/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 6.1.4, Date: 06-Jul-2012.
 */
#ifndef HNBAP_CONTAINERS_H
#define HNBAP_CONTAINERS_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdio.h>
#include <stdlib.h>
#include "rtkey.h"
#include "rtpersrc/asn1per.h"
#include "HNBAP-CommonDataTypes.h"

/**
 * Header file for ASN.1 module HNBAP-Containers
 */
/**************************************************************/
/*                                                            */
/*  ProtocolIE_Field                                          */
/*                                                            */
/**************************************************************/

typedef struct EXTERN ProtocolIE_Field {
   ProtocolIE_ID id;
   Criticality criticality;
   ASN1OpenType value;
} ProtocolIE_Field;

EXTERN int asn1PE_ProtocolIE_Field (OSCTXT* pctxt, ProtocolIE_Field* pvalue);

EXTERN int asn1PD_ProtocolIE_Field (OSCTXT* pctxt, ProtocolIE_Field* pvalue);

EXTERN void asn1Print_ProtocolIE_Field
   (const char* name, ProtocolIE_Field* pvalue);

EXTERN void asn1Init_ProtocolIE_Field (ProtocolIE_Field* pvalue);

/**************************************************************/
/*                                                            */
/*  ProtocolIE_Container                                      */
/*                                                            */
/**************************************************************/

/* List of ProtocolIE_Field */
typedef OSRTDList ProtocolIE_Container;

EXTERN int asn1PE_ProtocolIE_Container (OSCTXT* pctxt, ProtocolIE_Container* pvalue);

EXTERN int asn1PD_ProtocolIE_Container (OSCTXT* pctxt, ProtocolIE_Container* pvalue);

EXTERN void asn1Print_ProtocolIE_Container
   (const char* name, ProtocolIE_Container* pvalue);

EXTERN void asn1Init_ProtocolIE_Container (ProtocolIE_Container* pvalue);

/**************************************************************/
/*                                                            */
/*  ProtocolExtensionField                                    */
/*                                                            */
/**************************************************************/

typedef struct EXTERN ProtocolExtensionField {
   ProtocolIE_ID id;
   Criticality criticality;
   ASN1OpenType extensionValue;
} ProtocolExtensionField;

EXTERN int asn1PE_ProtocolExtensionField (OSCTXT* pctxt, ProtocolExtensionField* pvalue);

EXTERN int asn1PD_ProtocolExtensionField (OSCTXT* pctxt, ProtocolExtensionField* pvalue);

EXTERN void asn1Print_ProtocolExtensionField
   (const char* name, ProtocolExtensionField* pvalue);

EXTERN void asn1Init_ProtocolExtensionField (ProtocolExtensionField* pvalue);

/**************************************************************/
/*                                                            */
/*  ProtocolExtensionContainer                                */
/*                                                            */
/**************************************************************/

/* List of ProtocolExtensionField */
typedef OSRTDList ProtocolExtensionContainer;

EXTERN int asn1PE_ProtocolExtensionContainer (OSCTXT* pctxt, ProtocolExtensionContainer* pvalue);

EXTERN int asn1PD_ProtocolExtensionContainer (OSCTXT* pctxt, ProtocolExtensionContainer* pvalue);

EXTERN void asn1Print_ProtocolExtensionContainer
   (const char* name, ProtocolExtensionContainer* pvalue);

EXTERN void asn1Init_ProtocolExtensionContainer (ProtocolExtensionContainer* pvalue);

/**************************************************************/
/*                                                            */
/*  PrivateIE_Field                                           */
/*                                                            */
/**************************************************************/

typedef struct EXTERN PrivateIE_Field {
   PrivateIE_ID id;
   Criticality criticality;
   ASN1OpenType value;
} PrivateIE_Field;

EXTERN int asn1PE_PrivateIE_Field (OSCTXT* pctxt, PrivateIE_Field* pvalue);

EXTERN int asn1PD_PrivateIE_Field (OSCTXT* pctxt, PrivateIE_Field* pvalue);

EXTERN void asn1Print_PrivateIE_Field
   (const char* name, PrivateIE_Field* pvalue);

EXTERN void asn1Init_PrivateIE_Field (PrivateIE_Field* pvalue);

/**************************************************************/
/*                                                            */
/*  PrivateIE_Container                                       */
/*                                                            */
/**************************************************************/

/* List of PrivateIE_Field */
typedef OSRTDList PrivateIE_Container;

EXTERN int asn1PE_PrivateIE_Container (OSCTXT* pctxt, PrivateIE_Container* pvalue);

EXTERN int asn1PD_PrivateIE_Container (OSCTXT* pctxt, PrivateIE_Container* pvalue);

EXTERN void asn1Print_PrivateIE_Container
   (const char* name, PrivateIE_Container* pvalue);

EXTERN void asn1Init_PrivateIE_Container (PrivateIE_Container* pvalue);

/**************************************************************/
/*                                                            */
/*  ProtocolIE_Single_Container                               */
/*                                                            */
/**************************************************************/

typedef ProtocolIE_Field ProtocolIE_Single_Container;

EXTERN int asn1PE_ProtocolIE_Single_Container (OSCTXT* pctxt, ProtocolIE_Single_Container* pvalue);

EXTERN int asn1PD_ProtocolIE_Single_Container (OSCTXT* pctxt, ProtocolIE_Single_Container* pvalue);

EXTERN void asn1Print_ProtocolIE_Single_Container
   (const char* name, ProtocolIE_Single_Container* pvalue);

EXTERN void asn1Init_ProtocolIE_Single_Container (ProtocolIE_Single_Container* pvalue);

#ifdef __cplusplus
}
#endif

#endif
