/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 6.1.4, Date: 06-Jul-2012.
 */
#ifndef HNBAP_COMMONDATATYPES_H
#define HNBAP_COMMONDATATYPES_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdio.h>
#include <stdlib.h>
#include "rtkey.h"
#include "rtpersrc/asn1per.h"

/**
 * Header file for ASN.1 module HNBAP-CommonDataTypes
 */
/**************************************************************/
/*                                                            */
/*  ProcedureCode                                             */
/*                                                            */
/**************************************************************/

typedef OSUINT8 ProcedureCode;

EXTERN int asn1PE_ProcedureCode (OSCTXT* pctxt, ProcedureCode value);

EXTERN int asn1PD_ProcedureCode (OSCTXT* pctxt, ProcedureCode* pvalue);

EXTERN void asn1Print_ProcedureCode
   (const char* name, ProcedureCode* pvalue);

/**************************************************************/
/*                                                            */
/*  Criticality                                               */
/*                                                            */
/**************************************************************/

typedef enum {
   reject = 0,
   ignore = 1,
   notify = 2
} Criticality_Root;

typedef OSUINT32 Criticality;

EXTERN int asn1PE_Criticality (OSCTXT* pctxt, Criticality value);

EXTERN int asn1PD_Criticality (OSCTXT* pctxt, Criticality* pvalue);

EXTERN void asn1Print_Criticality
   (const char* name, Criticality* pvalue);

EXTERN const OSUTF8CHAR* Criticality_ToString (OSINT32 value);

EXTERN int Criticality_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, Criticality* pvalue);

/**************************************************************/
/*                                                            */
/*  ProtocolIE_ID                                             */
/*                                                            */
/**************************************************************/

typedef OSUINT16 ProtocolIE_ID;

EXTERN int asn1PE_ProtocolIE_ID (OSCTXT* pctxt, ProtocolIE_ID value);

EXTERN int asn1PD_ProtocolIE_ID (OSCTXT* pctxt, ProtocolIE_ID* pvalue);

EXTERN void asn1Print_ProtocolIE_ID
   (const char* name, ProtocolIE_ID* pvalue);

/**************************************************************/
/*                                                            */
/*  PrivateIE_ID                                              */
/*                                                            */
/**************************************************************/

/* Choice tag constants */

#define T_PrivateIE_ID_local            1
#define T_PrivateIE_ID_global           2

typedef struct EXTERN PrivateIE_ID {
   int t;
   union {
      /* t = 1 */
      OSUINT16 local;
      /* t = 2 */
      ASN1OBJID *global;
   } u;
} PrivateIE_ID;

EXTERN int asn1PE_PrivateIE_ID (OSCTXT* pctxt, PrivateIE_ID* pvalue);

EXTERN int asn1PD_PrivateIE_ID (OSCTXT* pctxt, PrivateIE_ID* pvalue);

EXTERN void asn1Print_PrivateIE_ID
   (const char* name, PrivateIE_ID* pvalue);

EXTERN void asn1Init_PrivateIE_ID (PrivateIE_ID* pvalue);

/**************************************************************/
/*                                                            */
/*  TriggeringMessage                                         */
/*                                                            */
/**************************************************************/

typedef enum {
   initiating_message = 0,
   successful_outcome = 1,
   unsuccessful_outcome = 2
} TriggeringMessage_Root;

typedef OSUINT32 TriggeringMessage;

EXTERN int asn1PE_TriggeringMessage (OSCTXT* pctxt, TriggeringMessage value);

EXTERN int asn1PD_TriggeringMessage (OSCTXT* pctxt, TriggeringMessage* pvalue);

EXTERN void asn1Print_TriggeringMessage
   (const char* name, TriggeringMessage* pvalue);

EXTERN const OSUTF8CHAR* TriggeringMessage_ToString (OSINT32 value);

EXTERN int TriggeringMessage_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, TriggeringMessage* pvalue);

/**************************************************************/
/*                                                            */
/*  Presence                                                  */
/*                                                            */
/**************************************************************/

typedef enum {
   optional = 0,
   conditional = 1,
   mandatory = 2
} Presence_Root;

typedef OSUINT32 Presence;

EXTERN int asn1PE_Presence (OSCTXT* pctxt, Presence value);

EXTERN int asn1PD_Presence (OSCTXT* pctxt, Presence* pvalue);

EXTERN void asn1Print_Presence
   (const char* name, Presence* pvalue);

EXTERN const OSUTF8CHAR* Presence_ToString (OSINT32 value);

EXTERN int Presence_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, Presence* pvalue);

/* Value definitions */

#define ASN1V_maxPrivateIEs 65535
#define ASN1V_maxProtocolExtensions 65535
#define ASN1V_maxProtocolIEs 65535

#ifdef __cplusplus
}
#endif

#endif
