/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 6.1.4, Date: 06-Jul-2012.
 */
#include "HNBAP-PDU-Descriptions.h"
#include "HNBAP-Constants.h"
#include "rtsrc/rtPrint.h"
#include "rtxsrc/rtxCommon.h"

void asn1Print_HnbInitiatingMessage
   (const char* name, HnbInitiatingMessage* pvalue)
{
   rtPrintOpenBrace (name);

   asn1Print_ProcedureCode ("procedureCode",
      &pvalue->procedureCode);

   asn1Print_Criticality ("criticality",
      &pvalue->criticality);

   rtPrintIndent ();
   rtPrintHexStr ("value",
      pvalue->value.numocts,
      pvalue->value.data);

   rtPrintCloseBrace ();
}

void asn1Print_HnbSuccessfulOutcome
   (const char* name, HnbSuccessfulOutcome* pvalue)
{
   rtPrintOpenBrace (name);

   asn1Print_ProcedureCode ("procedureCode",
      &pvalue->procedureCode);

   asn1Print_Criticality ("criticality",
      &pvalue->criticality);

   rtPrintIndent ();
   rtPrintHexStr ("value",
      pvalue->value.numocts,
      pvalue->value.data);

   rtPrintCloseBrace ();
}

void asn1Print_HnbUnsuccessfulOutcome
   (const char* name, HnbUnsuccessfulOutcome* pvalue)
{
   rtPrintOpenBrace (name);

   asn1Print_ProcedureCode ("procedureCode",
      &pvalue->procedureCode);

   asn1Print_Criticality ("criticality",
      &pvalue->criticality);

   rtPrintIndent ();
   rtPrintHexStr ("value",
      pvalue->value.numocts,
      pvalue->value.data);

   rtPrintCloseBrace ();
}

void asn1Print_HnbHNBAP_PDU
   (const char* name, HnbHNBAP_PDU* pvalue)
{
   rtPrintOpenBrace (name);

   switch (pvalue->t) {
      case 1: {
         asn1Print_HnbInitiatingMessage ("initiatingMessage",
            pvalue->u.initiatingMessage);
         break;
      }
      case 2: {
         asn1Print_HnbSuccessfulOutcome ("successfulOutcome",
            pvalue->u.successfulOutcome);
         break;
      }
      case 3: {
         asn1Print_HnbUnsuccessfulOutcome ("unsuccessfulOutcome",
            pvalue->u.unsuccessfulOutcome);
         break;
      }
      case 4: {
         rtPrintIndent ();
         rtPrintHexStr ("extElem1",
            pvalue->u.extElem1->numocts,
            pvalue->u.extElem1->data);
         break;
      }
      default:;
   }

   rtPrintCloseBrace ();
}

