/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 6.1.4, Date: 06-Jul-2012.
 */
#ifndef HNBAP_IES_H
#define HNBAP_IES_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdio.h>
#include <stdlib.h>
#include "rtkey.h"
#include "rtpersrc/asn1per.h"
#include "HNBAP-CommonDataTypes.h"
#include "HNBAP-Containers.h"

/**
 * Header file for ASN.1 module HNBAP-IEs
 */
/**************************************************************/
/*                                                            */
/*  Access_stratum_release_indicator                          */
/*                                                            */
/**************************************************************/

typedef enum {
   r99 = 0,
   rel_4 = 1,
   rel_5 = 2,
   rel_6 = 3,
   rel_7 = 4,
   rel_8 = 5
} Access_stratum_release_indicator_Root;

typedef OSUINT32 Access_stratum_release_indicator;

EXTERN int asn1PE_Access_stratum_release_indicator (OSCTXT* pctxt, Access_stratum_release_indicator value);

EXTERN int asn1PD_Access_stratum_release_indicator (OSCTXT* pctxt, Access_stratum_release_indicator* pvalue);

EXTERN void asn1Print_Access_stratum_release_indicator
   (const char* name, Access_stratum_release_indicator* pvalue);

EXTERN const OSUTF8CHAR* Access_stratum_release_indicator_ToString (OSINT32 value);

EXTERN int Access_stratum_release_indicator_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, Access_stratum_release_indicator* pvalue);

/**************************************************************/
/*                                                            */
/*  BackoffTimer                                              */
/*                                                            */
/**************************************************************/

typedef OSUINT16 BackoffTimer;

EXTERN int asn1PE_BackoffTimer (OSCTXT* pctxt, BackoffTimer value);

EXTERN int asn1PD_BackoffTimer (OSCTXT* pctxt, BackoffTimer* pvalue);

EXTERN void asn1Print_BackoffTimer
   (const char* name, BackoffTimer* pvalue);

/**************************************************************/
/*                                                            */
/*  CauseRadioNetwork                                         */
/*                                                            */
/**************************************************************/

typedef enum {
   overload = 0,
   unauthorised_Location = 1,
   unauthorised_HNB = 2,
   hNB_parameter_mismatch = 3,
   invalid_UE_identity = 4,
   uE_not_allowed_on_this_HNB = 5,
   uE_unauthorised = 6,
   connection_with_UE_lost = 7,
   ue_RRC_telease = 8,
   hNB_not_registered = 9,
   unspecified = 10,
   normal = 11,
   uE_relocated = 12,
   ue_registered_in_another_HNB = 13
} CauseRadioNetwork_Root;

typedef OSUINT32 CauseRadioNetwork;

EXTERN int asn1PE_CauseRadioNetwork (OSCTXT* pctxt, CauseRadioNetwork value);

EXTERN int asn1PD_CauseRadioNetwork (OSCTXT* pctxt, CauseRadioNetwork* pvalue);

EXTERN void asn1Print_CauseRadioNetwork
   (const char* name, CauseRadioNetwork* pvalue);

EXTERN const OSUTF8CHAR* CauseRadioNetwork_ToString (OSINT32 value);

EXTERN int CauseRadioNetwork_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, CauseRadioNetwork* pvalue);

/**************************************************************/
/*                                                            */
/*  CauseTransport                                            */
/*                                                            */
/**************************************************************/

typedef enum {
   transport_resource_unavailable = 0,
   unspecified_1 = 1
} CauseTransport_Root;

typedef OSUINT32 CauseTransport;

EXTERN int asn1PE_CauseTransport (OSCTXT* pctxt, CauseTransport value);

EXTERN int asn1PD_CauseTransport (OSCTXT* pctxt, CauseTransport* pvalue);

EXTERN void asn1Print_CauseTransport
   (const char* name, CauseTransport* pvalue);

EXTERN const OSUTF8CHAR* CauseTransport_ToString (OSINT32 value);

EXTERN int CauseTransport_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, CauseTransport* pvalue);

/**************************************************************/
/*                                                            */
/*  CauseProtocol                                             */
/*                                                            */
/**************************************************************/

typedef enum {
   transfer_syntax_error = 0,
   abstract_syntax_error_reject = 1,
   abstract_syntax_error_ignore_and_notify = 2,
   message_not_compatible_with_receiver_state = 3,
   semantic_error = 4,
   unspecified_2 = 5,
   abstract_syntax_error_falsely_constructed_message = 6
} CauseProtocol_Root;

typedef OSUINT32 CauseProtocol;

EXTERN int asn1PE_CauseProtocol (OSCTXT* pctxt, CauseProtocol value);

EXTERN int asn1PD_CauseProtocol (OSCTXT* pctxt, CauseProtocol* pvalue);

EXTERN void asn1Print_CauseProtocol
   (const char* name, CauseProtocol* pvalue);

EXTERN const OSUTF8CHAR* CauseProtocol_ToString (OSINT32 value);

EXTERN int CauseProtocol_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, CauseProtocol* pvalue);

/**************************************************************/
/*                                                            */
/*  CauseMisc                                                 */
/*                                                            */
/**************************************************************/

typedef enum {
   processing_overload = 0,
   hardware_failure = 1,
   o_and_m_intervention = 2,
   unspecified_3 = 3
} CauseMisc_Root;

typedef OSUINT32 CauseMisc;

EXTERN int asn1PE_CauseMisc (OSCTXT* pctxt, CauseMisc value);

EXTERN int asn1PD_CauseMisc (OSCTXT* pctxt, CauseMisc* pvalue);

EXTERN void asn1Print_CauseMisc
   (const char* name, CauseMisc* pvalue);

EXTERN const OSUTF8CHAR* CauseMisc_ToString (OSINT32 value);

EXTERN int CauseMisc_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, CauseMisc* pvalue);

/**************************************************************/
/*                                                            */
/*  CellIdentity                                              */
/*                                                            */
/**************************************************************/

typedef struct EXTERN CellIdentity {
   OSUINT32  numbits;
   OSOCTET data[4];
} CellIdentity;

EXTERN int asn1PE_CellIdentity (OSCTXT* pctxt, CellIdentity* pvalue);

EXTERN int asn1PD_CellIdentity (OSCTXT* pctxt, CellIdentity* pvalue);

EXTERN void asn1Print_CellIdentity
   (const char* name, CellIdentity* pvalue);

EXTERN void asn1Init_CellIdentity (CellIdentity* pvalue);

/**************************************************************/
/*                                                            */
/*  Context_ID                                                */
/*                                                            */
/**************************************************************/

typedef struct EXTERN Context_ID {
   OSUINT32  numbits;
   OSOCTET data[3];
} Context_ID;

EXTERN int asn1PE_Context_ID (OSCTXT* pctxt, Context_ID* pvalue);

EXTERN int asn1PD_Context_ID (OSCTXT* pctxt, Context_ID* pvalue);

EXTERN void asn1Print_Context_ID
   (const char* name, Context_ID* pvalue);

EXTERN void asn1Init_Context_ID (Context_ID* pvalue);

/**************************************************************/
/*                                                            */
/*  CSG_ID                                                    */
/*                                                            */
/**************************************************************/

typedef struct EXTERN CSG_ID {
   OSUINT32  numbits;
   OSOCTET data[4];
} CSG_ID;

EXTERN int asn1PE_CSG_ID (OSCTXT* pctxt, CSG_ID* pvalue);

EXTERN int asn1PD_CSG_ID (OSCTXT* pctxt, CSG_ID* pvalue);

EXTERN void asn1Print_CSG_ID
   (const char* name, CSG_ID* pvalue);

EXTERN void asn1Init_CSG_ID (CSG_ID* pvalue);

/**************************************************************/
/*                                                            */
/*  CSG_Indicator                                             */
/*                                                            */
/**************************************************************/

typedef enum {
   csg_capable = 0,
   not_csg_capable = 1
} CSG_Indicator_Root;

typedef OSUINT32 CSG_Indicator;

EXTERN int asn1PE_CSG_Indicator (OSCTXT* pctxt, CSG_Indicator value);

EXTERN int asn1PD_CSG_Indicator (OSCTXT* pctxt, CSG_Indicator* pvalue);

EXTERN void asn1Print_CSG_Indicator
   (const char* name, CSG_Indicator* pvalue);

EXTERN const OSUTF8CHAR* CSG_Indicator_ToString (OSINT32 value);

EXTERN int CSG_Indicator_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, CSG_Indicator* pvalue);

/**************************************************************/
/*                                                            */
/*  CI                                                        */
/*                                                            */
/**************************************************************/

typedef struct EXTERN CI {
   OSUINT32 numocts;
   OSOCTET data[2];
} CI;

EXTERN int asn1PE_CI (OSCTXT* pctxt, CI* pvalue);

EXTERN int asn1PD_CI (OSCTXT* pctxt, CI* pvalue);

EXTERN void asn1Print_CI
   (const char* name, CI* pvalue);

EXTERN void asn1Init_CI (CI* pvalue);

/**************************************************************/
/*                                                            */
/*  CN_DomainIndicator                                        */
/*                                                            */
/**************************************************************/

typedef enum {
   cs_domain = 0,
   ps_domain = 1
} CN_DomainIndicator_Root;

typedef OSUINT32 CN_DomainIndicator;

EXTERN int asn1PE_CN_DomainIndicator (OSCTXT* pctxt, CN_DomainIndicator value);

EXTERN int asn1PD_CN_DomainIndicator (OSCTXT* pctxt, CN_DomainIndicator* pvalue);

EXTERN void asn1Print_CN_DomainIndicator
   (const char* name, CN_DomainIndicator* pvalue);

EXTERN const OSUTF8CHAR* CN_DomainIndicator_ToString (OSINT32 value);

EXTERN int CN_DomainIndicator_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, CN_DomainIndicator* pvalue);

/**************************************************************/
/*                                                            */
/*  ESN                                                       */
/*                                                            */
/**************************************************************/

typedef struct EXTERN ESN {
   OSUINT32  numbits;
   OSOCTET data[4];
} ESN;

EXTERN int asn1PE_ESN (OSCTXT* pctxt, ESN* pvalue);

EXTERN int asn1PD_ESN (OSCTXT* pctxt, ESN* pvalue);

EXTERN void asn1Print_ESN
   (const char* name, ESN* pvalue);

EXTERN void asn1Init_ESN (ESN* pvalue);

/**************************************************************/
/*                                                            */
/*  HNB_Identity_Info                                         */
/*                                                            */
/**************************************************************/

typedef struct EXTERN HNB_Identity_Info {
   OSUINT32 numocts;
   OSOCTET data[255];
} HNB_Identity_Info;

EXTERN int asn1PE_HNB_Identity_Info (OSCTXT* pctxt, HNB_Identity_Info* pvalue);

EXTERN int asn1PD_HNB_Identity_Info (OSCTXT* pctxt, HNB_Identity_Info* pvalue);

EXTERN void asn1Print_HNB_Identity_Info
   (const char* name, HNB_Identity_Info* pvalue);

EXTERN void asn1Init_HNB_Identity_Info (HNB_Identity_Info* pvalue);

/**************************************************************/
/*                                                            */
/*  IMEI                                                      */
/*                                                            */
/**************************************************************/

typedef struct EXTERN IMEI {
   OSUINT32  numbits;
   OSOCTET data[8];
} IMEI;

EXTERN int asn1PE_IMEI (OSCTXT* pctxt, IMEI* pvalue);

EXTERN int asn1PD_IMEI (OSCTXT* pctxt, IMEI* pvalue);

EXTERN void asn1Print_IMEI
   (const char* name, IMEI* pvalue);

EXTERN void asn1Init_IMEI (IMEI* pvalue);

/**************************************************************/
/*                                                            */
/*  IMSI                                                      */
/*                                                            */
/**************************************************************/

typedef struct EXTERN IMSI {
   OSUINT32 numocts;
   OSOCTET data[8];
} IMSI;

EXTERN int asn1PE_IMSI (OSCTXT* pctxt, IMSI* pvalue);

EXTERN int asn1PD_IMSI (OSCTXT* pctxt, IMSI* pvalue);

EXTERN void asn1Print_IMSI
   (const char* name, IMSI* pvalue);

EXTERN void asn1Init_IMSI (IMSI* pvalue);

/**************************************************************/
/*                                                            */
/*  IMSIDS41                                                  */
/*                                                            */
/**************************************************************/

typedef struct EXTERN IMSIDS41 {
   OSUINT32 numocts;
   OSOCTET data[7];
} IMSIDS41;

EXTERN int asn1PE_IMSIDS41 (OSCTXT* pctxt, IMSIDS41* pvalue);

EXTERN int asn1PD_IMSIDS41 (OSCTXT* pctxt, IMSIDS41* pvalue);

EXTERN void asn1Print_IMSIDS41
   (const char* name, IMSIDS41* pvalue);

EXTERN void asn1Init_IMSIDS41 (IMSIDS41* pvalue);

/**************************************************************/
/*                                                            */
/*  Ipv4Address                                               */
/*                                                            */
/**************************************************************/

typedef struct EXTERN Ipv4Address {
   OSUINT32 numocts;
   OSOCTET data[4];
} Ipv4Address;

EXTERN int asn1PE_Ipv4Address (OSCTXT* pctxt, Ipv4Address* pvalue);

EXTERN int asn1PD_Ipv4Address (OSCTXT* pctxt, Ipv4Address* pvalue);

EXTERN void asn1Print_Ipv4Address
   (const char* name, Ipv4Address* pvalue);

EXTERN void asn1Init_Ipv4Address (Ipv4Address* pvalue);

/**************************************************************/
/*                                                            */
/*  Ipv6Address                                               */
/*                                                            */
/**************************************************************/

typedef struct EXTERN Ipv6Address {
   OSUINT32 numocts;
   OSOCTET data[16];
} Ipv6Address;

EXTERN int asn1PE_Ipv6Address (OSCTXT* pctxt, Ipv6Address* pvalue);

EXTERN int asn1PD_Ipv6Address (OSCTXT* pctxt, Ipv6Address* pvalue);

EXTERN void asn1Print_Ipv6Address
   (const char* name, Ipv6Address* pvalue);

EXTERN void asn1Init_Ipv6Address (Ipv6Address* pvalue);

/**************************************************************/
/*                                                            */
/*  LAC                                                       */
/*                                                            */
/**************************************************************/

typedef struct EXTERN LAC {
   OSUINT32 numocts;
   OSOCTET data[2];
} LAC;

EXTERN int asn1PE_LAC (OSCTXT* pctxt, LAC* pvalue);

EXTERN int asn1PD_LAC (OSCTXT* pctxt, LAC* pvalue);

EXTERN void asn1Print_LAC
   (const char* name, LAC* pvalue);

EXTERN void asn1Init_LAC (LAC* pvalue);

/**************************************************************/
/*                                                            */
/*  PLMNidentity                                              */
/*                                                            */
/**************************************************************/

typedef struct EXTERN PLMNidentity {
   OSUINT32 numocts;
   OSOCTET data[3];
} PLMNidentity;

EXTERN int asn1PE_PLMNidentity (OSCTXT* pctxt, PLMNidentity* pvalue);

EXTERN int asn1PD_PLMNidentity (OSCTXT* pctxt, PLMNidentity* pvalue);

EXTERN void asn1Print_PLMNidentity
   (const char* name, PLMNidentity* pvalue);

EXTERN void asn1Init_PLMNidentity (PLMNidentity* pvalue);

/**************************************************************/
/*                                                            */
/*  PTMSI                                                     */
/*                                                            */
/**************************************************************/

typedef struct EXTERN PTMSI {
   OSUINT32  numbits;
   OSOCTET data[4];
} PTMSI;

EXTERN int asn1PE_PTMSI (OSCTXT* pctxt, PTMSI* pvalue);

EXTERN int asn1PD_PTMSI (OSCTXT* pctxt, PTMSI* pvalue);

EXTERN void asn1Print_PTMSI
   (const char* name, PTMSI* pvalue);

EXTERN void asn1Init_PTMSI (PTMSI* pvalue);

/**************************************************************/
/*                                                            */
/*  RAC                                                       */
/*                                                            */
/**************************************************************/

typedef struct EXTERN RAC {
   OSUINT32 numocts;
   OSOCTET data[1];
} RAC;

EXTERN int asn1PE_RAC (OSCTXT* pctxt, RAC* pvalue);

EXTERN int asn1PD_RAC (OSCTXT* pctxt, RAC* pvalue);

EXTERN void asn1Print_RAC
   (const char* name, RAC* pvalue);

EXTERN void asn1Init_RAC (RAC* pvalue);

/**************************************************************/
/*                                                            */
/*  Registration_Cause                                        */
/*                                                            */
/**************************************************************/

typedef enum {
   emergency_call = 0,
   normal_1 = 1
} Registration_Cause_Root;

typedef OSUINT32 Registration_Cause;

EXTERN int asn1PE_Registration_Cause (OSCTXT* pctxt, Registration_Cause value);

EXTERN int asn1PD_Registration_Cause (OSCTXT* pctxt, Registration_Cause* pvalue);

EXTERN void asn1Print_Registration_Cause
   (const char* name, Registration_Cause* pvalue);

EXTERN const OSUTF8CHAR* Registration_Cause_ToString (OSINT32 value);

EXTERN int Registration_Cause_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, Registration_Cause* pvalue);

/**************************************************************/
/*                                                            */
/*  RNC_ID                                                    */
/*                                                            */
/**************************************************************/

typedef OSUINT16 RNC_ID;

EXTERN int asn1PE_RNC_ID (OSCTXT* pctxt, RNC_ID value);

EXTERN int asn1PD_RNC_ID (OSCTXT* pctxt, RNC_ID* pvalue);

EXTERN void asn1Print_RNC_ID
   (const char* name, RNC_ID* pvalue);

/**************************************************************/
/*                                                            */
/*  SAC                                                       */
/*                                                            */
/**************************************************************/

typedef struct EXTERN SAC {
   OSUINT32 numocts;
   OSOCTET data[2];
} SAC;

EXTERN int asn1PE_SAC (OSCTXT* pctxt, SAC* pvalue);

EXTERN int asn1PD_SAC (OSCTXT* pctxt, SAC* pvalue);

EXTERN void asn1Print_SAC
   (const char* name, SAC* pvalue);

EXTERN void asn1Init_SAC (SAC* pvalue);

/**************************************************************/
/*                                                            */
/*  TMSIDS41                                                  */
/*                                                            */
/**************************************************************/

typedef struct EXTERN TMSIDS41 {
   OSUINT32 numocts;
   OSOCTET data[17];
} TMSIDS41;

EXTERN int asn1PE_TMSIDS41 (OSCTXT* pctxt, TMSIDS41* pvalue);

EXTERN int asn1PD_TMSIDS41 (OSCTXT* pctxt, TMSIDS41* pvalue);

EXTERN void asn1Print_TMSIDS41
   (const char* name, TMSIDS41* pvalue);

EXTERN void asn1Init_TMSIDS41 (TMSIDS41* pvalue);

/**************************************************************/
/*                                                            */
/*  TypeOfError                                               */
/*                                                            */
/**************************************************************/

typedef enum {
   not_understood = 0,
   missing = 1
} TypeOfError_Root;

typedef OSUINT32 TypeOfError;

EXTERN int asn1PE_TypeOfError (OSCTXT* pctxt, TypeOfError value);

EXTERN int asn1PD_TypeOfError (OSCTXT* pctxt, TypeOfError* pvalue);

EXTERN void asn1Print_TypeOfError
   (const char* name, TypeOfError* pvalue);

EXTERN const OSUTF8CHAR* TypeOfError_ToString (OSINT32 value);

EXTERN int TypeOfError_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, TypeOfError* pvalue);

/**************************************************************/
/*                                                            */
/*  AltitudeAndDirection_directionOfAltitude                  */
/*                                                            */
/**************************************************************/

typedef enum {
   height = 0,
   depth = 1
} AltitudeAndDirection_directionOfAltitude_Root;

typedef OSUINT32 AltitudeAndDirection_directionOfAltitude;

EXTERN int asn1PE_AltitudeAndDirection_directionOfAltitude (OSCTXT* pctxt, AltitudeAndDirection_directionOfAltitude value);

EXTERN int asn1PD_AltitudeAndDirection_directionOfAltitude (OSCTXT* pctxt, AltitudeAndDirection_directionOfAltitude* pvalue);

EXTERN void asn1Print_AltitudeAndDirection_directionOfAltitude
   (const char* name, AltitudeAndDirection_directionOfAltitude* pvalue);

EXTERN const OSUTF8CHAR* AltitudeAndDirection_directionOfAltitude_ToString (OSINT32 value);

EXTERN int AltitudeAndDirection_directionOfAltitude_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, AltitudeAndDirection_directionOfAltitude* pvalue);

/**************************************************************/
/*                                                            */
/*  GeographicalCoordinates_latitudeSign                      */
/*                                                            */
/**************************************************************/

typedef enum {
   north = 0,
   south = 1
} GeographicalCoordinates_latitudeSign_Root;

typedef OSUINT32 GeographicalCoordinates_latitudeSign;

EXTERN int asn1PE_GeographicalCoordinates_latitudeSign (OSCTXT* pctxt, GeographicalCoordinates_latitudeSign value);

EXTERN int asn1PD_GeographicalCoordinates_latitudeSign (OSCTXT* pctxt, GeographicalCoordinates_latitudeSign* pvalue);

EXTERN void asn1Print_GeographicalCoordinates_latitudeSign
   (const char* name, GeographicalCoordinates_latitudeSign* pvalue);

EXTERN const OSUTF8CHAR* GeographicalCoordinates_latitudeSign_ToString (OSINT32 value);

EXTERN int GeographicalCoordinates_latitudeSign_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, GeographicalCoordinates_latitudeSign* pvalue);

/**************************************************************/
/*                                                            */
/*  TMSILAI_tMSI                                              */
/*                                                            */
/**************************************************************/

typedef struct EXTERN TMSILAI_tMSI {
   OSUINT32  numbits;
   OSOCTET data[4];
} TMSILAI_tMSI;

EXTERN int asn1PE_TMSILAI_tMSI (OSCTXT* pctxt, TMSILAI_tMSI* pvalue);

EXTERN int asn1PD_TMSILAI_tMSI (OSCTXT* pctxt, TMSILAI_tMSI* pvalue);

EXTERN void asn1Print_TMSILAI_tMSI
   (const char* name, TMSILAI_tMSI* pvalue);

EXTERN void asn1Init_TMSILAI_tMSI (TMSILAI_tMSI* pvalue);

/**************************************************************/
/*                                                            */
/*  AltitudeAndDirection                                      */
/*                                                            */
/**************************************************************/

typedef struct EXTERN AltitudeAndDirection {
   AltitudeAndDirection_directionOfAltitude directionOfAltitude;
   OSUINT16 altitude;
   OSRTDList extElem1;
} AltitudeAndDirection;

EXTERN int asn1PE_AltitudeAndDirection (OSCTXT* pctxt, AltitudeAndDirection* pvalue);

EXTERN int asn1PD_AltitudeAndDirection (OSCTXT* pctxt, AltitudeAndDirection* pvalue);

EXTERN void asn1Print_AltitudeAndDirection
   (const char* name, AltitudeAndDirection* pvalue);

EXTERN void asn1Init_AltitudeAndDirection (AltitudeAndDirection* pvalue);

/**************************************************************/
/*                                                            */
/*  Cause                                                     */
/*                                                            */
/**************************************************************/

/* Choice tag constants */

#define T_Cause_radioNetwork            1
#define T_Cause_transport               2
#define T_Cause_protocol                3
#define T_Cause_misc                    4
#define T_Cause_extElem1                5

typedef struct EXTERN Cause {
   int t;
   union {
      /* t = 1 */
      CauseRadioNetwork radioNetwork;
      /* t = 2 */
      CauseTransport transport;
      /* t = 3 */
      CauseProtocol protocol;
      /* t = 4 */
      CauseMisc misc;
      /* t = 5 */
      ASN1OpenType *extElem1;
   } u;
} Cause;

EXTERN int asn1PE_Cause (OSCTXT* pctxt, Cause* pvalue);

EXTERN int asn1PD_Cause (OSCTXT* pctxt, Cause* pvalue);

EXTERN void asn1Print_Cause
   (const char* name, Cause* pvalue);

EXTERN void asn1Init_Cause (Cause* pvalue);

/**************************************************************/
/*                                                            */
/*  CriticalityDiagnostics_IE_List_element                    */
/*                                                            */
/**************************************************************/

typedef struct EXTERN CriticalityDiagnostics_IE_List_element {
   struct {
      unsigned iE_ExtensionsPresent : 1;
   } m;
   Criticality iECriticality;
   ProtocolIE_ID iE_ID;
   TypeOfError typeOfError;
   ProtocolExtensionContainer iE_Extensions;
   OSRTDList extElem1;
} CriticalityDiagnostics_IE_List_element;

EXTERN int asn1PE_CriticalityDiagnostics_IE_List_element (OSCTXT* pctxt, CriticalityDiagnostics_IE_List_element* pvalue);

EXTERN int asn1PD_CriticalityDiagnostics_IE_List_element (OSCTXT* pctxt, CriticalityDiagnostics_IE_List_element* pvalue);

EXTERN void asn1Print_CriticalityDiagnostics_IE_List_element
   (const char* name, CriticalityDiagnostics_IE_List_element* pvalue);

EXTERN void asn1Init_CriticalityDiagnostics_IE_List_element (
   CriticalityDiagnostics_IE_List_element* pvalue);

/**************************************************************/
/*                                                            */
/*  CriticalityDiagnostics_IE_List                            */
/*                                                            */
/**************************************************************/

/* List of CriticalityDiagnostics_IE_List_element */
typedef OSRTDList CriticalityDiagnostics_IE_List;

EXTERN int asn1PE_CriticalityDiagnostics_IE_List (OSCTXT* pctxt, CriticalityDiagnostics_IE_List* pvalue);

EXTERN int asn1PD_CriticalityDiagnostics_IE_List (OSCTXT* pctxt, CriticalityDiagnostics_IE_List* pvalue);

EXTERN void asn1Print_CriticalityDiagnostics_IE_List
   (const char* name, CriticalityDiagnostics_IE_List* pvalue);

EXTERN void asn1Init_CriticalityDiagnostics_IE_List (
   CriticalityDiagnostics_IE_List* pvalue);

/**************************************************************/
/*                                                            */
/*  CriticalityDiagnostics                                    */
/*                                                            */
/**************************************************************/

typedef struct EXTERN CriticalityDiagnostics {
   struct {
      unsigned procedureCodePresent : 1;
      unsigned triggeringMessagePresent : 1;
      unsigned procedureCriticalityPresent : 1;
      unsigned iEsCriticalityDiagnosticsPresent : 1;
      unsigned iE_ExtensionsPresent : 1;
   } m;
   ProcedureCode procedureCode;
   TriggeringMessage triggeringMessage;
   Criticality procedureCriticality;
   CriticalityDiagnostics_IE_List iEsCriticalityDiagnostics;
   ProtocolExtensionContainer iE_Extensions;
   OSRTDList extElem1;
} CriticalityDiagnostics;

EXTERN int asn1PE_CriticalityDiagnostics (OSCTXT* pctxt, CriticalityDiagnostics* pvalue);

EXTERN int asn1PD_CriticalityDiagnostics (OSCTXT* pctxt, CriticalityDiagnostics* pvalue);

EXTERN void asn1Print_CriticalityDiagnostics
   (const char* name, CriticalityDiagnostics* pvalue);

EXTERN void asn1Init_CriticalityDiagnostics (CriticalityDiagnostics* pvalue);

/**************************************************************/
/*                                                            */
/*  CGI                                                       */
/*                                                            */
/**************************************************************/

typedef struct EXTERN CGI {
   struct {
      unsigned iE_ExtensionsPresent : 1;
   } m;
   PLMNidentity pLMNidentity;
   LAC lAC;
   CI cI;
   ProtocolExtensionContainer iE_Extensions;
} CGI;

EXTERN int asn1PE_CGI (OSCTXT* pctxt, CGI* pvalue);

EXTERN int asn1PD_CGI (OSCTXT* pctxt, CGI* pvalue);

EXTERN void asn1Print_CGI
   (const char* name, CGI* pvalue);

EXTERN void asn1Init_CGI (CGI* pvalue);

/**************************************************************/
/*                                                            */
/*  GeographicalCoordinates                                   */
/*                                                            */
/**************************************************************/

typedef struct EXTERN GeographicalCoordinates {
   struct {
      unsigned iE_ExtensionsPresent : 1;
   } m;
   GeographicalCoordinates_latitudeSign latitudeSign;
   OSUINT32 latitude;
   OSINT32 longitude;
   ProtocolExtensionContainer iE_Extensions;
   OSRTDList extElem1;
} GeographicalCoordinates;

EXTERN int asn1PE_GeographicalCoordinates (OSCTXT* pctxt, GeographicalCoordinates* pvalue);

EXTERN int asn1PD_GeographicalCoordinates (OSCTXT* pctxt, GeographicalCoordinates* pvalue);

EXTERN void asn1Print_GeographicalCoordinates
   (const char* name, GeographicalCoordinates* pvalue);

EXTERN void asn1Init_GeographicalCoordinates (GeographicalCoordinates* pvalue);

/**************************************************************/
/*                                                            */
/*  GeographicalLocation                                      */
/*                                                            */
/**************************************************************/

typedef struct EXTERN GeographicalLocation {
   struct {
      unsigned iE_ExtensionsPresent : 1;
   } m;
   GeographicalCoordinates geographicalCoordinates;
   AltitudeAndDirection altitudeAndDirection;
   ProtocolExtensionContainer iE_Extensions;
   OSRTDList extElem1;
} GeographicalLocation;

EXTERN int asn1PE_GeographicalLocation (OSCTXT* pctxt, GeographicalLocation* pvalue);

EXTERN int asn1PD_GeographicalLocation (OSCTXT* pctxt, GeographicalLocation* pvalue);

EXTERN void asn1Print_GeographicalLocation
   (const char* name, GeographicalLocation* pvalue);

EXTERN void asn1Init_GeographicalLocation (GeographicalLocation* pvalue);

/**************************************************************/
/*                                                            */
/*  UTRANCellID                                               */
/*                                                            */
/**************************************************************/

typedef struct EXTERN UTRANCellID {
   struct {
      unsigned iE_ExtensionsPresent : 1;
   } m;
   LAC lAC;
   RAC rAC;
   PLMNidentity pLMNidentity;
   CellIdentity uTRANcellID;
   ProtocolExtensionContainer iE_Extensions;
} UTRANCellID;

EXTERN int asn1PE_UTRANCellID (OSCTXT* pctxt, UTRANCellID* pvalue);

EXTERN int asn1PD_UTRANCellID (OSCTXT* pctxt, UTRANCellID* pvalue);

EXTERN void asn1Print_UTRANCellID
   (const char* name, UTRANCellID* pvalue);

EXTERN void asn1Init_UTRANCellID (UTRANCellID* pvalue);

/**************************************************************/
/*                                                            */
/*  MacroCellID                                               */
/*                                                            */
/**************************************************************/

/* Choice tag constants */

#define T_MacroCellID_uTRANCellID       1
#define T_MacroCellID_gERANCellID       2
#define T_MacroCellID_extElem1          3

typedef struct EXTERN MacroCellID {
   int t;
   union {
      /* t = 1 */
      UTRANCellID *uTRANCellID;
      /* t = 2 */
      CGI *gERANCellID;
      /* t = 3 */
      ASN1OpenType *extElem1;
   } u;
} MacroCellID;

EXTERN int asn1PE_MacroCellID (OSCTXT* pctxt, MacroCellID* pvalue);

EXTERN int asn1PD_MacroCellID (OSCTXT* pctxt, MacroCellID* pvalue);

EXTERN void asn1Print_MacroCellID
   (const char* name, MacroCellID* pvalue);

EXTERN void asn1Init_MacroCellID (MacroCellID* pvalue);

/**************************************************************/
/*                                                            */
/*  MacroCoverageInformation                                  */
/*                                                            */
/**************************************************************/

typedef struct EXTERN MacroCoverageInformation {
   struct {
      unsigned iE_ExtensionsPresent : 1;
   } m;
   MacroCellID cellIdentity;
   ProtocolExtensionContainer iE_Extensions;
   OSRTDList extElem1;
} MacroCoverageInformation;

EXTERN int asn1PE_MacroCoverageInformation (OSCTXT* pctxt, MacroCoverageInformation* pvalue);

EXTERN int asn1PD_MacroCoverageInformation (OSCTXT* pctxt, MacroCoverageInformation* pvalue);

EXTERN void asn1Print_MacroCoverageInformation
   (const char* name, MacroCoverageInformation* pvalue);

EXTERN void asn1Init_MacroCoverageInformation (MacroCoverageInformation* pvalue);

/**************************************************************/
/*                                                            */
/*  HNB_Location_Information                                  */
/*                                                            */
/**************************************************************/

typedef struct EXTERN HNB_Location_Information {
   struct {
      unsigned macroCoverageInfoPresent : 1;
      unsigned geographicalCoordinatesPresent : 1;
      unsigned iE_ExtensionsPresent : 1;
   } m;
   MacroCoverageInformation macroCoverageInfo;
   GeographicalLocation geographicalCoordinates;
   ProtocolExtensionContainer iE_Extensions;
   OSRTDList extElem1;
} HNB_Location_Information;

EXTERN int asn1PE_HNB_Location_Information (OSCTXT* pctxt, HNB_Location_Information* pvalue);

EXTERN int asn1PD_HNB_Location_Information (OSCTXT* pctxt, HNB_Location_Information* pvalue);

EXTERN void asn1Print_HNB_Location_Information
   (const char* name, HNB_Location_Information* pvalue);

EXTERN void asn1Init_HNB_Location_Information (HNB_Location_Information* pvalue);

/**************************************************************/
/*                                                            */
/*  HNB_Identity                                              */
/*                                                            */
/**************************************************************/

typedef struct EXTERN HNB_Identity {
   struct {
      unsigned iE_ExtensionsPresent : 1;
   } m;
   HNB_Identity_Info hNB_Identity_Info;
   ProtocolExtensionContainer iE_Extensions;
   OSRTDList extElem1;
} HNB_Identity;

EXTERN int asn1PE_HNB_Identity (OSCTXT* pctxt, HNB_Identity* pvalue);

EXTERN int asn1PD_HNB_Identity (OSCTXT* pctxt, HNB_Identity* pvalue);

EXTERN void asn1Print_HNB_Identity
   (const char* name, HNB_Identity* pvalue);

EXTERN void asn1Init_HNB_Identity (HNB_Identity* pvalue);

/**************************************************************/
/*                                                            */
/*  IMSIESN                                                   */
/*                                                            */
/**************************************************************/

typedef struct EXTERN IMSIESN {
   IMSIDS41 iMSIDS41;
   ESN eSN;
} IMSIESN;

EXTERN int asn1PE_IMSIESN (OSCTXT* pctxt, IMSIESN* pvalue);

EXTERN int asn1PD_IMSIESN (OSCTXT* pctxt, IMSIESN* pvalue);

EXTERN void asn1Print_IMSIESN
   (const char* name, IMSIESN* pvalue);

EXTERN void asn1Init_IMSIESN (IMSIESN* pvalue);

/**************************************************************/
/*                                                            */
/*  IP_Address_ipaddress                                      */
/*                                                            */
/**************************************************************/

/* Choice tag constants */

#define T_IP_Address_ipaddress_ipv4info 1
#define T_IP_Address_ipaddress_ipv6info 2
#define T_IP_Address_ipaddress_extElem1 3

typedef struct EXTERN IP_Address_ipaddress {
   int t;
   union {
      /* t = 1 */
      Ipv4Address *ipv4info;
      /* t = 2 */
      Ipv6Address *ipv6info;
      /* t = 3 */
      ASN1OpenType *extElem1;
   } u;
} IP_Address_ipaddress;

EXTERN int asn1PE_IP_Address_ipaddress (OSCTXT* pctxt, IP_Address_ipaddress* pvalue);

EXTERN int asn1PD_IP_Address_ipaddress (OSCTXT* pctxt, IP_Address_ipaddress* pvalue);

EXTERN void asn1Print_IP_Address_ipaddress
   (const char* name, IP_Address_ipaddress* pvalue);

EXTERN void asn1Init_IP_Address_ipaddress (IP_Address_ipaddress* pvalue);

/**************************************************************/
/*                                                            */
/*  IP_Address                                                */
/*                                                            */
/**************************************************************/

typedef struct EXTERN IP_Address {
   struct {
      unsigned iE_ExtensionsPresent : 1;
   } m;
   IP_Address_ipaddress ipaddress;
   ProtocolExtensionContainer iE_Extensions;
   OSRTDList extElem1;
} IP_Address;

EXTERN int asn1PE_IP_Address (OSCTXT* pctxt, IP_Address* pvalue);

EXTERN int asn1PD_IP_Address (OSCTXT* pctxt, IP_Address* pvalue);

EXTERN void asn1Print_IP_Address
   (const char* name, IP_Address* pvalue);

EXTERN void asn1Init_IP_Address (IP_Address* pvalue);

/**************************************************************/
/*                                                            */
/*  LAI                                                       */
/*                                                            */
/**************************************************************/

typedef struct EXTERN LAI {
   PLMNidentity pLMNID;
   LAC lAC;
   OSRTDList extElem1;
} LAI;

EXTERN int asn1PE_LAI (OSCTXT* pctxt, LAI* pvalue);

EXTERN int asn1PD_LAI (OSCTXT* pctxt, LAI* pvalue);

EXTERN void asn1Print_LAI
   (const char* name, LAI* pvalue);

EXTERN void asn1Init_LAI (LAI* pvalue);

/**************************************************************/
/*                                                            */
/*  RAI                                                       */
/*                                                            */
/**************************************************************/

typedef struct EXTERN RAI {
   LAI lAI;
   RAC rAC;
   OSRTDList extElem1;
} RAI;

EXTERN int asn1PE_RAI (OSCTXT* pctxt, RAI* pvalue);

EXTERN int asn1PD_RAI (OSCTXT* pctxt, RAI* pvalue);

EXTERN void asn1Print_RAI
   (const char* name, RAI* pvalue);

EXTERN void asn1Init_RAI (RAI* pvalue);

/**************************************************************/
/*                                                            */
/*  PTMSIRAI                                                  */
/*                                                            */
/**************************************************************/

typedef struct EXTERN PTMSIRAI {
   PTMSI pTMSI;
   RAI rAI;
   OSRTDList extElem1;
} PTMSIRAI;

EXTERN int asn1PE_PTMSIRAI (OSCTXT* pctxt, PTMSIRAI* pvalue);

EXTERN int asn1PD_PTMSIRAI (OSCTXT* pctxt, PTMSIRAI* pvalue);

EXTERN void asn1Print_PTMSIRAI
   (const char* name, PTMSIRAI* pvalue);

EXTERN void asn1Init_PTMSIRAI (PTMSIRAI* pvalue);

/**************************************************************/
/*                                                            */
/*  TMSILAI                                                   */
/*                                                            */
/**************************************************************/

typedef struct EXTERN TMSILAI {
   TMSILAI_tMSI tMSI;
   LAI lAI;
} TMSILAI;

EXTERN int asn1PE_TMSILAI (OSCTXT* pctxt, TMSILAI* pvalue);

EXTERN int asn1PD_TMSILAI (OSCTXT* pctxt, TMSILAI* pvalue);

EXTERN void asn1Print_TMSILAI
   (const char* name, TMSILAI* pvalue);

EXTERN void asn1Init_TMSILAI (TMSILAI* pvalue);

/**************************************************************/
/*                                                            */
/*  UE_Capabilities                                           */
/*                                                            */
/**************************************************************/

typedef struct EXTERN UE_Capabilities {
   struct {
      unsigned iE_ExtensionsPresent : 1;
   } m;
   Access_stratum_release_indicator access_stratum_release_indicator;
   CSG_Indicator csg_indicator;
   ProtocolExtensionContainer iE_Extensions;
   OSRTDList extElem1;
} UE_Capabilities;

EXTERN int asn1PE_UE_Capabilities (OSCTXT* pctxt, UE_Capabilities* pvalue);

EXTERN int asn1PD_UE_Capabilities (OSCTXT* pctxt, UE_Capabilities* pvalue);

EXTERN void asn1Print_UE_Capabilities
   (const char* name, UE_Capabilities* pvalue);

EXTERN void asn1Init_UE_Capabilities (UE_Capabilities* pvalue);

/**************************************************************/
/*                                                            */
/*  UE_Identity                                               */
/*                                                            */
/**************************************************************/

/* Choice tag constants */

#define T_UE_Identity_iMSI              1
#define T_UE_Identity_tMSILAI           2
#define T_UE_Identity_pTMSIRAI          3
#define T_UE_Identity_iMEI              4
#define T_UE_Identity_eSN               5
#define T_UE_Identity_iMSIDS41          6
#define T_UE_Identity_iMSIESN           7
#define T_UE_Identity_tMSIDS41          8
#define T_UE_Identity_extElem1          9

typedef struct EXTERN UE_Identity {
   int t;
   union {
      /* t = 1 */
      IMSI *iMSI;
      /* t = 2 */
      TMSILAI *tMSILAI;
      /* t = 3 */
      PTMSIRAI *pTMSIRAI;
      /* t = 4 */
      IMEI *iMEI;
      /* t = 5 */
      ESN *eSN;
      /* t = 6 */
      IMSIDS41 *iMSIDS41;
      /* t = 7 */
      IMSIESN *iMSIESN;
      /* t = 8 */
      TMSIDS41 *tMSIDS41;
      /* t = 9 */
      ASN1OpenType *extElem1;
   } u;
} UE_Identity;

EXTERN int asn1PE_UE_Identity (OSCTXT* pctxt, UE_Identity* pvalue);

EXTERN int asn1PD_UE_Identity (OSCTXT* pctxt, UE_Identity* pvalue);

EXTERN void asn1Print_UE_Identity
   (const char* name, UE_Identity* pvalue);

EXTERN void asn1Init_UE_Identity (UE_Identity* pvalue);

#ifdef __cplusplus
}
#endif

#endif
