/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 6.1.4, Date: 06-Jul-2012.
 */
#include "HNBAP-CommonDataTypes.h"
#include "rtxsrc/rtxCommon.h"

static const OSEnumItem Criticality_ENUMTAB[] = {
   { OSUTF8("ignore"), 1, 6, 2 },
   { OSUTF8("notify"), 2, 6, 0 },
   { OSUTF8("reject"), 0, 6, 1 }
} ;
#define Criticality_ENUMTABSIZE 3

const OSUTF8CHAR* Criticality_ToString (OSINT32 value)
{
   OSINT32 idx = value;

   if (idx >= 0 && idx < Criticality_ENUMTABSIZE) {
      return Criticality_ENUMTAB[Criticality_ENUMTAB[idx].transidx].name;
   }
   else
      return OSUTF8("_UNKNOWN_");
}

int Criticality_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, Criticality* pvalue)
{
   OSUINT32 valueLen = rtxUTF8LenBytes (value);
   OSINT32 idx = rtxLookupEnum (value, valueLen, Criticality_ENUMTAB, 
      Criticality_ENUMTABSIZE);

   if (idx >= 0) {
      *pvalue = (Criticality)Criticality_ENUMTAB[idx].value;
      return 0;
   }
   else {
      rtxErrAddStrParm (pctxt, (const char*)value);
      return LOG_RTERR (pctxt, RTERR_INVENUM);
   }
}

void asn1Init_PrivateIE_ID (PrivateIE_ID* pvalue)
{
   if (0 == pvalue) return;
   pvalue->t = 0;
   OSCRTLMEMSET (&pvalue->u, 0, sizeof(pvalue->u));
}

static const OSEnumItem TriggeringMessage_ENUMTAB[] = {
   { OSUTF8("initiating-message"), 0, 18, 0 },
   { OSUTF8("successful-outcome"), 1, 18, 1 },
   { OSUTF8("unsuccessful-outcome"), 2, 20, 2 }
} ;
#define TriggeringMessage_ENUMTABSIZE 3

const OSUTF8CHAR* TriggeringMessage_ToString (OSINT32 value)
{
   OSINT32 idx = value;

   if (idx >= 0 && idx < TriggeringMessage_ENUMTABSIZE) {
      return TriggeringMessage_ENUMTAB
         [TriggeringMessage_ENUMTAB[idx].transidx].name;
   }
   else
      return OSUTF8("_UNKNOWN_");
}

int TriggeringMessage_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, TriggeringMessage* pvalue)
{
   OSUINT32 valueLen = rtxUTF8LenBytes (value);
   OSINT32 idx = rtxLookupEnum (value, valueLen, TriggeringMessage_ENUMTAB, 
      TriggeringMessage_ENUMTABSIZE);

   if (idx >= 0) {
      *pvalue = (TriggeringMessage)TriggeringMessage_ENUMTAB[idx].value;
      return 0;
   }
   else {
      rtxErrAddStrParm (pctxt, (const char*)value);
      return LOG_RTERR (pctxt, RTERR_INVENUM);
   }
}

static const OSEnumItem Presence_ENUMTAB[] = {
   { OSUTF8("conditional"), 1, 11, 2 },
   { OSUTF8("mandatory"), 2, 9, 0 },
   { OSUTF8("optional"), 0, 8, 1 }
} ;
#define Presence_ENUMTABSIZE 3

const OSUTF8CHAR* Presence_ToString (OSINT32 value)
{
   OSINT32 idx = value;

   if (idx >= 0 && idx < Presence_ENUMTABSIZE) {
      return Presence_ENUMTAB[Presence_ENUMTAB[idx].transidx].name;
   }
   else
      return OSUTF8("_UNKNOWN_");
}

int Presence_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, Presence* pvalue)
{
   OSUINT32 valueLen = rtxUTF8LenBytes (value);
   OSINT32 idx = rtxLookupEnum (value, valueLen, Presence_ENUMTAB, 
      Presence_ENUMTABSIZE);

   if (idx >= 0) {
      *pvalue = (Presence)Presence_ENUMTAB[idx].value;
      return 0;
   }
   else {
      rtxErrAddStrParm (pctxt, (const char*)value);
      return LOG_RTERR (pctxt, RTERR_INVENUM);
   }
}

