/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 6.1.4, Date: 06-Jul-2012.
 */
#include "HNBAP-CommonDataTypes.h"
#include "rtxsrc/rtxCommon.h"

EXTERN int asn1PE_ProcedureCode (OSCTXT* pctxt, ProcedureCode value)
{
   int stat = 0;

   stat = pe_ConsUnsigned (pctxt, value, OSUINTCONST(0), OSUINTCONST(255));
   if (stat != 0) return LOG_RTERR (pctxt, stat);

   return (stat);
}

EXTERN int asn1PE_Criticality (OSCTXT* pctxt, Criticality value)
{
   int stat = 0;
   OSUINT32 ui;

   switch (value) {
      case reject: ui = 0; break;
      case ignore: ui = 1; break;
      case notify: ui = 2; break;
      default: rtxErrAddUIntParm (pctxt, value);
      return LOG_RTERR (pctxt, RTERR_INVENUM);
   }

   stat = pe_ConsUnsigned (pctxt, ui, 0, OSUINTCONST(2));
   if (stat != 0) return LOG_RTERR (pctxt, stat);

   return (stat);
}

EXTERN int asn1PE_ProtocolIE_ID (OSCTXT* pctxt, ProtocolIE_ID value)
{
   int stat = 0;

   stat = pe_ConsUnsigned (pctxt, value, OSUINTCONST(0), OSUINTCONST(65535));
   if (stat != 0) return LOG_RTERR (pctxt, stat);

   return (stat);
}

EXTERN int asn1PE_PrivateIE_ID (OSCTXT* pctxt, PrivateIE_ID* pvalue)
{
   int stat = 0;

   /* Encode choice index value */

   stat = pe_ConsUnsigned (pctxt, pvalue->t - 1, 0, 1);
   if (stat != 0) return LOG_RTERR (pctxt, stat);

   /* Encode root element data value */

   switch (pvalue->t)
   {
      /* local */
      case 1:
         stat = pe_ConsUnsigned (pctxt, pvalue->u.local, OSUINTCONST(0), OSUINTCONST(65535));
         if (stat != 0) return LOG_RTERR (pctxt, stat);

         break;

      /* global */
      case 2:
         stat = pe_ObjectIdentifier (pctxt, pvalue->u.global);
         if (stat != 0) return LOG_RTERR (pctxt, stat);
         break;

      default:
         return LOG_RTERR (pctxt, RTERR_INVOPT);
   }

   return (stat);
}

EXTERN int asn1PE_TriggeringMessage (OSCTXT* pctxt, TriggeringMessage value)
{
   int stat = 0;
   OSUINT32 ui;

   switch (value) {
      case initiating_message: ui = 0; break;
      case successful_outcome: ui = 1; break;
      case unsuccessful_outcome: ui = 2; break;
      default: rtxErrAddUIntParm (pctxt, value);
      return LOG_RTERR (pctxt, RTERR_INVENUM);
   }

   stat = pe_ConsUnsigned (pctxt, ui, 0, OSUINTCONST(2));
   if (stat != 0) return LOG_RTERR (pctxt, stat);

   return (stat);
}

EXTERN int asn1PE_Presence (OSCTXT* pctxt, Presence value)
{
   int stat = 0;
   OSUINT32 ui;

   switch (value) {
      case optional: ui = 0; break;
      case conditional: ui = 1; break;
      case mandatory: ui = 2; break;
      default: rtxErrAddUIntParm (pctxt, value);
      return LOG_RTERR (pctxt, RTERR_INVENUM);
   }

   stat = pe_ConsUnsigned (pctxt, ui, 0, OSUINTCONST(2));
   if (stat != 0) return LOG_RTERR (pctxt, stat);

   return (stat);
}

