/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 6.1.4, Date: 06-Jul-2012.
 */
#include "HNBAP-PDU-Descriptions.h"
#include "HNBAP-Constants.h"
#include "rtxsrc/rtxCommon.h"

EXTERN int asn1PE_HnbInitiatingMessage (OSCTXT* pctxt, HnbInitiatingMessage* pvalue)
{
   int stat = 0;

   /* encode procedureCode */

   stat = asn1PE_ProcedureCode (pctxt, pvalue->procedureCode);
   if (stat != 0) return LOG_RTERR (pctxt, stat);

   /* encode criticality */

   stat = asn1PE_Criticality (pctxt, pvalue->criticality);
   if (stat != 0) return LOG_RTERR (pctxt, stat);

   /* encode value */

   stat = pe_OpenType (pctxt, pvalue->value.numocts, pvalue->value.data);
   if (stat != 0) return LOG_RTERR (pctxt, stat);

   return (stat);
}

EXTERN int asn1PE_HnbSuccessfulOutcome (OSCTXT* pctxt, HnbSuccessfulOutcome* pvalue)
{
   int stat = 0;

   /* encode procedureCode */

   stat = asn1PE_ProcedureCode (pctxt, pvalue->procedureCode);
   if (stat != 0) return LOG_RTERR (pctxt, stat);

   /* encode criticality */

   stat = asn1PE_Criticality (pctxt, pvalue->criticality);
   if (stat != 0) return LOG_RTERR (pctxt, stat);

   /* encode value */

   stat = pe_OpenType (pctxt, pvalue->value.numocts, pvalue->value.data);
   if (stat != 0) return LOG_RTERR (pctxt, stat);

   return (stat);
}

EXTERN int asn1PE_HnbUnsuccessfulOutcome (OSCTXT* pctxt, HnbUnsuccessfulOutcome* pvalue)
{
   int stat = 0;

   /* encode procedureCode */

   stat = asn1PE_ProcedureCode (pctxt, pvalue->procedureCode);
   if (stat != 0) return LOG_RTERR (pctxt, stat);

   /* encode criticality */

   stat = asn1PE_Criticality (pctxt, pvalue->criticality);
   if (stat != 0) return LOG_RTERR (pctxt, stat);

   /* encode value */

   stat = pe_OpenType (pctxt, pvalue->value.numocts, pvalue->value.data);
   if (stat != 0) return LOG_RTERR (pctxt, stat);

   return (stat);
}

EXTERN int asn1PE_HnbHNBAP_PDU (OSCTXT* pctxt, HnbHNBAP_PDU* pvalue)
{
   int stat = 0;
   OSBOOL extbit = FALSE;

   /* extension bit */

   extbit = (OSBOOL)(pvalue->t > 3);

   stat = pe_bit (pctxt, extbit);
   if (stat != 0) return LOG_RTERR (pctxt, stat);

   if (!extbit) {

      /* Encode choice index value */

      stat = pe_ConsUnsigned (pctxt, pvalue->t - 1, 0, 2);
      if (stat != 0) return LOG_RTERR (pctxt, stat);

      /* Encode root element data value */

      switch (pvalue->t)
      {
         /* initiatingMessage */
         case 1:
            stat = asn1PE_HnbInitiatingMessage (pctxt, pvalue->u.initiatingMessage);
            if (stat != 0) return LOG_RTERR (pctxt, stat);
            break;

         /* successfulOutcome */
         case 2:
            stat = asn1PE_HnbSuccessfulOutcome (pctxt, pvalue->u.successfulOutcome);
            if (stat != 0) return LOG_RTERR (pctxt, stat);
            break;

         /* unsuccessfulOutcome */
         case 3:
            stat = asn1PE_HnbUnsuccessfulOutcome (pctxt, pvalue->u.unsuccessfulOutcome);
            if (stat != 0) return LOG_RTERR (pctxt, stat);
            break;

         default:
            return LOG_RTERR (pctxt, RTERR_INVOPT);
      }
   }
   else {
      /* Encode extension choice index value */

      stat = pe_SmallNonNegWholeNumber (pctxt, pvalue->t - 4);
      if (stat != 0) return LOG_RTERR (pctxt, stat);

      /* Encode extension element data value */

      stat = pe_OpenType (pctxt, pvalue->u.extElem1->numocts, pvalue->u.extElem1->data);
      if (stat != 0) return LOG_RTERR (pctxt, stat);
   }

   return (stat);
}

