/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 6.1.4, Date: 06-Jul-2012.
 */
#ifndef HNBAP_PDU_DESCRIPTIONS_H
#define HNBAP_PDU_DESCRIPTIONS_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdio.h>
#include <stdlib.h>
#include "rtkey.h"
#include "rtpersrc/asn1per.h"
#include "HNBAP-CommonDataTypes.h"
#include "HNBAP-PDU-Contents.h"

/**
 * Header file for ASN.1 module HNBAP-PDU-Descriptions
 */
/**************************************************************/
/*                                                            */
/*  InitiatingMessage                                         */
/*                                                            */
/**************************************************************/

typedef struct EXTERN HnbInitiatingMessage {
   ProcedureCode procedureCode;
   Criticality criticality;
   ASN1OpenType value;
} HnbInitiatingMessage;

EXTERN int asn1PE_HnbInitiatingMessage (OSCTXT* pctxt, HnbInitiatingMessage* pvalue);

EXTERN int asn1PD_HnbInitiatingMessage (OSCTXT* pctxt, HnbInitiatingMessage* pvalue);

EXTERN void asn1Print_HnbInitiatingMessage
   (const char* name, HnbInitiatingMessage* pvalue);

EXTERN void asn1Init_HnbInitiatingMessage (HnbInitiatingMessage* pvalue);

/**************************************************************/
/*                                                            */
/*  SuccessfulOutcome                                         */
/*                                                            */
/**************************************************************/

typedef struct EXTERN HnbSuccessfulOutcome {
   ProcedureCode procedureCode;
   Criticality criticality;
   ASN1OpenType value;
} HnbSuccessfulOutcome;

EXTERN int asn1PE_HnbSuccessfulOutcome (OSCTXT* pctxt, HnbSuccessfulOutcome* pvalue);

EXTERN int asn1PD_HnbSuccessfulOutcome (OSCTXT* pctxt, HnbSuccessfulOutcome* pvalue);

EXTERN void asn1Print_HnbSuccessfulOutcome
   (const char* name, HnbSuccessfulOutcome* pvalue);

EXTERN void asn1Init_HnbSuccessfulOutcome (HnbSuccessfulOutcome* pvalue);

/**************************************************************/
/*                                                            */
/*  UnsuccessfulOutcome                                       */
/*                                                            */
/**************************************************************/

typedef struct EXTERN HnbUnsuccessfulOutcome {
   ProcedureCode procedureCode;
   Criticality criticality;
   ASN1OpenType value;
} HnbUnsuccessfulOutcome;

EXTERN int asn1PE_HnbUnsuccessfulOutcome (OSCTXT* pctxt, HnbUnsuccessfulOutcome* pvalue);

EXTERN int asn1PD_HnbUnsuccessfulOutcome (OSCTXT* pctxt, HnbUnsuccessfulOutcome* pvalue);

EXTERN void asn1Print_HnbUnsuccessfulOutcome
   (const char* name, HnbUnsuccessfulOutcome* pvalue);

EXTERN void asn1Init_HnbUnsuccessfulOutcome (HnbUnsuccessfulOutcome* pvalue);

/**************************************************************/
/*                                                            */
/*  HNBAP_PDU                                                 */
/*                                                            */
/**************************************************************/

/* Choice tag constants */

#define T_HnbHNBAP_PDU_initiatingMessage 1
#define T_HnbHNBAP_PDU_successfulOutcome 2
#define T_HnbHNBAP_PDU_unsuccessfulOutcome 3
#define T_HnbHNBAP_PDU_extElem1         4

typedef struct EXTERN HnbHNBAP_PDU {
   int t;
   union {
      /* t = 1 */
      HnbInitiatingMessage *initiatingMessage;
      /* t = 2 */
      HnbSuccessfulOutcome *successfulOutcome;
      /* t = 3 */
      HnbUnsuccessfulOutcome *unsuccessfulOutcome;
      /* t = 4 */
      ASN1OpenType *extElem1;
   } u;
} HnbHNBAP_PDU;

EXTERN int asn1PE_HnbHNBAP_PDU (OSCTXT* pctxt, HnbHNBAP_PDU* pvalue);

EXTERN int asn1PD_HnbHNBAP_PDU (OSCTXT* pctxt, HnbHNBAP_PDU* pvalue);

EXTERN void asn1Print_HnbHNBAP_PDU
   (const char* name, HnbHNBAP_PDU* pvalue);

EXTERN void asn1Init_HnbHNBAP_PDU (HnbHNBAP_PDU* pvalue);

#ifdef __cplusplus
}
#endif

#endif
