/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 6.1.4, Date: 06-Jul-2012.
 */
#include "HNBAP-IEs.h"
#include "HNBAP-Constants.h"
#include "rtsrc/rtPrint.h"
#include "rtxsrc/rtxCommon.h"

void asn1Print_Access_stratum_release_indicator
   (const char* name, Access_stratum_release_indicator* pvalue)
{
   rtPrintIndent ();
   printf ("%s = ", name);
   switch (*pvalue) {
      case 0: printf ("r99\n"); break;
      case 1: printf ("rel-4\n"); break;
      case 2: printf ("rel-5\n"); break;
      case 3: printf ("rel-6\n"); break;
      case 4: printf ("rel-7\n"); break;
      case 5: printf ("rel-8\n"); break;
      default: printf ("%u\n", *pvalue);
   }
}

void asn1Print_BackoffTimer
   (const char* name, BackoffTimer* pvalue)
{
   rtPrintIndent ();
   rtPrintUnsigned (name, *pvalue);
}

void asn1Print_CauseRadioNetwork
   (const char* name, CauseRadioNetwork* pvalue)
{
   rtPrintIndent ();
   printf ("%s = ", name);
   switch (*pvalue) {
      case 0: printf ("overload\n"); break;
      case 1: printf ("unauthorised-Location\n"); break;
      case 2: printf ("unauthorised-HNB\n"); break;
      case 3: printf ("hNB-parameter-mismatch\n"); break;
      case 4: printf ("invalid-UE-identity\n"); break;
      case 5: printf ("uE-not-allowed-on-this-HNB\n"); break;
      case 6: printf ("uE-unauthorised\n"); break;
      case 7: printf ("connection-with-UE-lost\n"); break;
      case 8: printf ("ue-RRC-telease\n"); break;
      case 9: printf ("hNB-not-registered\n"); break;
      case 10: printf ("unspecified\n"); break;
      case 11: printf ("normal\n"); break;
      case 12: printf ("uE-relocated\n"); break;
      case 13: printf ("ue-registered-in-another-HNB\n"); break;
      default: printf ("%u\n", *pvalue);
   }
}

void asn1Print_CauseTransport
   (const char* name, CauseTransport* pvalue)
{
   rtPrintIndent ();
   printf ("%s = ", name);
   switch (*pvalue) {
      case 0: printf ("transport-resource-unavailable\n"); break;
      case 1: printf ("unspecified\n"); break;
      default: printf ("%u\n", *pvalue);
   }
}

void asn1Print_CauseProtocol
   (const char* name, CauseProtocol* pvalue)
{
   rtPrintIndent ();
   printf ("%s = ", name);
   switch (*pvalue) {
      case 0: printf ("transfer-syntax-error\n"); break;
      case 1: printf ("abstract-syntax-error-reject\n"); break;
      case 2: printf ("abstract-syntax-error-ignore-and-notify\n"); break;
      case 3: printf ("message-not-compatible-with-receiver-state\n"); break;
      case 4: printf ("semantic-error\n"); break;
      case 5: printf ("unspecified\n"); break;
      case 6: printf ("abstract-syntax-error-falsely-constructed-message\n"); break;
      default: printf ("%u\n", *pvalue);
   }
}

void asn1Print_CauseMisc
   (const char* name, CauseMisc* pvalue)
{
   rtPrintIndent ();
   printf ("%s = ", name);
   switch (*pvalue) {
      case 0: printf ("processing-overload\n"); break;
      case 1: printf ("hardware-failure\n"); break;
      case 2: printf ("o-and-m-intervention\n"); break;
      case 3: printf ("unspecified\n"); break;
      default: printf ("%u\n", *pvalue);
   }
}

void asn1Print_CellIdentity
   (const char* name, CellIdentity* pvalue)
{
   rtPrintIndent ();
   rtPrintBitStrBraceText (name, pvalue->numbits, pvalue->data);
}

void asn1Print_Context_ID
   (const char* name, Context_ID* pvalue)
{
   rtPrintIndent ();
   rtPrintBitStrBraceText (name, pvalue->numbits, pvalue->data);
}

void asn1Print_CSG_ID
   (const char* name, CSG_ID* pvalue)
{
   rtPrintIndent ();
   rtPrintBitStrBraceText (name, pvalue->numbits, pvalue->data);
}

void asn1Print_CSG_Indicator
   (const char* name, CSG_Indicator* pvalue)
{
   rtPrintIndent ();
   printf ("%s = ", name);
   switch (*pvalue) {
      case 0: printf ("csg-capable\n"); break;
      case 1: printf ("not-csg-capable\n"); break;
      default: printf ("%u\n", *pvalue);
   }
}

void asn1Print_CI
   (const char* name, CI* pvalue)
{
   rtPrintIndent ();
   rtPrintHexStr (name, pvalue->numocts, pvalue->data);
}

void asn1Print_CN_DomainIndicator
   (const char* name, CN_DomainIndicator* pvalue)
{
   rtPrintIndent ();
   printf ("%s = ", name);
   switch (*pvalue) {
      case 0: printf ("cs-domain\n"); break;
      case 1: printf ("ps-domain\n"); break;
      default: printf ("???\n");
   }
}

void asn1Print_ESN
   (const char* name, ESN* pvalue)
{
   rtPrintIndent ();
   rtPrintBitStrBraceText (name, pvalue->numbits, pvalue->data);
}

void asn1Print_HNB_Identity_Info
   (const char* name, HNB_Identity_Info* pvalue)
{
   rtPrintIndent ();
   rtPrintHexStr (name, pvalue->numocts, pvalue->data);
}

void asn1Print_IMEI
   (const char* name, IMEI* pvalue)
{
   rtPrintIndent ();
   rtPrintBitStrBraceText (name, pvalue->numbits, pvalue->data);
}

void asn1Print_IMSI
   (const char* name, IMSI* pvalue)
{
   rtPrintIndent ();
   rtPrintHexStr (name, pvalue->numocts, pvalue->data);
}

void asn1Print_IMSIDS41
   (const char* name, IMSIDS41* pvalue)
{
   rtPrintIndent ();
   rtPrintHexStr (name, pvalue->numocts, pvalue->data);
}

void asn1Print_Ipv4Address
   (const char* name, Ipv4Address* pvalue)
{
   rtPrintIndent ();
   rtPrintHexStr (name, pvalue->numocts, pvalue->data);
}

void asn1Print_Ipv6Address
   (const char* name, Ipv6Address* pvalue)
{
   rtPrintIndent ();
   rtPrintHexStr (name, pvalue->numocts, pvalue->data);
}

void asn1Print_LAC
   (const char* name, LAC* pvalue)
{
   rtPrintIndent ();
   rtPrintHexStr (name, pvalue->numocts, pvalue->data);
}

void asn1Print_PLMNidentity
   (const char* name, PLMNidentity* pvalue)
{
   rtPrintIndent ();
   rtPrintHexStr (name, pvalue->numocts, pvalue->data);
}

void asn1Print_PTMSI
   (const char* name, PTMSI* pvalue)
{
   rtPrintIndent ();
   rtPrintBitStrBraceText (name, pvalue->numbits, pvalue->data);
}

void asn1Print_RAC
   (const char* name, RAC* pvalue)
{
   rtPrintIndent ();
   rtPrintHexStr (name, pvalue->numocts, pvalue->data);
}

void asn1Print_Registration_Cause
   (const char* name, Registration_Cause* pvalue)
{
   rtPrintIndent ();
   printf ("%s = ", name);
   switch (*pvalue) {
      case 0: printf ("emergency-call\n"); break;
      case 1: printf ("normal\n"); break;
      default: printf ("%u\n", *pvalue);
   }
}

void asn1Print_RNC_ID
   (const char* name, RNC_ID* pvalue)
{
   rtPrintIndent ();
   rtPrintUnsigned (name, *pvalue);
}

void asn1Print_SAC
   (const char* name, SAC* pvalue)
{
   rtPrintIndent ();
   rtPrintHexStr (name, pvalue->numocts, pvalue->data);
}

void asn1Print_TMSIDS41
   (const char* name, TMSIDS41* pvalue)
{
   rtPrintIndent ();
   rtPrintHexStr (name, pvalue->numocts, pvalue->data);
}

void asn1Print_TypeOfError
   (const char* name, TypeOfError* pvalue)
{
   rtPrintIndent ();
   printf ("%s = ", name);
   switch (*pvalue) {
      case 0: printf ("not-understood\n"); break;
      case 1: printf ("missing\n"); break;
      default: printf ("%u\n", *pvalue);
   }
}

void asn1Print_AltitudeAndDirection_directionOfAltitude
   (const char* name, AltitudeAndDirection_directionOfAltitude* pvalue)
{
   rtPrintIndent ();
   printf ("%s = ", name);
   switch (*pvalue) {
      case 0: printf ("height\n"); break;
      case 1: printf ("depth\n"); break;
      default: printf ("???\n");
   }
}

void asn1Print_GeographicalCoordinates_latitudeSign
   (const char* name, GeographicalCoordinates_latitudeSign* pvalue)
{
   rtPrintIndent ();
   printf ("%s = ", name);
   switch (*pvalue) {
      case 0: printf ("north\n"); break;
      case 1: printf ("south\n"); break;
      default: printf ("???\n");
   }
}

void asn1Print_TMSILAI_tMSI
   (const char* name, TMSILAI_tMSI* pvalue)
{
   rtPrintIndent ();
   rtPrintBitStrBraceText (name, pvalue->numbits, pvalue->data);
}

void asn1Print_AltitudeAndDirection
   (const char* name, AltitudeAndDirection* pvalue)
{
   rtPrintOpenBrace (name);

   asn1Print_AltitudeAndDirection_directionOfAltitude ("directionOfAltitude",
      &pvalue->directionOfAltitude);

   rtPrintIndent ();
   rtPrintUnsigned ("altitude", pvalue->altitude);

   rtPrintOpenTypeExtBraceText ("extElem1", &pvalue->extElem1);

   rtPrintCloseBrace ();
}

void asn1Print_Cause
   (const char* name, Cause* pvalue)
{
   rtPrintOpenBrace (name);

   switch (pvalue->t) {
      case 1: {
         asn1Print_CauseRadioNetwork ("radioNetwork",
            &pvalue->u.radioNetwork);
         break;
      }
      case 2: {
         asn1Print_CauseTransport ("transport",
            &pvalue->u.transport);
         break;
      }
      case 3: {
         asn1Print_CauseProtocol ("protocol",
            &pvalue->u.protocol);
         break;
      }
      case 4: {
         asn1Print_CauseMisc ("misc",
            &pvalue->u.misc);
         break;
      }
      case 5: {
         rtPrintIndent ();
         rtPrintHexStr ("extElem1",
            pvalue->u.extElem1->numocts,
            pvalue->u.extElem1->data);
         break;
      }
      default:;
   }

   rtPrintCloseBrace ();
}

void asn1Print_CriticalityDiagnostics_IE_List_element
   (const char* name, CriticalityDiagnostics_IE_List_element* pvalue)
{
   rtPrintOpenBrace (name);

   asn1Print_Criticality ("iECriticality",
      &pvalue->iECriticality);

   asn1Print_ProtocolIE_ID ("iE_ID",
      &pvalue->iE_ID);

   asn1Print_TypeOfError ("typeOfError",
      &pvalue->typeOfError);

   if (pvalue->m.iE_ExtensionsPresent) {
      asn1Print_ProtocolExtensionContainer ("iE_Extensions",
         &pvalue->iE_Extensions);
   }

   rtPrintOpenTypeExtBraceText ("extElem1", &pvalue->extElem1);

   rtPrintCloseBrace ();
}

void asn1Print_CriticalityDiagnostics_IE_List
   (const char* name, CriticalityDiagnostics_IE_List* pvalue)
{
   CriticalityDiagnostics_IE_List_element* pdata0;
   OSRTDListNode* pnode;
   char namebuf[512];
   OSUINT32 xx1;

   pnode = pvalue->head;
   for (xx1 = 0; xx1 < pvalue->count; xx1++) {
      pdata0 = (CriticalityDiagnostics_IE_List_element*) pnode->data;
      os_snprintf (namebuf, 512, "%s[%d]", name, xx1);
      asn1Print_CriticalityDiagnostics_IE_List_element (namebuf,
         pdata0);
      pnode = pnode->next;
   }
}

void asn1Print_CriticalityDiagnostics
   (const char* name, CriticalityDiagnostics* pvalue)
{
   rtPrintOpenBrace (name);

   if (pvalue->m.procedureCodePresent) {
      asn1Print_ProcedureCode ("procedureCode",
         &pvalue->procedureCode);
   }

   if (pvalue->m.triggeringMessagePresent) {
      asn1Print_TriggeringMessage ("triggeringMessage",
         &pvalue->triggeringMessage);
   }

   if (pvalue->m.procedureCriticalityPresent) {
      asn1Print_Criticality ("procedureCriticality",
         &pvalue->procedureCriticality);
   }

   if (pvalue->m.iEsCriticalityDiagnosticsPresent) {
      asn1Print_CriticalityDiagnostics_IE_List ("iEsCriticalityDiagnostics",
         &pvalue->iEsCriticalityDiagnostics);
   }

   if (pvalue->m.iE_ExtensionsPresent) {
      asn1Print_ProtocolExtensionContainer ("iE_Extensions",
         &pvalue->iE_Extensions);
   }

   rtPrintOpenTypeExtBraceText ("extElem1", &pvalue->extElem1);

   rtPrintCloseBrace ();
}

void asn1Print_CGI
   (const char* name, CGI* pvalue)
{
   rtPrintOpenBrace (name);

   asn1Print_PLMNidentity ("pLMNidentity",
      &pvalue->pLMNidentity);

   asn1Print_LAC ("lAC",
      &pvalue->lAC);

   asn1Print_CI ("cI",
      &pvalue->cI);

   if (pvalue->m.iE_ExtensionsPresent) {
      asn1Print_ProtocolExtensionContainer ("iE_Extensions",
         &pvalue->iE_Extensions);
   }

   rtPrintCloseBrace ();
}

void asn1Print_GeographicalCoordinates
   (const char* name, GeographicalCoordinates* pvalue)
{
   rtPrintOpenBrace (name);

   asn1Print_GeographicalCoordinates_latitudeSign ("latitudeSign",
      &pvalue->latitudeSign);

   rtPrintIndent ();
   rtPrintUnsigned ("latitude", pvalue->latitude);

   rtPrintIndent ();
   rtPrintInteger ("longitude", pvalue->longitude);

   if (pvalue->m.iE_ExtensionsPresent) {
      asn1Print_ProtocolExtensionContainer ("iE_Extensions",
         &pvalue->iE_Extensions);
   }

   rtPrintOpenTypeExtBraceText ("extElem1", &pvalue->extElem1);

   rtPrintCloseBrace ();
}

void asn1Print_GeographicalLocation
   (const char* name, GeographicalLocation* pvalue)
{
   rtPrintOpenBrace (name);

   asn1Print_GeographicalCoordinates ("geographicalCoordinates",
      &pvalue->geographicalCoordinates);

   asn1Print_AltitudeAndDirection ("altitudeAndDirection",
      &pvalue->altitudeAndDirection);

   if (pvalue->m.iE_ExtensionsPresent) {
      asn1Print_ProtocolExtensionContainer ("iE_Extensions",
         &pvalue->iE_Extensions);
   }

   rtPrintOpenTypeExtBraceText ("extElem1", &pvalue->extElem1);

   rtPrintCloseBrace ();
}

void asn1Print_UTRANCellID
   (const char* name, UTRANCellID* pvalue)
{
   rtPrintOpenBrace (name);

   asn1Print_LAC ("lAC",
      &pvalue->lAC);

   asn1Print_RAC ("rAC",
      &pvalue->rAC);

   asn1Print_PLMNidentity ("pLMNidentity",
      &pvalue->pLMNidentity);

   asn1Print_CellIdentity ("uTRANcellID",
      &pvalue->uTRANcellID);

   if (pvalue->m.iE_ExtensionsPresent) {
      asn1Print_ProtocolExtensionContainer ("iE_Extensions",
         &pvalue->iE_Extensions);
   }

   rtPrintCloseBrace ();
}

void asn1Print_MacroCellID
   (const char* name, MacroCellID* pvalue)
{
   rtPrintOpenBrace (name);

   switch (pvalue->t) {
      case 1: {
         asn1Print_UTRANCellID ("uTRANCellID",
            pvalue->u.uTRANCellID);
         break;
      }
      case 2: {
         asn1Print_CGI ("gERANCellID",
            pvalue->u.gERANCellID);
         break;
      }
      case 3: {
         rtPrintIndent ();
         rtPrintHexStr ("extElem1",
            pvalue->u.extElem1->numocts,
            pvalue->u.extElem1->data);
         break;
      }
      default:;
   }

   rtPrintCloseBrace ();
}

void asn1Print_MacroCoverageInformation
   (const char* name, MacroCoverageInformation* pvalue)
{
   rtPrintOpenBrace (name);

   asn1Print_MacroCellID ("cellIdentity",
      &pvalue->cellIdentity);

   if (pvalue->m.iE_ExtensionsPresent) {
      asn1Print_ProtocolExtensionContainer ("iE_Extensions",
         &pvalue->iE_Extensions);
   }

   rtPrintOpenTypeExtBraceText ("extElem1", &pvalue->extElem1);

   rtPrintCloseBrace ();
}

void asn1Print_HNB_Location_Information
   (const char* name, HNB_Location_Information* pvalue)
{
   rtPrintOpenBrace (name);

   if (pvalue->m.macroCoverageInfoPresent) {
      asn1Print_MacroCoverageInformation ("macroCoverageInfo",
         &pvalue->macroCoverageInfo);
   }

   if (pvalue->m.geographicalCoordinatesPresent) {
      asn1Print_GeographicalLocation ("geographicalCoordinates",
         &pvalue->geographicalCoordinates);
   }

   if (pvalue->m.iE_ExtensionsPresent) {
      asn1Print_ProtocolExtensionContainer ("iE_Extensions",
         &pvalue->iE_Extensions);
   }

   rtPrintOpenTypeExtBraceText ("extElem1", &pvalue->extElem1);

   rtPrintCloseBrace ();
}

void asn1Print_HNB_Identity
   (const char* name, HNB_Identity* pvalue)
{
   rtPrintOpenBrace (name);

   asn1Print_HNB_Identity_Info ("hNB_Identity_Info",
      &pvalue->hNB_Identity_Info);

   if (pvalue->m.iE_ExtensionsPresent) {
      asn1Print_ProtocolExtensionContainer ("iE_Extensions",
         &pvalue->iE_Extensions);
   }

   rtPrintOpenTypeExtBraceText ("extElem1", &pvalue->extElem1);

   rtPrintCloseBrace ();
}

void asn1Print_IMSIESN
   (const char* name, IMSIESN* pvalue)
{
   rtPrintOpenBrace (name);

   asn1Print_IMSIDS41 ("iMSIDS41",
      &pvalue->iMSIDS41);

   asn1Print_ESN ("eSN",
      &pvalue->eSN);

   rtPrintCloseBrace ();
}

void asn1Print_IP_Address_ipaddress
   (const char* name, IP_Address_ipaddress* pvalue)
{
   rtPrintOpenBrace (name);

   switch (pvalue->t) {
      case 1: {
         asn1Print_Ipv4Address ("ipv4info",
            pvalue->u.ipv4info);
         break;
      }
      case 2: {
         asn1Print_Ipv6Address ("ipv6info",
            pvalue->u.ipv6info);
         break;
      }
      case 3: {
         rtPrintIndent ();
         rtPrintHexStr ("extElem1",
            pvalue->u.extElem1->numocts,
            pvalue->u.extElem1->data);
         break;
      }
      default:;
   }

   rtPrintCloseBrace ();
}

void asn1Print_IP_Address
   (const char* name, IP_Address* pvalue)
{
   rtPrintOpenBrace (name);

   asn1Print_IP_Address_ipaddress ("ipaddress",
      &pvalue->ipaddress);

   if (pvalue->m.iE_ExtensionsPresent) {
      asn1Print_ProtocolExtensionContainer ("iE_Extensions",
         &pvalue->iE_Extensions);
   }

   rtPrintOpenTypeExtBraceText ("extElem1", &pvalue->extElem1);

   rtPrintCloseBrace ();
}

void asn1Print_LAI
   (const char* name, LAI* pvalue)
{
   rtPrintOpenBrace (name);

   asn1Print_PLMNidentity ("pLMNID",
      &pvalue->pLMNID);

   asn1Print_LAC ("lAC",
      &pvalue->lAC);

   rtPrintOpenTypeExtBraceText ("extElem1", &pvalue->extElem1);

   rtPrintCloseBrace ();
}

void asn1Print_RAI
   (const char* name, RAI* pvalue)
{
   rtPrintOpenBrace (name);

   asn1Print_LAI ("lAI",
      &pvalue->lAI);

   asn1Print_RAC ("rAC",
      &pvalue->rAC);

   rtPrintOpenTypeExtBraceText ("extElem1", &pvalue->extElem1);

   rtPrintCloseBrace ();
}

void asn1Print_PTMSIRAI
   (const char* name, PTMSIRAI* pvalue)
{
   rtPrintOpenBrace (name);

   asn1Print_PTMSI ("pTMSI",
      &pvalue->pTMSI);

   asn1Print_RAI ("rAI",
      &pvalue->rAI);

   rtPrintOpenTypeExtBraceText ("extElem1", &pvalue->extElem1);

   rtPrintCloseBrace ();
}

void asn1Print_TMSILAI
   (const char* name, TMSILAI* pvalue)
{
   rtPrintOpenBrace (name);

   asn1Print_TMSILAI_tMSI ("tMSI",
      &pvalue->tMSI);

   asn1Print_LAI ("lAI",
      &pvalue->lAI);

   rtPrintCloseBrace ();
}

void asn1Print_UE_Capabilities
   (const char* name, UE_Capabilities* pvalue)
{
   rtPrintOpenBrace (name);

   asn1Print_Access_stratum_release_indicator ("access_stratum_release_indicator",
      &pvalue->access_stratum_release_indicator);

   asn1Print_CSG_Indicator ("csg_indicator",
      &pvalue->csg_indicator);

   if (pvalue->m.iE_ExtensionsPresent) {
      asn1Print_ProtocolExtensionContainer ("iE_Extensions",
         &pvalue->iE_Extensions);
   }

   rtPrintOpenTypeExtBraceText ("extElem1", &pvalue->extElem1);

   rtPrintCloseBrace ();
}

void asn1Print_UE_Identity
   (const char* name, UE_Identity* pvalue)
{
   rtPrintOpenBrace (name);

   switch (pvalue->t) {
      case 1: {
         asn1Print_IMSI ("iMSI",
            pvalue->u.iMSI);
         break;
      }
      case 2: {
         asn1Print_TMSILAI ("tMSILAI",
            pvalue->u.tMSILAI);
         break;
      }
      case 3: {
         asn1Print_PTMSIRAI ("pTMSIRAI",
            pvalue->u.pTMSIRAI);
         break;
      }
      case 4: {
         asn1Print_IMEI ("iMEI",
            pvalue->u.iMEI);
         break;
      }
      case 5: {
         asn1Print_ESN ("eSN",
            pvalue->u.eSN);
         break;
      }
      case 6: {
         asn1Print_IMSIDS41 ("iMSIDS41",
            pvalue->u.iMSIDS41);
         break;
      }
      case 7: {
         asn1Print_IMSIESN ("iMSIESN",
            pvalue->u.iMSIESN);
         break;
      }
      case 8: {
         asn1Print_TMSIDS41 ("tMSIDS41",
            pvalue->u.tMSIDS41);
         break;
      }
      case 9: {
         rtPrintIndent ();
         rtPrintHexStr ("extElem1",
            pvalue->u.extElem1->numocts,
            pvalue->u.extElem1->data);
         break;
      }
      default:;
   }

   rtPrintCloseBrace ();
}

