/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 6.1.4, Date: 06-Jul-2012.
 */
#ifndef HNBAP_PDU_CONTENTS_H
#define HNBAP_PDU_CONTENTS_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdio.h>
#include <stdlib.h>
#include "rtkey.h"
#include "rtpersrc/asn1per.h"
#include "HNBAP-IEs.h"
#include "HNBAP-Containers.h"

/**
 * Header file for ASN.1 module HNBAP-PDU-Contents
 */
/**************************************************************/
/*                                                            */
/*  HNBRegisterRequest                                        */
/*                                                            */
/**************************************************************/

typedef struct EXTERN HnbHNBRegisterRequest {
   struct {
      unsigned protocolExtensionsPresent : 1;
   } m;
   ProtocolIE_Container protocolIEs;
   ProtocolExtensionContainer protocolExtensions;
   OSRTDList extElem1;
} HnbHNBRegisterRequest;

EXTERN int asn1PE_HnbHNBRegisterRequest (OSCTXT* pctxt, HnbHNBRegisterRequest* pvalue);

EXTERN int asn1PD_HnbHNBRegisterRequest (OSCTXT* pctxt, HnbHNBRegisterRequest* pvalue);

EXTERN void asn1Print_HnbHNBRegisterRequest
   (const char* name, HnbHNBRegisterRequest* pvalue);

EXTERN void asn1Init_HnbHNBRegisterRequest (HnbHNBRegisterRequest* pvalue);

/**************************************************************/
/*                                                            */
/*  HNBRegisterAccept                                         */
/*                                                            */
/**************************************************************/

typedef struct EXTERN HnbHNBRegisterAccept {
   struct {
      unsigned protocolExtensionsPresent : 1;
   } m;
   ProtocolIE_Container protocolIEs;
   ProtocolExtensionContainer protocolExtensions;
   OSRTDList extElem1;
} HnbHNBRegisterAccept;

EXTERN int asn1PE_HnbHNBRegisterAccept (OSCTXT* pctxt, HnbHNBRegisterAccept* pvalue);

EXTERN int asn1PD_HnbHNBRegisterAccept (OSCTXT* pctxt, HnbHNBRegisterAccept* pvalue);

EXTERN void asn1Print_HnbHNBRegisterAccept
   (const char* name, HnbHNBRegisterAccept* pvalue);

EXTERN void asn1Init_HnbHNBRegisterAccept (HnbHNBRegisterAccept* pvalue);

/**************************************************************/
/*                                                            */
/*  HNBRegisterReject                                         */
/*                                                            */
/**************************************************************/

typedef struct EXTERN HnbHNBRegisterReject {
   struct {
      unsigned protocolExtensionsPresent : 1;
   } m;
   ProtocolIE_Container protocolIEs;
   ProtocolExtensionContainer protocolExtensions;
   OSRTDList extElem1;
} HnbHNBRegisterReject;

EXTERN int asn1PE_HnbHNBRegisterReject (OSCTXT* pctxt, HnbHNBRegisterReject* pvalue);

EXTERN int asn1PD_HnbHNBRegisterReject (OSCTXT* pctxt, HnbHNBRegisterReject* pvalue);

EXTERN void asn1Print_HnbHNBRegisterReject
   (const char* name, HnbHNBRegisterReject* pvalue);

EXTERN void asn1Init_HnbHNBRegisterReject (HnbHNBRegisterReject* pvalue);

/**************************************************************/
/*                                                            */
/*  HNBDe_Register                                            */
/*                                                            */
/**************************************************************/

typedef struct EXTERN HnbHNBDe_Register {
   struct {
      unsigned protocolExtensionsPresent : 1;
   } m;
   ProtocolIE_Container protocolIEs;
   ProtocolExtensionContainer protocolExtensions;
   OSRTDList extElem1;
} HnbHNBDe_Register;

EXTERN int asn1PE_HnbHNBDe_Register (OSCTXT* pctxt, HnbHNBDe_Register* pvalue);

EXTERN int asn1PD_HnbHNBDe_Register (OSCTXT* pctxt, HnbHNBDe_Register* pvalue);

EXTERN void asn1Print_HnbHNBDe_Register
   (const char* name, HnbHNBDe_Register* pvalue);

EXTERN void asn1Init_HnbHNBDe_Register (HnbHNBDe_Register* pvalue);

/**************************************************************/
/*                                                            */
/*  UERegisterRequest                                         */
/*                                                            */
/**************************************************************/

typedef struct EXTERN HnbUERegisterRequest {
   struct {
      unsigned protocolExtensionsPresent : 1;
   } m;
   ProtocolIE_Container protocolIEs;
   ProtocolExtensionContainer protocolExtensions;
   OSRTDList extElem1;
} HnbUERegisterRequest;

EXTERN int asn1PE_HnbUERegisterRequest (OSCTXT* pctxt, HnbUERegisterRequest* pvalue);

EXTERN int asn1PD_HnbUERegisterRequest (OSCTXT* pctxt, HnbUERegisterRequest* pvalue);

EXTERN void asn1Print_HnbUERegisterRequest
   (const char* name, HnbUERegisterRequest* pvalue);

EXTERN void asn1Init_HnbUERegisterRequest (HnbUERegisterRequest* pvalue);

/**************************************************************/
/*                                                            */
/*  UERegisterAccept                                          */
/*                                                            */
/**************************************************************/

typedef struct EXTERN HnbUERegisterAccept {
   struct {
      unsigned protocolExtensionsPresent : 1;
   } m;
   ProtocolIE_Container protocolIEs;
   ProtocolExtensionContainer protocolExtensions;
   OSRTDList extElem1;
} HnbUERegisterAccept;

EXTERN int asn1PE_HnbUERegisterAccept (OSCTXT* pctxt, HnbUERegisterAccept* pvalue);

EXTERN int asn1PD_HnbUERegisterAccept (OSCTXT* pctxt, HnbUERegisterAccept* pvalue);

EXTERN void asn1Print_HnbUERegisterAccept
   (const char* name, HnbUERegisterAccept* pvalue);

EXTERN void asn1Init_HnbUERegisterAccept (HnbUERegisterAccept* pvalue);

/**************************************************************/
/*                                                            */
/*  UERegisterReject                                          */
/*                                                            */
/**************************************************************/

typedef struct EXTERN HnbUERegisterReject {
   struct {
      unsigned protocolExtensionsPresent : 1;
   } m;
   ProtocolIE_Container protocolIEs;
   ProtocolExtensionContainer protocolExtensions;
   OSRTDList extElem1;
} HnbUERegisterReject;

EXTERN int asn1PE_HnbUERegisterReject (OSCTXT* pctxt, HnbUERegisterReject* pvalue);

EXTERN int asn1PD_HnbUERegisterReject (OSCTXT* pctxt, HnbUERegisterReject* pvalue);

EXTERN void asn1Print_HnbUERegisterReject
   (const char* name, HnbUERegisterReject* pvalue);

EXTERN void asn1Init_HnbUERegisterReject (HnbUERegisterReject* pvalue);

/**************************************************************/
/*                                                            */
/*  UEDe_Register                                             */
/*                                                            */
/**************************************************************/

typedef struct EXTERN HnbUEDe_Register {
   struct {
      unsigned protocolExtensionsPresent : 1;
   } m;
   ProtocolIE_Container protocolIEs;
   ProtocolExtensionContainer protocolExtensions;
   OSRTDList extElem1;
} HnbUEDe_Register;

EXTERN int asn1PE_HnbUEDe_Register (OSCTXT* pctxt, HnbUEDe_Register* pvalue);

EXTERN int asn1PD_HnbUEDe_Register (OSCTXT* pctxt, HnbUEDe_Register* pvalue);

EXTERN void asn1Print_HnbUEDe_Register
   (const char* name, HnbUEDe_Register* pvalue);

EXTERN void asn1Init_HnbUEDe_Register (HnbUEDe_Register* pvalue);

/**************************************************************/
/*                                                            */
/*  ErrorIndication                                           */
/*                                                            */
/**************************************************************/

typedef struct EXTERN HnbErrorIndication {
   struct {
      unsigned protocolExtensionsPresent : 1;
   } m;
   ProtocolIE_Container protocolIEs;
   ProtocolExtensionContainer protocolExtensions;
   OSRTDList extElem1;
} HnbErrorIndication;

EXTERN int asn1PE_HnbErrorIndication (OSCTXT* pctxt, HnbErrorIndication* pvalue);

EXTERN int asn1PD_HnbErrorIndication (OSCTXT* pctxt, HnbErrorIndication* pvalue);

EXTERN void asn1Print_HnbErrorIndication
   (const char* name, HnbErrorIndication* pvalue);

EXTERN void asn1Init_HnbErrorIndication (HnbErrorIndication* pvalue);

/**************************************************************/
/*                                                            */
/*  PrivateMessage                                            */
/*                                                            */
/**************************************************************/

typedef struct EXTERN HnbPrivateMessage {
   PrivateIE_Container privateIEs;
   OSRTDList extElem1;
} HnbPrivateMessage;

EXTERN int asn1PE_HnbPrivateMessage (OSCTXT* pctxt, HnbPrivateMessage* pvalue);

EXTERN int asn1PD_HnbPrivateMessage (OSCTXT* pctxt, HnbPrivateMessage* pvalue);

EXTERN void asn1Print_HnbPrivateMessage
   (const char* name, HnbPrivateMessage* pvalue);

EXTERN void asn1Init_HnbPrivateMessage (HnbPrivateMessage* pvalue);

#ifdef __cplusplus
}
#endif

#endif
