/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 6.1.4, Date: 06-Jul-2012.
 */
#include "HNBAP-PDU-Contents.h"
#include "HNBAP-Constants.h"
#include "rtsrc/rtPrint.h"
#include "rtxsrc/rtxCommon.h"

void asn1Print_HnbHNBRegisterRequest
   (const char* name, HnbHNBRegisterRequest* pvalue)
{
   rtPrintOpenBrace (name);

   asn1Print_ProtocolIE_Container ("protocolIEs",
      &pvalue->protocolIEs);

   if (pvalue->m.protocolExtensionsPresent) {
      asn1Print_ProtocolExtensionContainer ("protocolExtensions",
         &pvalue->protocolExtensions);
   }

   rtPrintOpenTypeExtBraceText ("extElem1", &pvalue->extElem1);

   rtPrintCloseBrace ();
}

void asn1Print_HnbHNBRegisterAccept
   (const char* name, HnbHNBRegisterAccept* pvalue)
{
   rtPrintOpenBrace (name);

   asn1Print_ProtocolIE_Container ("protocolIEs",
      &pvalue->protocolIEs);

   if (pvalue->m.protocolExtensionsPresent) {
      asn1Print_ProtocolExtensionContainer ("protocolExtensions",
         &pvalue->protocolExtensions);
   }

   rtPrintOpenTypeExtBraceText ("extElem1", &pvalue->extElem1);

   rtPrintCloseBrace ();
}

void asn1Print_HnbHNBRegisterReject
   (const char* name, HnbHNBRegisterReject* pvalue)
{
   rtPrintOpenBrace (name);

   asn1Print_ProtocolIE_Container ("protocolIEs",
      &pvalue->protocolIEs);

   if (pvalue->m.protocolExtensionsPresent) {
      asn1Print_ProtocolExtensionContainer ("protocolExtensions",
         &pvalue->protocolExtensions);
   }

   rtPrintOpenTypeExtBraceText ("extElem1", &pvalue->extElem1);

   rtPrintCloseBrace ();
}

void asn1Print_HnbHNBDe_Register
   (const char* name, HnbHNBDe_Register* pvalue)
{
   rtPrintOpenBrace (name);

   asn1Print_ProtocolIE_Container ("protocolIEs",
      &pvalue->protocolIEs);

   if (pvalue->m.protocolExtensionsPresent) {
      asn1Print_ProtocolExtensionContainer ("protocolExtensions",
         &pvalue->protocolExtensions);
   }

   rtPrintOpenTypeExtBraceText ("extElem1", &pvalue->extElem1);

   rtPrintCloseBrace ();
}

void asn1Print_HnbUERegisterRequest
   (const char* name, HnbUERegisterRequest* pvalue)
{
   rtPrintOpenBrace (name);

   asn1Print_ProtocolIE_Container ("protocolIEs",
      &pvalue->protocolIEs);

   if (pvalue->m.protocolExtensionsPresent) {
      asn1Print_ProtocolExtensionContainer ("protocolExtensions",
         &pvalue->protocolExtensions);
   }

   rtPrintOpenTypeExtBraceText ("extElem1", &pvalue->extElem1);

   rtPrintCloseBrace ();
}

void asn1Print_HnbUERegisterAccept
   (const char* name, HnbUERegisterAccept* pvalue)
{
   rtPrintOpenBrace (name);

   asn1Print_ProtocolIE_Container ("protocolIEs",
      &pvalue->protocolIEs);

   if (pvalue->m.protocolExtensionsPresent) {
      asn1Print_ProtocolExtensionContainer ("protocolExtensions",
         &pvalue->protocolExtensions);
   }

   rtPrintOpenTypeExtBraceText ("extElem1", &pvalue->extElem1);

   rtPrintCloseBrace ();
}

void asn1Print_HnbUERegisterReject
   (const char* name, HnbUERegisterReject* pvalue)
{
   rtPrintOpenBrace (name);

   asn1Print_ProtocolIE_Container ("protocolIEs",
      &pvalue->protocolIEs);

   if (pvalue->m.protocolExtensionsPresent) {
      asn1Print_ProtocolExtensionContainer ("protocolExtensions",
         &pvalue->protocolExtensions);
   }

   rtPrintOpenTypeExtBraceText ("extElem1", &pvalue->extElem1);

   rtPrintCloseBrace ();
}

void asn1Print_HnbUEDe_Register
   (const char* name, HnbUEDe_Register* pvalue)
{
   rtPrintOpenBrace (name);

   asn1Print_ProtocolIE_Container ("protocolIEs",
      &pvalue->protocolIEs);

   if (pvalue->m.protocolExtensionsPresent) {
      asn1Print_ProtocolExtensionContainer ("protocolExtensions",
         &pvalue->protocolExtensions);
   }

   rtPrintOpenTypeExtBraceText ("extElem1", &pvalue->extElem1);

   rtPrintCloseBrace ();
}

void asn1Print_HnbErrorIndication
   (const char* name, HnbErrorIndication* pvalue)
{
   rtPrintOpenBrace (name);

   asn1Print_ProtocolIE_Container ("protocolIEs",
      &pvalue->protocolIEs);

   if (pvalue->m.protocolExtensionsPresent) {
      asn1Print_ProtocolExtensionContainer ("protocolExtensions",
         &pvalue->protocolExtensions);
   }

   rtPrintOpenTypeExtBraceText ("extElem1", &pvalue->extElem1);

   rtPrintCloseBrace ();
}

void asn1Print_HnbPrivateMessage
   (const char* name, HnbPrivateMessage* pvalue)
{
   rtPrintOpenBrace (name);

   asn1Print_PrivateIE_Container ("privateIEs",
      &pvalue->privateIEs);

   rtPrintOpenTypeExtBraceText ("extElem1", &pvalue->extElem1);

   rtPrintCloseBrace ();
}

