/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 6.1.4, Date: 06-Jul-2012.
 */
#include "HNBAP-PDU-Contents.h"
#include "HNBAP-Constants.h"
#include "rtxsrc/rtxCommon.h"

void asn1Init_HnbHNBRegisterRequest (HnbHNBRegisterRequest* pvalue)
{
   if (0 == pvalue) return;
   OSCRTLMEMSET (&pvalue->m, 0, sizeof (pvalue->m));
   asn1Init_ProtocolIE_Container (&pvalue->protocolIEs);
   asn1Init_ProtocolExtensionContainer (&pvalue->protocolExtensions);
   rtxDListFastInit (&pvalue->extElem1);
}

void asn1Init_HnbHNBRegisterAccept (HnbHNBRegisterAccept* pvalue)
{
   if (0 == pvalue) return;
   OSCRTLMEMSET (&pvalue->m, 0, sizeof (pvalue->m));
   asn1Init_ProtocolIE_Container (&pvalue->protocolIEs);
   asn1Init_ProtocolExtensionContainer (&pvalue->protocolExtensions);
   rtxDListFastInit (&pvalue->extElem1);
}

void asn1Init_HnbHNBRegisterReject (HnbHNBRegisterReject* pvalue)
{
   if (0 == pvalue) return;
   OSCRTLMEMSET (&pvalue->m, 0, sizeof (pvalue->m));
   asn1Init_ProtocolIE_Container (&pvalue->protocolIEs);
   asn1Init_ProtocolExtensionContainer (&pvalue->protocolExtensions);
   rtxDListFastInit (&pvalue->extElem1);
}

void asn1Init_HnbHNBDe_Register (HnbHNBDe_Register* pvalue)
{
   if (0 == pvalue) return;
   OSCRTLMEMSET (&pvalue->m, 0, sizeof (pvalue->m));
   asn1Init_ProtocolIE_Container (&pvalue->protocolIEs);
   asn1Init_ProtocolExtensionContainer (&pvalue->protocolExtensions);
   rtxDListFastInit (&pvalue->extElem1);
}

void asn1Init_HnbUERegisterRequest (HnbUERegisterRequest* pvalue)
{
   if (0 == pvalue) return;
   OSCRTLMEMSET (&pvalue->m, 0, sizeof (pvalue->m));
   asn1Init_ProtocolIE_Container (&pvalue->protocolIEs);
   asn1Init_ProtocolExtensionContainer (&pvalue->protocolExtensions);
   rtxDListFastInit (&pvalue->extElem1);
}

void asn1Init_HnbUERegisterAccept (HnbUERegisterAccept* pvalue)
{
   if (0 == pvalue) return;
   OSCRTLMEMSET (&pvalue->m, 0, sizeof (pvalue->m));
   asn1Init_ProtocolIE_Container (&pvalue->protocolIEs);
   asn1Init_ProtocolExtensionContainer (&pvalue->protocolExtensions);
   rtxDListFastInit (&pvalue->extElem1);
}

void asn1Init_HnbUERegisterReject (HnbUERegisterReject* pvalue)
{
   if (0 == pvalue) return;
   OSCRTLMEMSET (&pvalue->m, 0, sizeof (pvalue->m));
   asn1Init_ProtocolIE_Container (&pvalue->protocolIEs);
   asn1Init_ProtocolExtensionContainer (&pvalue->protocolExtensions);
   rtxDListFastInit (&pvalue->extElem1);
}

void asn1Init_HnbUEDe_Register (HnbUEDe_Register* pvalue)
{
   if (0 == pvalue) return;
   OSCRTLMEMSET (&pvalue->m, 0, sizeof (pvalue->m));
   asn1Init_ProtocolIE_Container (&pvalue->protocolIEs);
   asn1Init_ProtocolExtensionContainer (&pvalue->protocolExtensions);
   rtxDListFastInit (&pvalue->extElem1);
}

void asn1Init_HnbErrorIndication (HnbErrorIndication* pvalue)
{
   if (0 == pvalue) return;
   OSCRTLMEMSET (&pvalue->m, 0, sizeof (pvalue->m));
   asn1Init_ProtocolIE_Container (&pvalue->protocolIEs);
   asn1Init_ProtocolExtensionContainer (&pvalue->protocolExtensions);
   rtxDListFastInit (&pvalue->extElem1);
}

void asn1Init_HnbPrivateMessage (HnbPrivateMessage* pvalue)
{
   if (0 == pvalue) return;
   asn1Init_PrivateIE_Container (&pvalue->privateIEs);
   rtxDListFastInit (&pvalue->extElem1);
}

