/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 6.1.4, Date: 09-Jul-2012.
 */
#include "RUA-PDU-Contents.h"
#include "RUA-Constants.h"
#include "rtsrc/rtPrint.h"
#include "rtxsrc/rtxCommon.h"

void asn1Print_RUA_Connect
   (const char* name, RUA_Connect* pvalue)
{
   rtPrintOpenBrace (name);

   asn1Print_RUA_ProtocolIE_Container ("protocolIEs",
      &pvalue->protocolIEs);

   if (pvalue->m.protocolExtensionsPresent) {
      asn1Print_RUA_ProtocolExtensionContainer ("protocolExtensions",
         &pvalue->protocolExtensions);
   }

   rtPrintOpenTypeExtBraceText ("extElem1", &pvalue->extElem1);

   rtPrintCloseBrace ();
}

void asn1Print_RUA_DirectTransfer
   (const char* name, RUA_DirectTransfer* pvalue)
{
   rtPrintOpenBrace (name);

   asn1Print_RUA_ProtocolIE_Container ("protocolIEs",
      &pvalue->protocolIEs);

   if (pvalue->m.protocolExtensionsPresent) {
      asn1Print_RUA_ProtocolExtensionContainer ("protocolExtensions",
         &pvalue->protocolExtensions);
   }

   rtPrintOpenTypeExtBraceText ("extElem1", &pvalue->extElem1);

   rtPrintCloseBrace ();
}

void asn1Print_RUA_Disconnect
   (const char* name, RUA_Disconnect* pvalue)
{
   rtPrintOpenBrace (name);

   asn1Print_RUA_ProtocolIE_Container ("protocolIEs",
      &pvalue->protocolIEs);

   if (pvalue->m.protocolExtensionsPresent) {
      asn1Print_RUA_ProtocolExtensionContainer ("protocolExtensions",
         &pvalue->protocolExtensions);
   }

   rtPrintOpenTypeExtBraceText ("extElem1", &pvalue->extElem1);

   rtPrintCloseBrace ();
}

void asn1Print_RUA_ConnectionlessTransfer
   (const char* name, RUA_ConnectionlessTransfer* pvalue)
{
   rtPrintOpenBrace (name);

   asn1Print_RUA_ProtocolIE_Container ("protocolIEs",
      &pvalue->protocolIEs);

   if (pvalue->m.protocolExtensionsPresent) {
      asn1Print_RUA_ProtocolExtensionContainer ("protocolExtensions",
         &pvalue->protocolExtensions);
   }

   rtPrintOpenTypeExtBraceText ("extElem1", &pvalue->extElem1);

   rtPrintCloseBrace ();
}

void asn1Print_RUA_ErrorIndication
   (const char* name, RUA_ErrorIndication* pvalue)
{
   rtPrintOpenBrace (name);

   asn1Print_RUA_ProtocolIE_Container ("protocolIEs",
      &pvalue->protocolIEs);

   if (pvalue->m.protocolExtensionsPresent) {
      asn1Print_RUA_ProtocolExtensionContainer ("protocolExtensions",
         &pvalue->protocolExtensions);
   }

   rtPrintOpenTypeExtBraceText ("extElem1", &pvalue->extElem1);

   rtPrintCloseBrace ();
}

void asn1Print_RUA_PrivateMessage
   (const char* name, RUA_PrivateMessage* pvalue)
{
   rtPrintOpenBrace (name);

   asn1Print_RUA_PrivateIE_Container ("privateIEs",
      &pvalue->privateIEs);

   rtPrintOpenTypeExtBraceText ("extElem1", &pvalue->extElem1);

   rtPrintCloseBrace ();
}

