/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 6.1.4, Date: 09-Jul-2012.
 */
#include "RUA-CommonDataTypes.h"
#include "rtxsrc/rtxCommon.h"

EXTERN int asn1PD_RUA_ProcedureCode (OSCTXT* pctxt, RUA_ProcedureCode* pvalue)
{
   int stat = 0;

   stat = pd_ConsUInt8 (pctxt, pvalue, OSUINTCONST(0), OSUINTCONST(255));
   if (stat != 0) return LOG_RTERR (pctxt, stat);

   return (stat);
}

EXTERN int asn1PD_RUA_Criticality (OSCTXT* pctxt, RUA_Criticality* pvalue)
{
   int stat = 0;
   OSUINT32 ui;

   stat = pd_ConsUnsigned (pctxt, &ui, 0, OSUINTCONST(2));
   if (stat != 0) return LOG_RTERR (pctxt, stat);

   switch (ui) {
      case 0: *pvalue = RUA_reject; break;
      case 1: *pvalue = RUA_ignore; break;
      case 2: *pvalue = RUA_notify; break;
      default: return LOG_RTERR (pctxt, RTERR_INVENUM);
   }

   return (stat);
}

EXTERN int asn1PD_RUA_ProtocolIE_ID (OSCTXT* pctxt, RUA_ProtocolIE_ID* pvalue)
{
   int stat = 0;

   stat = pd_ConsUInt16 (pctxt, pvalue, OSUINTCONST(0), OSUINTCONST(65535));
   if (stat != 0) return LOG_RTERR (pctxt, stat);

   return (stat);
}

EXTERN int asn1PD_RUA_PrivateIE_ID (OSCTXT* pctxt, RUA_PrivateIE_ID* pvalue)
{
   int stat = 0;
   OSUINT32 ui;

   stat = pd_ConsUnsigned (pctxt, &ui, 0, OSUINTCONST(1));
   if (stat != 0) return LOG_RTERR (pctxt, stat);
   else pvalue->t = ui + 1;

   switch (ui) {
      /* local */
      case 0:
         stat = pd_ConsUInt16 (pctxt, &pvalue->u.local, OSUINTCONST(0), OSUINTCONST(65535));
         if (stat != 0) return LOG_RTERR (pctxt, stat);

         break;

      /* global */
      case 1:
         pvalue->u.global = rtxMemAllocType (pctxt, ASN1OBJID);

         if (pvalue->u.global == NULL)
            return LOG_RTERR (pctxt, RTERR_NOMEM);

         pvalue->u.global->numids = 0;

         stat = pd_ObjectIdentifier (pctxt, pvalue->u.global);
         if (stat != 0) return LOG_RTERR (pctxt, stat);

         break;

      default:
         return LOG_RTERR (pctxt, RTERR_INVOPT);
   }

   return (stat);
}

EXTERN int asn1PD_RUA_TriggeringMessage (OSCTXT* pctxt, RUA_TriggeringMessage* pvalue)
{
   int stat = 0;
   OSUINT32 ui;

   stat = pd_ConsUnsigned (pctxt, &ui, 0, OSUINTCONST(2));
   if (stat != 0) return LOG_RTERR (pctxt, stat);

   switch (ui) {
      case 0: *pvalue = RUA_initiating_message; break;
      case 1: *pvalue = RUA_successful_outcome; break;
      case 2: *pvalue = RUA_unsuccessful_outcome; break;
      default: return LOG_RTERR (pctxt, RTERR_INVENUM);
   }

   return (stat);
}

EXTERN int asn1PD_RUA_Presence (OSCTXT* pctxt, RUA_Presence* pvalue)
{
   int stat = 0;
   OSUINT32 ui;

   stat = pd_ConsUnsigned (pctxt, &ui, 0, OSUINTCONST(2));
   if (stat != 0) return LOG_RTERR (pctxt, stat);

   switch (ui) {
      case 0: *pvalue = RUA_optional; break;
      case 1: *pvalue = RUA_conditional; break;
      case 2: *pvalue = RUA_mandatory; break;
      default: return LOG_RTERR (pctxt, RTERR_INVENUM);
   }

   return (stat);
}

