/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 6.1.4, Date: 09-Jul-2012.
 */
#ifndef RUA_PDU_CONTENTS_H
#define RUA_PDU_CONTENTS_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdio.h>
#include <stdlib.h>
#include "rtkey.h"
#include "rtpersrc/asn1per.h"
#include "RUA-IEs.h"
#include "RUA-Containers.h"

/**
 * Header file for ASN.1 module RUA-PDU-Contents
 */
/**************************************************************/
/*                                                            */
/*  Connect                                                   */
/*                                                            */
/**************************************************************/

typedef struct EXTERN RUA_Connect {
   struct {
      unsigned protocolExtensionsPresent : 1;
   } m;
   RUA_ProtocolIE_Container protocolIEs;
   RUA_ProtocolExtensionContainer protocolExtensions;
   OSRTDList extElem1;
} RUA_Connect;

EXTERN int asn1PE_RUA_Connect (OSCTXT* pctxt, RUA_Connect* pvalue);

EXTERN int asn1PD_RUA_Connect (OSCTXT* pctxt, RUA_Connect* pvalue);

EXTERN void asn1Print_RUA_Connect
   (const char* name, RUA_Connect* pvalue);

EXTERN void asn1Init_RUA_Connect (RUA_Connect* pvalue);

/**************************************************************/
/*                                                            */
/*  DirectTransfer                                            */
/*                                                            */
/**************************************************************/

typedef struct EXTERN RUA_DirectTransfer {
   struct {
      unsigned protocolExtensionsPresent : 1;
   } m;
   RUA_ProtocolIE_Container protocolIEs;
   RUA_ProtocolExtensionContainer protocolExtensions;
   OSRTDList extElem1;
} RUA_DirectTransfer;

EXTERN int asn1PE_RUA_DirectTransfer (OSCTXT* pctxt, RUA_DirectTransfer* pvalue);

EXTERN int asn1PD_RUA_DirectTransfer (OSCTXT* pctxt, RUA_DirectTransfer* pvalue);

EXTERN void asn1Print_RUA_DirectTransfer
   (const char* name, RUA_DirectTransfer* pvalue);

EXTERN void asn1Init_RUA_DirectTransfer (RUA_DirectTransfer* pvalue);

/**************************************************************/
/*                                                            */
/*  Disconnect                                                */
/*                                                            */
/**************************************************************/

typedef struct EXTERN RUA_Disconnect {
   struct {
      unsigned protocolExtensionsPresent : 1;
   } m;
   RUA_ProtocolIE_Container protocolIEs;
   RUA_ProtocolExtensionContainer protocolExtensions;
   OSRTDList extElem1;
} RUA_Disconnect;

EXTERN int asn1PE_RUA_Disconnect (OSCTXT* pctxt, RUA_Disconnect* pvalue);

EXTERN int asn1PD_RUA_Disconnect (OSCTXT* pctxt, RUA_Disconnect* pvalue);

EXTERN void asn1Print_RUA_Disconnect
   (const char* name, RUA_Disconnect* pvalue);

EXTERN void asn1Init_RUA_Disconnect (RUA_Disconnect* pvalue);

/**************************************************************/
/*                                                            */
/*  ConnectionlessTransfer                                    */
/*                                                            */
/**************************************************************/

typedef struct EXTERN RUA_ConnectionlessTransfer {
   struct {
      unsigned protocolExtensionsPresent : 1;
   } m;
   RUA_ProtocolIE_Container protocolIEs;
   RUA_ProtocolExtensionContainer protocolExtensions;
   OSRTDList extElem1;
} RUA_ConnectionlessTransfer;

EXTERN int asn1PE_RUA_ConnectionlessTransfer (OSCTXT* pctxt, RUA_ConnectionlessTransfer* pvalue);

EXTERN int asn1PD_RUA_ConnectionlessTransfer (OSCTXT* pctxt, RUA_ConnectionlessTransfer* pvalue);

EXTERN void asn1Print_RUA_ConnectionlessTransfer
   (const char* name, RUA_ConnectionlessTransfer* pvalue);

EXTERN void asn1Init_RUA_ConnectionlessTransfer (RUA_ConnectionlessTransfer* pvalue);

/**************************************************************/
/*                                                            */
/*  ErrorIndication                                           */
/*                                                            */
/**************************************************************/

typedef struct EXTERN RUA_ErrorIndication {
   struct {
      unsigned protocolExtensionsPresent : 1;
   } m;
   RUA_ProtocolIE_Container protocolIEs;
   RUA_ProtocolExtensionContainer protocolExtensions;
   OSRTDList extElem1;
} RUA_ErrorIndication;

EXTERN int asn1PE_RUA_ErrorIndication (OSCTXT* pctxt, RUA_ErrorIndication* pvalue);

EXTERN int asn1PD_RUA_ErrorIndication (OSCTXT* pctxt, RUA_ErrorIndication* pvalue);

EXTERN void asn1Print_RUA_ErrorIndication
   (const char* name, RUA_ErrorIndication* pvalue);

EXTERN void asn1Init_RUA_ErrorIndication (RUA_ErrorIndication* pvalue);

/**************************************************************/
/*                                                            */
/*  PrivateMessage                                            */
/*                                                            */
/**************************************************************/

typedef struct EXTERN RUA_PrivateMessage {
   RUA_PrivateIE_Container privateIEs;
   OSRTDList extElem1;
} RUA_PrivateMessage;

EXTERN int asn1PE_RUA_PrivateMessage (OSCTXT* pctxt, RUA_PrivateMessage* pvalue);

EXTERN int asn1PD_RUA_PrivateMessage (OSCTXT* pctxt, RUA_PrivateMessage* pvalue);

EXTERN void asn1Print_RUA_PrivateMessage
   (const char* name, RUA_PrivateMessage* pvalue);

EXTERN void asn1Init_RUA_PrivateMessage (RUA_PrivateMessage* pvalue);

#ifdef __cplusplus
}
#endif

#endif
