/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 6.1.4, Date: 09-Jul-2012.
 */
#include "RUA-PDU-Descriptions.h"
#include "RUA-Constants.h"
#include "rtsrc/rtPrint.h"
#include "rtxsrc/rtxCommon.h"

void asn1Print_RUA_InitiatingMessage
   (const char* name, RUA_InitiatingMessage* pvalue)
{
   rtPrintOpenBrace (name);

   asn1Print_RUA_ProcedureCode ("procedureCode",
      &pvalue->procedureCode);

   asn1Print_RUA_Criticality ("criticality",
      &pvalue->criticality);

   rtPrintIndent ();
   rtPrintHexStr ("value",
      pvalue->value.numocts,
      pvalue->value.data);

   rtPrintCloseBrace ();
}

void asn1Print_RUA_SuccessfulOutcome
   (const char* name, RUA_SuccessfulOutcome* pvalue)
{
   rtPrintOpenBrace (name);

   asn1Print_RUA_ProcedureCode ("procedureCode",
      &pvalue->procedureCode);

   asn1Print_RUA_Criticality ("criticality",
      &pvalue->criticality);

   rtPrintIndent ();
   rtPrintHexStr ("value",
      pvalue->value.numocts,
      pvalue->value.data);

   rtPrintCloseBrace ();
}

void asn1Print_RUA_UnsuccessfulOutcome
   (const char* name, RUA_UnsuccessfulOutcome* pvalue)
{
   rtPrintOpenBrace (name);

   asn1Print_RUA_ProcedureCode ("procedureCode",
      &pvalue->procedureCode);

   asn1Print_RUA_Criticality ("criticality",
      &pvalue->criticality);

   rtPrintIndent ();
   rtPrintHexStr ("value",
      pvalue->value.numocts,
      pvalue->value.data);

   rtPrintCloseBrace ();
}

void asn1Print_RUA_RUA_PDU
   (const char* name, RUA_RUA_PDU* pvalue)
{
   rtPrintOpenBrace (name);

   switch (pvalue->t) {
      case 1: {
         asn1Print_RUA_InitiatingMessage ("initiatingMessage",
            pvalue->u.initiatingMessage);
         break;
      }
      case 2: {
         asn1Print_RUA_SuccessfulOutcome ("successfulOutcome",
            pvalue->u.successfulOutcome);
         break;
      }
      case 3: {
         asn1Print_RUA_UnsuccessfulOutcome ("unsuccessfulOutcome",
            pvalue->u.unsuccessfulOutcome);
         break;
      }
      case 4: {
         rtPrintIndent ();
         rtPrintHexStr ("extElem1",
            pvalue->u.extElem1->numocts,
            pvalue->u.extElem1->data);
         break;
      }
      default:;
   }

   rtPrintCloseBrace ();
}

