/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 6.1.4, Date: 09-Jul-2012.
 */
#ifndef RUA_CONTAINERS_H
#define RUA_CONTAINERS_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdio.h>
#include <stdlib.h>
#include "rtkey.h"
#include "rtpersrc/asn1per.h"
#include "RUA-CommonDataTypes.h"

/**
 * Header file for ASN.1 module RUA-Containers
 */
/**************************************************************/
/*                                                            */
/*  ProtocolIE_Field                                          */
/*                                                            */
/**************************************************************/

typedef struct EXTERN RUA_ProtocolIE_Field {
   RUA_ProtocolIE_ID id;
   RUA_Criticality criticality;
   ASN1OpenType value;
} RUA_ProtocolIE_Field;

EXTERN int asn1PE_RUA_ProtocolIE_Field (OSCTXT* pctxt, RUA_ProtocolIE_Field* pvalue);

EXTERN int asn1PD_RUA_ProtocolIE_Field (OSCTXT* pctxt, RUA_ProtocolIE_Field* pvalue);

EXTERN void asn1Print_RUA_ProtocolIE_Field
   (const char* name, RUA_ProtocolIE_Field* pvalue);

EXTERN void asn1Init_RUA_ProtocolIE_Field (RUA_ProtocolIE_Field* pvalue);

/**************************************************************/
/*                                                            */
/*  ProtocolIE_Container                                      */
/*                                                            */
/**************************************************************/

/* List of RUA_ProtocolIE_Field */
typedef OSRTDList RUA_ProtocolIE_Container;

EXTERN int asn1PE_RUA_ProtocolIE_Container (OSCTXT* pctxt, RUA_ProtocolIE_Container* pvalue);

EXTERN int asn1PD_RUA_ProtocolIE_Container (OSCTXT* pctxt, RUA_ProtocolIE_Container* pvalue);

EXTERN void asn1Print_RUA_ProtocolIE_Container
   (const char* name, RUA_ProtocolIE_Container* pvalue);

EXTERN void asn1Init_RUA_ProtocolIE_Container (RUA_ProtocolIE_Container* pvalue);

/**************************************************************/
/*                                                            */
/*  ProtocolExtensionField                                    */
/*                                                            */
/**************************************************************/

typedef struct EXTERN RUA_ProtocolExtensionField {
   RUA_ProtocolIE_ID id;
   RUA_Criticality criticality;
   ASN1OpenType extensionValue;
} RUA_ProtocolExtensionField;

EXTERN int asn1PE_RUA_ProtocolExtensionField (OSCTXT* pctxt, RUA_ProtocolExtensionField* pvalue);

EXTERN int asn1PD_RUA_ProtocolExtensionField (OSCTXT* pctxt, RUA_ProtocolExtensionField* pvalue);

EXTERN void asn1Print_RUA_ProtocolExtensionField
   (const char* name, RUA_ProtocolExtensionField* pvalue);

EXTERN void asn1Init_RUA_ProtocolExtensionField (RUA_ProtocolExtensionField* pvalue);

/**************************************************************/
/*                                                            */
/*  ProtocolExtensionContainer                                */
/*                                                            */
/**************************************************************/

/* List of RUA_ProtocolExtensionField */
typedef OSRTDList RUA_ProtocolExtensionContainer;

EXTERN int asn1PE_RUA_ProtocolExtensionContainer (OSCTXT* pctxt, RUA_ProtocolExtensionContainer* pvalue);

EXTERN int asn1PD_RUA_ProtocolExtensionContainer (OSCTXT* pctxt, RUA_ProtocolExtensionContainer* pvalue);

EXTERN void asn1Print_RUA_ProtocolExtensionContainer
   (const char* name, RUA_ProtocolExtensionContainer* pvalue);

EXTERN void asn1Init_RUA_ProtocolExtensionContainer (
   RUA_ProtocolExtensionContainer* pvalue);

/**************************************************************/
/*                                                            */
/*  PrivateIE_Field                                           */
/*                                                            */
/**************************************************************/

typedef struct EXTERN RUA_PrivateIE_Field {
   RUA_PrivateIE_ID id;
   RUA_Criticality criticality;
   ASN1OpenType value;
} RUA_PrivateIE_Field;

EXTERN int asn1PE_RUA_PrivateIE_Field (OSCTXT* pctxt, RUA_PrivateIE_Field* pvalue);

EXTERN int asn1PD_RUA_PrivateIE_Field (OSCTXT* pctxt, RUA_PrivateIE_Field* pvalue);

EXTERN void asn1Print_RUA_PrivateIE_Field
   (const char* name, RUA_PrivateIE_Field* pvalue);

EXTERN void asn1Init_RUA_PrivateIE_Field (RUA_PrivateIE_Field* pvalue);

/**************************************************************/
/*                                                            */
/*  PrivateIE_Container                                       */
/*                                                            */
/**************************************************************/

/* List of RUA_PrivateIE_Field */
typedef OSRTDList RUA_PrivateIE_Container;

EXTERN int asn1PE_RUA_PrivateIE_Container (OSCTXT* pctxt, RUA_PrivateIE_Container* pvalue);

EXTERN int asn1PD_RUA_PrivateIE_Container (OSCTXT* pctxt, RUA_PrivateIE_Container* pvalue);

EXTERN void asn1Print_RUA_PrivateIE_Container
   (const char* name, RUA_PrivateIE_Container* pvalue);

EXTERN void asn1Init_RUA_PrivateIE_Container (RUA_PrivateIE_Container* pvalue);

/**************************************************************/
/*                                                            */
/*  ProtocolIE_Single_Container                               */
/*                                                            */
/**************************************************************/

typedef RUA_ProtocolIE_Field RUA_ProtocolIE_Single_Container;

EXTERN int asn1PE_RUA_ProtocolIE_Single_Container (OSCTXT* pctxt, RUA_ProtocolIE_Single_Container* pvalue);

EXTERN int asn1PD_RUA_ProtocolIE_Single_Container (OSCTXT* pctxt, RUA_ProtocolIE_Single_Container* pvalue);

EXTERN void asn1Print_RUA_ProtocolIE_Single_Container
   (const char* name, RUA_ProtocolIE_Single_Container* pvalue);

EXTERN void asn1Init_RUA_ProtocolIE_Single_Container (
   RUA_ProtocolIE_Single_Container* pvalue);

#ifdef __cplusplus
}
#endif

#endif
