/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 6.1.4, Date: 09-Jul-2012.
 */
#include "RUA-Containers.h"
#include "rtxsrc/rtxCommon.h"

EXTERN int asn1PD_RUA_ProtocolIE_Field (OSCTXT* pctxt, RUA_ProtocolIE_Field* pvalue)
{
   int stat = 0;

   /* decode id */

   stat = asn1PD_RUA_ProtocolIE_ID (pctxt, &pvalue->id);
   if (stat != 0) return LOG_RTERR (pctxt, stat);

   /* decode criticality */

   stat = asn1PD_RUA_Criticality (pctxt, &pvalue->criticality);
   if (stat != 0) return LOG_RTERR (pctxt, stat);

   /* decode value */

   stat = pd_OpenType (pctxt, &pvalue->value.data, &pvalue->value.numocts);
   if (stat != 0) return LOG_RTERR (pctxt, stat);

   return (stat);
}

EXTERN int asn1PD_RUA_ProtocolIE_Container (OSCTXT* pctxt, RUA_ProtocolIE_Container* pvalue)
{
   static Asn1SizeCnst lsize1 = { 0, OSUINTCONST(0), OSUINTCONST(65535), 0 };
   int stat = 0;
   RUA_ProtocolIE_Field* pdata;
   OSRTDListNode* pnode;
   OSUINT32 count = 0;
   OSUINT32 xx1 = 0;

   /* decode length determinant */

   stat = pu_addSizeConstraint (pctxt, &lsize1);
   if (stat != 0) return LOG_RTERR (pctxt, stat);

   stat = pd_Length (pctxt, &count);
   if (stat != 0) return LOG_RTERR (pctxt, stat);

   /* decode elements */

   rtxDListInit (pvalue);

   for (xx1 = 0; xx1 < count; xx1++) {
      rtxDListAllocNodeAndData (pctxt, RUA_ProtocolIE_Field, &pnode, &pdata);

      if (pnode == NULL)
         return LOG_RTERR (pctxt, RTERR_NOMEM);

      asn1Init_RUA_ProtocolIE_Field (pdata);

      stat = asn1PD_RUA_ProtocolIE_Field (pctxt, pdata);
      if (stat != 0) return LOG_RTERR (pctxt, stat);
      rtxDListAppendNode (pvalue, pnode);
   }

   return (stat);
}

EXTERN int asn1PD_RUA_ProtocolExtensionField (OSCTXT* pctxt, RUA_ProtocolExtensionField* pvalue)
{
   int stat = 0;

   /* decode id */

   stat = asn1PD_RUA_ProtocolIE_ID (pctxt, &pvalue->id);
   if (stat != 0) return LOG_RTERR (pctxt, stat);

   /* decode criticality */

   stat = asn1PD_RUA_Criticality (pctxt, &pvalue->criticality);
   if (stat != 0) return LOG_RTERR (pctxt, stat);

   /* decode extensionValue */

   stat = pd_OpenType (pctxt, &pvalue->extensionValue.data, &pvalue->extensionValue.numocts);
   if (stat != 0) return LOG_RTERR (pctxt, stat);

   return (stat);
}

EXTERN int asn1PD_RUA_ProtocolExtensionContainer (OSCTXT* pctxt, RUA_ProtocolExtensionContainer* pvalue)
{
   static Asn1SizeCnst lsize1 = { 0, OSUINTCONST(1), OSUINTCONST(65535), 0 };
   int stat = 0;
   RUA_ProtocolExtensionField* pdata;
   OSRTDListNode* pnode;
   OSUINT32 count = 0;
   OSUINT32 xx1 = 0;

   /* decode length determinant */

   stat = pu_addSizeConstraint (pctxt, &lsize1);
   if (stat != 0) return LOG_RTERR (pctxt, stat);

   stat = pd_Length (pctxt, &count);
   if (stat != 0) return LOG_RTERR (pctxt, stat);

   /* decode elements */

   rtxDListInit (pvalue);

   for (xx1 = 0; xx1 < count; xx1++) {
      rtxDListAllocNodeAndData (pctxt, RUA_ProtocolExtensionField, &pnode, &pdata);

      if (pnode == NULL)
         return LOG_RTERR (pctxt, RTERR_NOMEM);

      asn1Init_RUA_ProtocolExtensionField (pdata);

      stat = asn1PD_RUA_ProtocolExtensionField (pctxt, pdata);
      if (stat != 0) return LOG_RTERR (pctxt, stat);
      rtxDListAppendNode (pvalue, pnode);
   }

   return (stat);
}

EXTERN int asn1PD_RUA_PrivateIE_Field (OSCTXT* pctxt, RUA_PrivateIE_Field* pvalue)
{
   int stat = 0;

   /* decode id */

   asn1Init_RUA_PrivateIE_ID (&pvalue->id);

   stat = asn1PD_RUA_PrivateIE_ID (pctxt, &pvalue->id);
   if (stat != 0) return LOG_RTERR (pctxt, stat);

   /* decode criticality */

   stat = asn1PD_RUA_Criticality (pctxt, &pvalue->criticality);
   if (stat != 0) return LOG_RTERR (pctxt, stat);

   /* decode value */

   stat = pd_OpenType (pctxt, &pvalue->value.data, &pvalue->value.numocts);
   if (stat != 0) return LOG_RTERR (pctxt, stat);

   return (stat);
}

EXTERN int asn1PD_RUA_PrivateIE_Container (OSCTXT* pctxt, RUA_PrivateIE_Container* pvalue)
{
   static Asn1SizeCnst lsize1 = { 0, OSUINTCONST(1), OSUINTCONST(65535), 0 };
   int stat = 0;
   RUA_PrivateIE_Field* pdata;
   OSRTDListNode* pnode;
   OSUINT32 count = 0;
   OSUINT32 xx1 = 0;

   /* decode length determinant */

   stat = pu_addSizeConstraint (pctxt, &lsize1);
   if (stat != 0) return LOG_RTERR (pctxt, stat);

   stat = pd_Length (pctxt, &count);
   if (stat != 0) return LOG_RTERR (pctxt, stat);

   /* decode elements */

   rtxDListInit (pvalue);

   for (xx1 = 0; xx1 < count; xx1++) {
      rtxDListAllocNodeAndData (pctxt, RUA_PrivateIE_Field, &pnode, &pdata);

      if (pnode == NULL)
         return LOG_RTERR (pctxt, RTERR_NOMEM);

      asn1Init_RUA_PrivateIE_Field (pdata);

      stat = asn1PD_RUA_PrivateIE_Field (pctxt, pdata);
      if (stat != 0) return LOG_RTERR (pctxt, stat);
      rtxDListAppendNode (pvalue, pnode);
   }

   return (stat);
}

EXTERN int asn1PD_RUA_ProtocolIE_Single_Container (OSCTXT* pctxt, RUA_ProtocolIE_Single_Container* pvalue)
{
   int stat = 0;

   asn1Init_RUA_ProtocolIE_Field (pvalue);

   stat = asn1PD_RUA_ProtocolIE_Field (pctxt, pvalue);
   if (stat != 0) return LOG_RTERR (pctxt, stat);

   return (stat);
}

