/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 6.1.4, Date: 09-Jul-2012.
 */
#ifndef RUA_IES_H
#define RUA_IES_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdio.h>
#include <stdlib.h>
#include "rtkey.h"
#include "rtpersrc/asn1per.h"
#include "RUA-CommonDataTypes.h"
#include "RUA-Containers.h"

/**
 * Header file for ASN.1 module RUA-IEs
 */
/**************************************************************/
/*                                                            */
/*  CN_DomainIndicator                                        */
/*                                                            */
/**************************************************************/

typedef enum {
   RUA_cs_domain = 0,
   RUA_ps_domain = 1
} RUA_CN_DomainIndicator_Root;

typedef OSUINT32 RUA_CN_DomainIndicator;

EXTERN int asn1PE_RUA_CN_DomainIndicator (OSCTXT* pctxt, RUA_CN_DomainIndicator value);

EXTERN int asn1PD_RUA_CN_DomainIndicator (OSCTXT* pctxt, RUA_CN_DomainIndicator* pvalue);

EXTERN void asn1Print_RUA_CN_DomainIndicator
   (const char* name, RUA_CN_DomainIndicator* pvalue);

EXTERN const OSUTF8CHAR* RUA_CN_DomainIndicator_ToString (OSINT32 value);

EXTERN int RUA_CN_DomainIndicator_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, RUA_CN_DomainIndicator* pvalue);

/**************************************************************/
/*                                                            */
/*  Establishment_Cause                                       */
/*                                                            */
/**************************************************************/

typedef enum {
   RUA_emergency_call = 0,
   RUA_normal_call = 1
} RUA_Establishment_Cause_Root;

typedef OSUINT32 RUA_Establishment_Cause;

EXTERN int asn1PE_RUA_Establishment_Cause (OSCTXT* pctxt, RUA_Establishment_Cause value);

EXTERN int asn1PD_RUA_Establishment_Cause (OSCTXT* pctxt, RUA_Establishment_Cause* pvalue);

EXTERN void asn1Print_RUA_Establishment_Cause
   (const char* name, RUA_Establishment_Cause* pvalue);

EXTERN const OSUTF8CHAR* RUA_Establishment_Cause_ToString (OSINT32 value);

EXTERN int RUA_Establishment_Cause_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, RUA_Establishment_Cause* pvalue);

/**************************************************************/
/*                                                            */
/*  Context_ID                                                */
/*                                                            */
/**************************************************************/

typedef struct EXTERN RUA_Context_ID {
   OSUINT32  numbits;
   OSOCTET data[3];
} RUA_Context_ID;

EXTERN int asn1PE_RUA_Context_ID (OSCTXT* pctxt, RUA_Context_ID* pvalue);

EXTERN int asn1PD_RUA_Context_ID (OSCTXT* pctxt, RUA_Context_ID* pvalue);

EXTERN void asn1Print_RUA_Context_ID
   (const char* name, RUA_Context_ID* pvalue);

EXTERN void asn1Init_RUA_Context_ID (RUA_Context_ID* pvalue);

/**************************************************************/
/*                                                            */
/*  Ansi_41_IDNNS                                             */
/*                                                            */
/**************************************************************/

typedef struct EXTERN RUA_Ansi_41_IDNNS {
   OSUINT32  numbits;
   OSOCTET data[2];
} RUA_Ansi_41_IDNNS;

EXTERN int asn1PE_RUA_Ansi_41_IDNNS (OSCTXT* pctxt, RUA_Ansi_41_IDNNS* pvalue);

EXTERN int asn1PD_RUA_Ansi_41_IDNNS (OSCTXT* pctxt, RUA_Ansi_41_IDNNS* pvalue);

EXTERN void asn1Print_RUA_Ansi_41_IDNNS
   (const char* name, RUA_Ansi_41_IDNNS* pvalue);

EXTERN void asn1Init_RUA_Ansi_41_IDNNS (RUA_Ansi_41_IDNNS* pvalue);

/**************************************************************/
/*                                                            */
/*  RANAP_Message                                             */
/*                                                            */
/**************************************************************/

typedef OSDynOctStr RUA_RANAP_Message;

EXTERN int asn1PE_RUA_RANAP_Message (OSCTXT* pctxt, RUA_RANAP_Message value);

EXTERN int asn1PD_RUA_RANAP_Message (OSCTXT* pctxt, RUA_RANAP_Message* pvalue);

EXTERN void asn1Print_RUA_RANAP_Message
   (const char* name, RUA_RANAP_Message* pvalue);

EXTERN void asn1Init_RUA_RANAP_Message (RUA_RANAP_Message* pvalue);

/**************************************************************/
/*                                                            */
/*  RoutingParameter                                          */
/*                                                            */
/**************************************************************/

typedef struct EXTERN RUA_RoutingParameter {
   OSUINT32  numbits;
   OSOCTET data[2];
} RUA_RoutingParameter;

EXTERN int asn1PE_RUA_RoutingParameter (OSCTXT* pctxt, RUA_RoutingParameter* pvalue);

EXTERN int asn1PD_RUA_RoutingParameter (OSCTXT* pctxt, RUA_RoutingParameter* pvalue);

EXTERN void asn1Print_RUA_RoutingParameter
   (const char* name, RUA_RoutingParameter* pvalue);

EXTERN void asn1Init_RUA_RoutingParameter (RUA_RoutingParameter* pvalue);

/**************************************************************/
/*                                                            */
/*  CauseRadioNetwork                                         */
/*                                                            */
/**************************************************************/

typedef enum {
   RUA_normal = 0,
   RUA_connect_failed = 1,
   RUA_network_release = 2,
   RUA_unspecified = 3
} RUA_CauseRadioNetwork_Root;

typedef OSUINT32 RUA_CauseRadioNetwork;

EXTERN int asn1PE_RUA_CauseRadioNetwork (OSCTXT* pctxt, RUA_CauseRadioNetwork value);

EXTERN int asn1PD_RUA_CauseRadioNetwork (OSCTXT* pctxt, RUA_CauseRadioNetwork* pvalue);

EXTERN void asn1Print_RUA_CauseRadioNetwork
   (const char* name, RUA_CauseRadioNetwork* pvalue);

EXTERN const OSUTF8CHAR* RUA_CauseRadioNetwork_ToString (OSINT32 value);

EXTERN int RUA_CauseRadioNetwork_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, RUA_CauseRadioNetwork* pvalue);

/**************************************************************/
/*                                                            */
/*  CauseTransport                                            */
/*                                                            */
/**************************************************************/

typedef enum {
   RUA_transport_resource_unavailable = 0,
   RUA_unspecified_1 = 1
} RUA_CauseTransport_Root;

typedef OSUINT32 RUA_CauseTransport;

EXTERN int asn1PE_RUA_CauseTransport (OSCTXT* pctxt, RUA_CauseTransport value);

EXTERN int asn1PD_RUA_CauseTransport (OSCTXT* pctxt, RUA_CauseTransport* pvalue);

EXTERN void asn1Print_RUA_CauseTransport
   (const char* name, RUA_CauseTransport* pvalue);

EXTERN const OSUTF8CHAR* RUA_CauseTransport_ToString (OSINT32 value);

EXTERN int RUA_CauseTransport_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, RUA_CauseTransport* pvalue);

/**************************************************************/
/*                                                            */
/*  CauseProtocol                                             */
/*                                                            */
/**************************************************************/

typedef enum {
   RUA_transfer_syntax_error = 0,
   RUA_abstract_syntax_error_reject = 1,
   RUA_abstract_syntax_error_ignore_and_notify = 2,
   RUA_message_not_compatible_with_receiver_state = 3,
   RUA_semantic_error = 4,
   RUA_unspecified_2 = 5,
   RUA_abstract_syntax_error_falsely_constructed_message = 6
} RUA_CauseProtocol_Root;

typedef OSUINT32 RUA_CauseProtocol;

EXTERN int asn1PE_RUA_CauseProtocol (OSCTXT* pctxt, RUA_CauseProtocol value);

EXTERN int asn1PD_RUA_CauseProtocol (OSCTXT* pctxt, RUA_CauseProtocol* pvalue);

EXTERN void asn1Print_RUA_CauseProtocol
   (const char* name, RUA_CauseProtocol* pvalue);

EXTERN const OSUTF8CHAR* RUA_CauseProtocol_ToString (OSINT32 value);

EXTERN int RUA_CauseProtocol_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, RUA_CauseProtocol* pvalue);

/**************************************************************/
/*                                                            */
/*  CauseMisc                                                 */
/*                                                            */
/**************************************************************/

typedef enum {
   RUA_processing_overload = 0,
   RUA_hardware_failure = 1,
   RUA_o_and_m_intervention = 2,
   RUA_unspecified_3 = 3
} RUA_CauseMisc_Root;

typedef OSUINT32 RUA_CauseMisc;

EXTERN int asn1PE_RUA_CauseMisc (OSCTXT* pctxt, RUA_CauseMisc value);

EXTERN int asn1PD_RUA_CauseMisc (OSCTXT* pctxt, RUA_CauseMisc* pvalue);

EXTERN void asn1Print_RUA_CauseMisc
   (const char* name, RUA_CauseMisc* pvalue);

EXTERN const OSUTF8CHAR* RUA_CauseMisc_ToString (OSINT32 value);

EXTERN int RUA_CauseMisc_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, RUA_CauseMisc* pvalue);

/**************************************************************/
/*                                                            */
/*  TypeOfError                                               */
/*                                                            */
/**************************************************************/

typedef enum {
   RUA_not_understood = 0,
   RUA_missing = 1
} RUA_TypeOfError_Root;

typedef OSUINT32 RUA_TypeOfError;

EXTERN int asn1PE_RUA_TypeOfError (OSCTXT* pctxt, RUA_TypeOfError value);

EXTERN int asn1PD_RUA_TypeOfError (OSCTXT* pctxt, RUA_TypeOfError* pvalue);

EXTERN void asn1Print_RUA_TypeOfError
   (const char* name, RUA_TypeOfError* pvalue);

EXTERN const OSUTF8CHAR* RUA_TypeOfError_ToString (OSINT32 value);

EXTERN int RUA_TypeOfError_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, RUA_TypeOfError* pvalue);

/**************************************************************/
/*                                                            */
/*  IntraDomainNasNodeSelector_version_later_futurecoding     */
/*                                                            */
/**************************************************************/

typedef struct EXTERN RUA_IntraDomainNasNodeSelector_version_later_futurecoding {
   OSUINT32  numbits;
   OSOCTET data[2];
} RUA_IntraDomainNasNodeSelector_version_later_futurecoding;

EXTERN int asn1PE_RUA_IntraDomainNasNodeSelector_version_later_futurecoding (OSCTXT* pctxt, RUA_IntraDomainNasNodeSelector_version_later_futurecoding* pvalue);

EXTERN int asn1PD_RUA_IntraDomainNasNodeSelector_version_later_futurecoding (OSCTXT* pctxt, RUA_IntraDomainNasNodeSelector_version_later_futurecoding* pvalue);

EXTERN void asn1Print_RUA_IntraDomainNasNodeSelector_version_later_futurecoding
   (const char* name, RUA_IntraDomainNasNodeSelector_version_later_futurecoding* pvalue);

EXTERN void asn1Init_RUA_IntraDomainNasNodeSelector_version_later_futurecoding (
   RUA_IntraDomainNasNodeSelector_version_later_futurecoding* pvalue);

/**************************************************************/
/*                                                            */
/*  Gsm_map_IDNNS_routingbasis_localPTMSI                     */
/*                                                            */
/**************************************************************/

typedef struct EXTERN RUA_Gsm_map_IDNNS_routingbasis_localPTMSI {
   RUA_RoutingParameter routingparameter;
} RUA_Gsm_map_IDNNS_routingbasis_localPTMSI;

EXTERN int asn1PE_RUA_Gsm_map_IDNNS_routingbasis_localPTMSI (OSCTXT* pctxt, RUA_Gsm_map_IDNNS_routingbasis_localPTMSI* pvalue);

EXTERN int asn1PD_RUA_Gsm_map_IDNNS_routingbasis_localPTMSI (OSCTXT* pctxt, RUA_Gsm_map_IDNNS_routingbasis_localPTMSI* pvalue);

EXTERN void asn1Print_RUA_Gsm_map_IDNNS_routingbasis_localPTMSI
   (const char* name, RUA_Gsm_map_IDNNS_routingbasis_localPTMSI* pvalue);

EXTERN void asn1Init_RUA_Gsm_map_IDNNS_routingbasis_localPTMSI (
   RUA_Gsm_map_IDNNS_routingbasis_localPTMSI* pvalue);

/**************************************************************/
/*                                                            */
/*  Gsm_map_IDNNS_routingbasis_tMSIofsamePLMN                 */
/*                                                            */
/**************************************************************/

typedef struct EXTERN RUA_Gsm_map_IDNNS_routingbasis_tMSIofsamePLMN {
   RUA_RoutingParameter routingparameter;
} RUA_Gsm_map_IDNNS_routingbasis_tMSIofsamePLMN;

EXTERN int asn1PE_RUA_Gsm_map_IDNNS_routingbasis_tMSIofsamePLMN (OSCTXT* pctxt, RUA_Gsm_map_IDNNS_routingbasis_tMSIofsamePLMN* pvalue);

EXTERN int asn1PD_RUA_Gsm_map_IDNNS_routingbasis_tMSIofsamePLMN (OSCTXT* pctxt, RUA_Gsm_map_IDNNS_routingbasis_tMSIofsamePLMN* pvalue);

EXTERN void asn1Print_RUA_Gsm_map_IDNNS_routingbasis_tMSIofsamePLMN
   (const char* name, RUA_Gsm_map_IDNNS_routingbasis_tMSIofsamePLMN* pvalue);

EXTERN void asn1Init_RUA_Gsm_map_IDNNS_routingbasis_tMSIofsamePLMN (
   RUA_Gsm_map_IDNNS_routingbasis_tMSIofsamePLMN* pvalue);

/**************************************************************/
/*                                                            */
/*  Gsm_map_IDNNS_routingbasis_tMSIofdifferentPLMN            */
/*                                                            */
/**************************************************************/

typedef struct EXTERN RUA_Gsm_map_IDNNS_routingbasis_tMSIofdifferentPLMN {
   RUA_RoutingParameter routingparameter;
} RUA_Gsm_map_IDNNS_routingbasis_tMSIofdifferentPLMN;

EXTERN int asn1PE_RUA_Gsm_map_IDNNS_routingbasis_tMSIofdifferentPLMN (OSCTXT* pctxt, RUA_Gsm_map_IDNNS_routingbasis_tMSIofdifferentPLMN* pvalue);

EXTERN int asn1PD_RUA_Gsm_map_IDNNS_routingbasis_tMSIofdifferentPLMN (OSCTXT* pctxt, RUA_Gsm_map_IDNNS_routingbasis_tMSIofdifferentPLMN* pvalue);

EXTERN void asn1Print_RUA_Gsm_map_IDNNS_routingbasis_tMSIofdifferentPLMN
   (const char* name, RUA_Gsm_map_IDNNS_routingbasis_tMSIofdifferentPLMN* pvalue);

EXTERN void asn1Init_RUA_Gsm_map_IDNNS_routingbasis_tMSIofdifferentPLMN (
   RUA_Gsm_map_IDNNS_routingbasis_tMSIofdifferentPLMN* pvalue);

/**************************************************************/
/*                                                            */
/*  Gsm_map_IDNNS_routingbasis_iMSIresponsetopaging           */
/*                                                            */
/**************************************************************/

typedef struct EXTERN RUA_Gsm_map_IDNNS_routingbasis_iMSIresponsetopaging {
   RUA_RoutingParameter routingparameter;
} RUA_Gsm_map_IDNNS_routingbasis_iMSIresponsetopaging;

EXTERN int asn1PE_RUA_Gsm_map_IDNNS_routingbasis_iMSIresponsetopaging (OSCTXT* pctxt, RUA_Gsm_map_IDNNS_routingbasis_iMSIresponsetopaging* pvalue);

EXTERN int asn1PD_RUA_Gsm_map_IDNNS_routingbasis_iMSIresponsetopaging (OSCTXT* pctxt, RUA_Gsm_map_IDNNS_routingbasis_iMSIresponsetopaging* pvalue);

EXTERN void asn1Print_RUA_Gsm_map_IDNNS_routingbasis_iMSIresponsetopaging
   (const char* name, RUA_Gsm_map_IDNNS_routingbasis_iMSIresponsetopaging* pvalue);

EXTERN void asn1Init_RUA_Gsm_map_IDNNS_routingbasis_iMSIresponsetopaging (
   RUA_Gsm_map_IDNNS_routingbasis_iMSIresponsetopaging* pvalue);

/**************************************************************/
/*                                                            */
/*  Gsm_map_IDNNS_routingbasis_iMSIcauseUEinitiatedEvent      */
/*                                                            */
/**************************************************************/

typedef struct EXTERN RUA_Gsm_map_IDNNS_routingbasis_iMSIcauseUEinitiatedEvent {
   RUA_RoutingParameter routingparameter;
} RUA_Gsm_map_IDNNS_routingbasis_iMSIcauseUEinitiatedEvent;

EXTERN int asn1PE_RUA_Gsm_map_IDNNS_routingbasis_iMSIcauseUEinitiatedEvent (OSCTXT* pctxt, RUA_Gsm_map_IDNNS_routingbasis_iMSIcauseUEinitiatedEvent* pvalue);

EXTERN int asn1PD_RUA_Gsm_map_IDNNS_routingbasis_iMSIcauseUEinitiatedEvent (OSCTXT* pctxt, RUA_Gsm_map_IDNNS_routingbasis_iMSIcauseUEinitiatedEvent* pvalue);

EXTERN void asn1Print_RUA_Gsm_map_IDNNS_routingbasis_iMSIcauseUEinitiatedEvent
   (const char* name, RUA_Gsm_map_IDNNS_routingbasis_iMSIcauseUEinitiatedEvent* pvalue);

EXTERN void asn1Init_RUA_Gsm_map_IDNNS_routingbasis_iMSIcauseUEinitiatedEvent (
   RUA_Gsm_map_IDNNS_routingbasis_iMSIcauseUEinitiatedEvent* pvalue);

/**************************************************************/
/*                                                            */
/*  Gsm_map_IDNNS_routingbasis_iMEI                           */
/*                                                            */
/**************************************************************/

typedef struct EXTERN RUA_Gsm_map_IDNNS_routingbasis_iMEI {
   RUA_RoutingParameter routingparameter;
} RUA_Gsm_map_IDNNS_routingbasis_iMEI;

EXTERN int asn1PE_RUA_Gsm_map_IDNNS_routingbasis_iMEI (OSCTXT* pctxt, RUA_Gsm_map_IDNNS_routingbasis_iMEI* pvalue);

EXTERN int asn1PD_RUA_Gsm_map_IDNNS_routingbasis_iMEI (OSCTXT* pctxt, RUA_Gsm_map_IDNNS_routingbasis_iMEI* pvalue);

EXTERN void asn1Print_RUA_Gsm_map_IDNNS_routingbasis_iMEI
   (const char* name, RUA_Gsm_map_IDNNS_routingbasis_iMEI* pvalue);

EXTERN void asn1Init_RUA_Gsm_map_IDNNS_routingbasis_iMEI (
   RUA_Gsm_map_IDNNS_routingbasis_iMEI* pvalue);

/**************************************************************/
/*                                                            */
/*  Gsm_map_IDNNS_routingbasis_spare2                         */
/*                                                            */
/**************************************************************/

typedef struct EXTERN RUA_Gsm_map_IDNNS_routingbasis_spare2 {
   RUA_RoutingParameter routingparameter;
} RUA_Gsm_map_IDNNS_routingbasis_spare2;

EXTERN int asn1PE_RUA_Gsm_map_IDNNS_routingbasis_spare2 (OSCTXT* pctxt, RUA_Gsm_map_IDNNS_routingbasis_spare2* pvalue);

EXTERN int asn1PD_RUA_Gsm_map_IDNNS_routingbasis_spare2 (OSCTXT* pctxt, RUA_Gsm_map_IDNNS_routingbasis_spare2* pvalue);

EXTERN void asn1Print_RUA_Gsm_map_IDNNS_routingbasis_spare2
   (const char* name, RUA_Gsm_map_IDNNS_routingbasis_spare2* pvalue);

EXTERN void asn1Init_RUA_Gsm_map_IDNNS_routingbasis_spare2 (
   RUA_Gsm_map_IDNNS_routingbasis_spare2* pvalue);

/**************************************************************/
/*                                                            */
/*  Gsm_map_IDNNS_routingbasis_spare1                         */
/*                                                            */
/**************************************************************/

typedef struct EXTERN RUA_Gsm_map_IDNNS_routingbasis_spare1 {
   RUA_RoutingParameter routingparameter;
} RUA_Gsm_map_IDNNS_routingbasis_spare1;

EXTERN int asn1PE_RUA_Gsm_map_IDNNS_routingbasis_spare1 (OSCTXT* pctxt, RUA_Gsm_map_IDNNS_routingbasis_spare1* pvalue);

EXTERN int asn1PD_RUA_Gsm_map_IDNNS_routingbasis_spare1 (OSCTXT* pctxt, RUA_Gsm_map_IDNNS_routingbasis_spare1* pvalue);

EXTERN void asn1Print_RUA_Gsm_map_IDNNS_routingbasis_spare1
   (const char* name, RUA_Gsm_map_IDNNS_routingbasis_spare1* pvalue);

EXTERN void asn1Init_RUA_Gsm_map_IDNNS_routingbasis_spare1 (
   RUA_Gsm_map_IDNNS_routingbasis_spare1* pvalue);

/**************************************************************/
/*                                                            */
/*  Gsm_map_IDNNS_routingbasis                                */
/*                                                            */
/**************************************************************/

/* Choice tag constants */

#define T_RUA_Gsm_map_IDNNS_routingbasis_localPTMSI 1
#define T_RUA_Gsm_map_IDNNS_routingbasis_tMSIofsamePLMN 2
#define T_RUA_Gsm_map_IDNNS_routingbasis_tMSIofdifferentPLMN 3
#define T_RUA_Gsm_map_IDNNS_routingbasis_iMSIresponsetopaging 4
#define T_RUA_Gsm_map_IDNNS_routingbasis_iMSIcauseUEinitiatedEvent 5
#define T_RUA_Gsm_map_IDNNS_routingbasis_iMEI 6
#define T_RUA_Gsm_map_IDNNS_routingbasis_spare2 7
#define T_RUA_Gsm_map_IDNNS_routingbasis_spare1 8

typedef struct EXTERN RUA_Gsm_map_IDNNS_routingbasis {
   int t;
   union {
      /* t = 1 */
      RUA_Gsm_map_IDNNS_routingbasis_localPTMSI *localPTMSI;
      /* t = 2 */
      RUA_Gsm_map_IDNNS_routingbasis_tMSIofsamePLMN *tMSIofsamePLMN;
      /* t = 3 */
      RUA_Gsm_map_IDNNS_routingbasis_tMSIofdifferentPLMN *tMSIofdifferentPLMN;
      /* t = 4 */
      RUA_Gsm_map_IDNNS_routingbasis_iMSIresponsetopaging *iMSIresponsetopaging;
      /* t = 5 */
      RUA_Gsm_map_IDNNS_routingbasis_iMSIcauseUEinitiatedEvent *iMSIcauseUEinitiatedEvent;
      /* t = 6 */
      RUA_Gsm_map_IDNNS_routingbasis_iMEI *iMEI;
      /* t = 7 */
      RUA_Gsm_map_IDNNS_routingbasis_spare2 *spare2;
      /* t = 8 */
      RUA_Gsm_map_IDNNS_routingbasis_spare1 *spare1;
   } u;
} RUA_Gsm_map_IDNNS_routingbasis;

EXTERN int asn1PE_RUA_Gsm_map_IDNNS_routingbasis (OSCTXT* pctxt, RUA_Gsm_map_IDNNS_routingbasis* pvalue);

EXTERN int asn1PD_RUA_Gsm_map_IDNNS_routingbasis (OSCTXT* pctxt, RUA_Gsm_map_IDNNS_routingbasis* pvalue);

EXTERN void asn1Print_RUA_Gsm_map_IDNNS_routingbasis
   (const char* name, RUA_Gsm_map_IDNNS_routingbasis* pvalue);

EXTERN void asn1Init_RUA_Gsm_map_IDNNS_routingbasis (
   RUA_Gsm_map_IDNNS_routingbasis* pvalue);

/**************************************************************/
/*                                                            */
/*  Gsm_map_IDNNS                                             */
/*                                                            */
/**************************************************************/

typedef struct EXTERN RUA_Gsm_map_IDNNS {
   RUA_Gsm_map_IDNNS_routingbasis routingbasis;
   OSBOOL dummy;
} RUA_Gsm_map_IDNNS;

EXTERN int asn1PE_RUA_Gsm_map_IDNNS (OSCTXT* pctxt, RUA_Gsm_map_IDNNS* pvalue);

EXTERN int asn1PD_RUA_Gsm_map_IDNNS (OSCTXT* pctxt, RUA_Gsm_map_IDNNS* pvalue);

EXTERN void asn1Print_RUA_Gsm_map_IDNNS
   (const char* name, RUA_Gsm_map_IDNNS* pvalue);

EXTERN void asn1Init_RUA_Gsm_map_IDNNS (RUA_Gsm_map_IDNNS* pvalue);

/**************************************************************/
/*                                                            */
/*  IntraDomainNasNodeSelector_version_release99_cn_Type      */
/*                                                            */
/**************************************************************/

/* Choice tag constants */

#define T_RUA_IntraDomainNasNodeSelector_version_release99_cn_Type_gsm_Map_IDNNS 1
#define T_RUA_IntraDomainNasNodeSelector_version_release99_cn_Type_ansi_41_IDNNS 2

typedef struct EXTERN RUA_IntraDomainNasNodeSelector_version_release99_cn_Type {
   int t;
   union {
      /* t = 1 */
      RUA_Gsm_map_IDNNS *gsm_Map_IDNNS;
      /* t = 2 */
      RUA_Ansi_41_IDNNS *ansi_41_IDNNS;
   } u;
} RUA_IntraDomainNasNodeSelector_version_release99_cn_Type;

EXTERN int asn1PE_RUA_IntraDomainNasNodeSelector_version_release99_cn_Type (OSCTXT* pctxt, RUA_IntraDomainNasNodeSelector_version_release99_cn_Type* pvalue);

EXTERN int asn1PD_RUA_IntraDomainNasNodeSelector_version_release99_cn_Type (OSCTXT* pctxt, RUA_IntraDomainNasNodeSelector_version_release99_cn_Type* pvalue);

EXTERN void asn1Print_RUA_IntraDomainNasNodeSelector_version_release99_cn_Type
   (const char* name, RUA_IntraDomainNasNodeSelector_version_release99_cn_Type* pvalue);

EXTERN void asn1Init_RUA_IntraDomainNasNodeSelector_version_release99_cn_Type (
   RUA_IntraDomainNasNodeSelector_version_release99_cn_Type* pvalue);

/**************************************************************/
/*                                                            */
/*  IntraDomainNasNodeSelector_version_release99              */
/*                                                            */
/**************************************************************/

typedef struct EXTERN RUA_IntraDomainNasNodeSelector_version_release99 {
   RUA_IntraDomainNasNodeSelector_version_release99_cn_Type cn_Type;
} RUA_IntraDomainNasNodeSelector_version_release99;

EXTERN int asn1PE_RUA_IntraDomainNasNodeSelector_version_release99 (OSCTXT* pctxt, RUA_IntraDomainNasNodeSelector_version_release99* pvalue);

EXTERN int asn1PD_RUA_IntraDomainNasNodeSelector_version_release99 (OSCTXT* pctxt, RUA_IntraDomainNasNodeSelector_version_release99* pvalue);

EXTERN void asn1Print_RUA_IntraDomainNasNodeSelector_version_release99
   (const char* name, RUA_IntraDomainNasNodeSelector_version_release99* pvalue);

EXTERN void asn1Init_RUA_IntraDomainNasNodeSelector_version_release99 (
   RUA_IntraDomainNasNodeSelector_version_release99* pvalue);

/**************************************************************/
/*                                                            */
/*  IntraDomainNasNodeSelector_version_later                  */
/*                                                            */
/**************************************************************/

typedef struct EXTERN RUA_IntraDomainNasNodeSelector_version_later {
   RUA_IntraDomainNasNodeSelector_version_later_futurecoding futurecoding;
} RUA_IntraDomainNasNodeSelector_version_later;

EXTERN int asn1PE_RUA_IntraDomainNasNodeSelector_version_later (OSCTXT* pctxt, RUA_IntraDomainNasNodeSelector_version_later* pvalue);

EXTERN int asn1PD_RUA_IntraDomainNasNodeSelector_version_later (OSCTXT* pctxt, RUA_IntraDomainNasNodeSelector_version_later* pvalue);

EXTERN void asn1Print_RUA_IntraDomainNasNodeSelector_version_later
   (const char* name, RUA_IntraDomainNasNodeSelector_version_later* pvalue);

EXTERN void asn1Init_RUA_IntraDomainNasNodeSelector_version_later (
   RUA_IntraDomainNasNodeSelector_version_later* pvalue);

/**************************************************************/
/*                                                            */
/*  IntraDomainNasNodeSelector_version                        */
/*                                                            */
/**************************************************************/

/* Choice tag constants */

#define T_RUA_IntraDomainNasNodeSelector_version_release99 1
#define T_RUA_IntraDomainNasNodeSelector_version_later 2

typedef struct EXTERN RUA_IntraDomainNasNodeSelector_version {
   int t;
   union {
      /* t = 1 */
      RUA_IntraDomainNasNodeSelector_version_release99 *release99;
      /* t = 2 */
      RUA_IntraDomainNasNodeSelector_version_later *later;
   } u;
} RUA_IntraDomainNasNodeSelector_version;

EXTERN int asn1PE_RUA_IntraDomainNasNodeSelector_version (OSCTXT* pctxt, RUA_IntraDomainNasNodeSelector_version* pvalue);

EXTERN int asn1PD_RUA_IntraDomainNasNodeSelector_version (OSCTXT* pctxt, RUA_IntraDomainNasNodeSelector_version* pvalue);

EXTERN void asn1Print_RUA_IntraDomainNasNodeSelector_version
   (const char* name, RUA_IntraDomainNasNodeSelector_version* pvalue);

EXTERN void asn1Init_RUA_IntraDomainNasNodeSelector_version (
   RUA_IntraDomainNasNodeSelector_version* pvalue);

/**************************************************************/
/*                                                            */
/*  IntraDomainNasNodeSelector                                */
/*                                                            */
/**************************************************************/

typedef struct EXTERN RUA_IntraDomainNasNodeSelector {
   RUA_IntraDomainNasNodeSelector_version version;
} RUA_IntraDomainNasNodeSelector;

EXTERN int asn1PE_RUA_IntraDomainNasNodeSelector (OSCTXT* pctxt, RUA_IntraDomainNasNodeSelector* pvalue);

EXTERN int asn1PD_RUA_IntraDomainNasNodeSelector (OSCTXT* pctxt, RUA_IntraDomainNasNodeSelector* pvalue);

EXTERN void asn1Print_RUA_IntraDomainNasNodeSelector
   (const char* name, RUA_IntraDomainNasNodeSelector* pvalue);

EXTERN void asn1Init_RUA_IntraDomainNasNodeSelector (
   RUA_IntraDomainNasNodeSelector* pvalue);

/**************************************************************/
/*                                                            */
/*  Cause                                                     */
/*                                                            */
/**************************************************************/

/* Choice tag constants */

#define T_RUA_Cause_radioNetwork        1
#define T_RUA_Cause_transport           2
#define T_RUA_Cause_protocol            3
#define T_RUA_Cause_misc                4
#define T_RUA_Cause_extElem1            5

typedef struct EXTERN RUA_Cause {
   int t;
   union {
      /* t = 1 */
      RUA_CauseRadioNetwork radioNetwork;
      /* t = 2 */
      RUA_CauseTransport transport;
      /* t = 3 */
      RUA_CauseProtocol protocol;
      /* t = 4 */
      RUA_CauseMisc misc;
      /* t = 5 */
      ASN1OpenType *extElem1;
   } u;
} RUA_Cause;

EXTERN int asn1PE_RUA_Cause (OSCTXT* pctxt, RUA_Cause* pvalue);

EXTERN int asn1PD_RUA_Cause (OSCTXT* pctxt, RUA_Cause* pvalue);

EXTERN void asn1Print_RUA_Cause
   (const char* name, RUA_Cause* pvalue);

EXTERN void asn1Init_RUA_Cause (RUA_Cause* pvalue);

/**************************************************************/
/*                                                            */
/*  CriticalityDiagnostics_IE_List_element                    */
/*                                                            */
/**************************************************************/

typedef struct EXTERN RUA_CriticalityDiagnostics_IE_List_element {
   struct {
      unsigned iE_ExtensionsPresent : 1;
   } m;
   RUA_Criticality iECriticality;
   RUA_ProtocolIE_ID iE_ID;
   RUA_TypeOfError typeOfError;
   RUA_ProtocolExtensionContainer iE_Extensions;
   OSRTDList extElem1;
} RUA_CriticalityDiagnostics_IE_List_element;

EXTERN int asn1PE_RUA_CriticalityDiagnostics_IE_List_element (OSCTXT* pctxt, RUA_CriticalityDiagnostics_IE_List_element* pvalue);

EXTERN int asn1PD_RUA_CriticalityDiagnostics_IE_List_element (OSCTXT* pctxt, RUA_CriticalityDiagnostics_IE_List_element* pvalue);

EXTERN void asn1Print_RUA_CriticalityDiagnostics_IE_List_element
   (const char* name, RUA_CriticalityDiagnostics_IE_List_element* pvalue);

EXTERN void asn1Init_RUA_CriticalityDiagnostics_IE_List_element (
   RUA_CriticalityDiagnostics_IE_List_element* pvalue);

/**************************************************************/
/*                                                            */
/*  CriticalityDiagnostics_IE_List                            */
/*                                                            */
/**************************************************************/

/* List of RUA_CriticalityDiagnostics_IE_List_element */
typedef OSRTDList RUA_CriticalityDiagnostics_IE_List;

EXTERN int asn1PE_RUA_CriticalityDiagnostics_IE_List (OSCTXT* pctxt, RUA_CriticalityDiagnostics_IE_List* pvalue);

EXTERN int asn1PD_RUA_CriticalityDiagnostics_IE_List (OSCTXT* pctxt, RUA_CriticalityDiagnostics_IE_List* pvalue);

EXTERN void asn1Print_RUA_CriticalityDiagnostics_IE_List
   (const char* name, RUA_CriticalityDiagnostics_IE_List* pvalue);

EXTERN void asn1Init_RUA_CriticalityDiagnostics_IE_List (
   RUA_CriticalityDiagnostics_IE_List* pvalue);

/**************************************************************/
/*                                                            */
/*  CriticalityDiagnostics                                    */
/*                                                            */
/**************************************************************/

typedef struct EXTERN RUA_CriticalityDiagnostics {
   struct {
      unsigned procedureCodePresent : 1;
      unsigned triggeringMessagePresent : 1;
      unsigned procedureCriticalityPresent : 1;
      unsigned iEsCriticalityDiagnosticsPresent : 1;
      unsigned iE_ExtensionsPresent : 1;
   } m;
   RUA_ProcedureCode procedureCode;
   RUA_TriggeringMessage triggeringMessage;
   RUA_Criticality procedureCriticality;
   RUA_CriticalityDiagnostics_IE_List iEsCriticalityDiagnostics;
   RUA_ProtocolExtensionContainer iE_Extensions;
   OSRTDList extElem1;
} RUA_CriticalityDiagnostics;

EXTERN int asn1PE_RUA_CriticalityDiagnostics (OSCTXT* pctxt, RUA_CriticalityDiagnostics* pvalue);

EXTERN int asn1PD_RUA_CriticalityDiagnostics (OSCTXT* pctxt, RUA_CriticalityDiagnostics* pvalue);

EXTERN void asn1Print_RUA_CriticalityDiagnostics
   (const char* name, RUA_CriticalityDiagnostics* pvalue);

EXTERN void asn1Init_RUA_CriticalityDiagnostics (RUA_CriticalityDiagnostics* pvalue);

#ifdef __cplusplus
}
#endif

#endif
