/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 6.1.4, Date: 09-Jul-2012.
 */
#ifndef RUA_CONSTANTS_H
#define RUA_CONSTANTS_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdio.h>
#include <stdlib.h>
#include "rtkey.h"
#include "rtpersrc/asn1per.h"
#include "RUA-CommonDataTypes.h"

/**
 * Header file for ASN.1 module RUA-Constants
 */
/* Value definitions */

#define ASN1V_RUA_id_Connect 1
#define ASN1V_RUA_id_DirectTransfer 2
#define ASN1V_RUA_id_Disconnect 3
#define ASN1V_RUA_id_ConnectionlessTransfer 4
#define ASN1V_RUA_id_ErrorIndication 5
#define ASN1V_RUA_id_privateMessage 6
#define ASN1V_RUA_maxNrOfErrors 256
#define ASN1V_RUA_id_Cause 1
#define ASN1V_RUA_id_CriticalityDiagnostics 2
#define ASN1V_RUA_id_Context_ID 3
#define ASN1V_RUA_id_RANAP_Message 4
#define ASN1V_RUA_id_IntraDomainNasNodeSelector 5
#define ASN1V_RUA_id_Establishment_Cause 6
#define ASN1V_RUA_id_CN_DomainIndicator 7

#ifdef __cplusplus
}
#endif

#endif
