/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 6.1.4, Date: 09-Jul-2012.
 */
#include "RUA-CommonDataTypes.h"
#include "rtxsrc/rtxCommon.h"

static const OSEnumItem RUA_Criticality_ENUMTAB[] = {
   { OSUTF8("ignore"), 1, 6, 2 },
   { OSUTF8("notify"), 2, 6, 0 },
   { OSUTF8("reject"), 0, 6, 1 }
} ;
#define RUA_Criticality_ENUMTABSIZE 3

const OSUTF8CHAR* RUA_Criticality_ToString (OSINT32 value)
{
   OSINT32 idx = value;

   if (idx >= 0 && idx < RUA_Criticality_ENUMTABSIZE) {
      return RUA_Criticality_ENUMTAB
         [RUA_Criticality_ENUMTAB[idx].transidx].name;
   }
   else
      return OSUTF8("_UNKNOWN_");
}

int RUA_Criticality_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, RUA_Criticality* pvalue)
{
   OSUINT32 valueLen = rtxUTF8LenBytes (value);
   OSINT32 idx = rtxLookupEnum (value, valueLen, RUA_Criticality_ENUMTAB, 
      RUA_Criticality_ENUMTABSIZE);

   if (idx >= 0) {
      *pvalue = (RUA_Criticality)RUA_Criticality_ENUMTAB[idx].value;
      return 0;
   }
   else {
      rtxErrAddStrParm (pctxt, (const char*)value);
      return LOG_RTERR (pctxt, RTERR_INVENUM);
   }
}

void asn1Init_RUA_PrivateIE_ID (RUA_PrivateIE_ID* pvalue)
{
   if (0 == pvalue) return;
   pvalue->t = 0;
   OSCRTLMEMSET (&pvalue->u, 0, sizeof(pvalue->u));
}

static const OSEnumItem RUA_TriggeringMessage_ENUMTAB[] = {
   { OSUTF8("initiating-message"), 0, 18, 0 },
   { OSUTF8("successful-outcome"), 1, 18, 1 },
   { OSUTF8("unsuccessful-outcome"), 2, 20, 2 }
} ;
#define RUA_TriggeringMessage_ENUMTABSIZE 3

const OSUTF8CHAR* RUA_TriggeringMessage_ToString (OSINT32 value)
{
   OSINT32 idx = value;

   if (idx >= 0 && idx < RUA_TriggeringMessage_ENUMTABSIZE) {
      return RUA_TriggeringMessage_ENUMTAB
         [RUA_TriggeringMessage_ENUMTAB[idx].transidx].name;
   }
   else
      return OSUTF8("_UNKNOWN_");
}

int RUA_TriggeringMessage_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, RUA_TriggeringMessage* pvalue)
{
   OSUINT32 valueLen = rtxUTF8LenBytes (value);
   OSINT32 idx = rtxLookupEnum (value, valueLen, 
      RUA_TriggeringMessage_ENUMTAB, RUA_TriggeringMessage_ENUMTABSIZE);

   if (idx >= 0) {
      *pvalue = (RUA_TriggeringMessage)
         RUA_TriggeringMessage_ENUMTAB[idx].value;
      return 0;
   }
   else {
      rtxErrAddStrParm (pctxt, (const char*)value);
      return LOG_RTERR (pctxt, RTERR_INVENUM);
   }
}

static const OSEnumItem RUA_Presence_ENUMTAB[] = {
   { OSUTF8("conditional"), 1, 11, 2 },
   { OSUTF8("mandatory"), 2, 9, 0 },
   { OSUTF8("optional"), 0, 8, 1 }
} ;
#define RUA_Presence_ENUMTABSIZE 3

const OSUTF8CHAR* RUA_Presence_ToString (OSINT32 value)
{
   OSINT32 idx = value;

   if (idx >= 0 && idx < RUA_Presence_ENUMTABSIZE) {
      return RUA_Presence_ENUMTAB[RUA_Presence_ENUMTAB[idx].transidx].name;
   }
   else
      return OSUTF8("_UNKNOWN_");
}

int RUA_Presence_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, RUA_Presence* pvalue)
{
   OSUINT32 valueLen = rtxUTF8LenBytes (value);
   OSINT32 idx = rtxLookupEnum (value, valueLen, RUA_Presence_ENUMTAB, 
      RUA_Presence_ENUMTABSIZE);

   if (idx >= 0) {
      *pvalue = (RUA_Presence)RUA_Presence_ENUMTAB[idx].value;
      return 0;
   }
   else {
      rtxErrAddStrParm (pctxt, (const char*)value);
      return LOG_RTERR (pctxt, RTERR_INVENUM);
   }
}

