/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 6.1.4, Date: 09-Jul-2012.
 */
#include "RUA-PDU-Contents.h"
#include "RUA-Constants.h"
#include "rtxsrc/rtxCommon.h"

void asn1Init_RUA_Connect (RUA_Connect* pvalue)
{
   if (0 == pvalue) return;
   OSCRTLMEMSET (&pvalue->m, 0, sizeof (pvalue->m));
   asn1Init_RUA_ProtocolIE_Container (&pvalue->protocolIEs);
   asn1Init_RUA_ProtocolExtensionContainer (&pvalue->protocolExtensions);
   rtxDListFastInit (&pvalue->extElem1);
}

void asn1Init_RUA_DirectTransfer (RUA_DirectTransfer* pvalue)
{
   if (0 == pvalue) return;
   OSCRTLMEMSET (&pvalue->m, 0, sizeof (pvalue->m));
   asn1Init_RUA_ProtocolIE_Container (&pvalue->protocolIEs);
   asn1Init_RUA_ProtocolExtensionContainer (&pvalue->protocolExtensions);
   rtxDListFastInit (&pvalue->extElem1);
}

void asn1Init_RUA_Disconnect (RUA_Disconnect* pvalue)
{
   if (0 == pvalue) return;
   OSCRTLMEMSET (&pvalue->m, 0, sizeof (pvalue->m));
   asn1Init_RUA_ProtocolIE_Container (&pvalue->protocolIEs);
   asn1Init_RUA_ProtocolExtensionContainer (&pvalue->protocolExtensions);
   rtxDListFastInit (&pvalue->extElem1);
}

void asn1Init_RUA_ConnectionlessTransfer (RUA_ConnectionlessTransfer* pvalue)
{
   if (0 == pvalue) return;
   OSCRTLMEMSET (&pvalue->m, 0, sizeof (pvalue->m));
   asn1Init_RUA_ProtocolIE_Container (&pvalue->protocolIEs);
   asn1Init_RUA_ProtocolExtensionContainer (&pvalue->protocolExtensions);
   rtxDListFastInit (&pvalue->extElem1);
}

void asn1Init_RUA_ErrorIndication (RUA_ErrorIndication* pvalue)
{
   if (0 == pvalue) return;
   OSCRTLMEMSET (&pvalue->m, 0, sizeof (pvalue->m));
   asn1Init_RUA_ProtocolIE_Container (&pvalue->protocolIEs);
   asn1Init_RUA_ProtocolExtensionContainer (&pvalue->protocolExtensions);
   rtxDListFastInit (&pvalue->extElem1);
}

void asn1Init_RUA_PrivateMessage (RUA_PrivateMessage* pvalue)
{
   if (0 == pvalue) return;
   asn1Init_RUA_PrivateIE_Container (&pvalue->privateIEs);
   rtxDListFastInit (&pvalue->extElem1);
}

