/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 6.1.4, Date: 09-Jul-2012.
 */
#ifndef RUA_PDU_DESCRIPTIONS_H
#define RUA_PDU_DESCRIPTIONS_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdio.h>
#include <stdlib.h>
#include "rtkey.h"
#include "rtpersrc/asn1per.h"
#include "RUA-CommonDataTypes.h"
#include "RUA-PDU-Contents.h"

/**
 * Header file for ASN.1 module RUA-PDU-Descriptions
 */
/**************************************************************/
/*                                                            */
/*  InitiatingMessage                                         */
/*                                                            */
/**************************************************************/

typedef struct EXTERN RUA_InitiatingMessage {
   RUA_ProcedureCode procedureCode;
   RUA_Criticality criticality;
   ASN1OpenType value;
} RUA_InitiatingMessage;

EXTERN int asn1PE_RUA_InitiatingMessage (OSCTXT* pctxt, RUA_InitiatingMessage* pvalue);

EXTERN int asn1PD_RUA_InitiatingMessage (OSCTXT* pctxt, RUA_InitiatingMessage* pvalue);

EXTERN void asn1Print_RUA_InitiatingMessage
   (const char* name, RUA_InitiatingMessage* pvalue);

EXTERN void asn1Init_RUA_InitiatingMessage (RUA_InitiatingMessage* pvalue);

/**************************************************************/
/*                                                            */
/*  SuccessfulOutcome                                         */
/*                                                            */
/**************************************************************/

typedef struct EXTERN RUA_SuccessfulOutcome {
   RUA_ProcedureCode procedureCode;
   RUA_Criticality criticality;
   ASN1OpenType value;
} RUA_SuccessfulOutcome;

EXTERN int asn1PE_RUA_SuccessfulOutcome (OSCTXT* pctxt, RUA_SuccessfulOutcome* pvalue);

EXTERN int asn1PD_RUA_SuccessfulOutcome (OSCTXT* pctxt, RUA_SuccessfulOutcome* pvalue);

EXTERN void asn1Print_RUA_SuccessfulOutcome
   (const char* name, RUA_SuccessfulOutcome* pvalue);

EXTERN void asn1Init_RUA_SuccessfulOutcome (RUA_SuccessfulOutcome* pvalue);

/**************************************************************/
/*                                                            */
/*  UnsuccessfulOutcome                                       */
/*                                                            */
/**************************************************************/

typedef struct EXTERN RUA_UnsuccessfulOutcome {
   RUA_ProcedureCode procedureCode;
   RUA_Criticality criticality;
   ASN1OpenType value;
} RUA_UnsuccessfulOutcome;

EXTERN int asn1PE_RUA_UnsuccessfulOutcome (OSCTXT* pctxt, RUA_UnsuccessfulOutcome* pvalue);

EXTERN int asn1PD_RUA_UnsuccessfulOutcome (OSCTXT* pctxt, RUA_UnsuccessfulOutcome* pvalue);

EXTERN void asn1Print_RUA_UnsuccessfulOutcome
   (const char* name, RUA_UnsuccessfulOutcome* pvalue);

EXTERN void asn1Init_RUA_UnsuccessfulOutcome (RUA_UnsuccessfulOutcome* pvalue);

/**************************************************************/
/*                                                            */
/*  RUA_PDU                                                   */
/*                                                            */
/**************************************************************/

/* Choice tag constants */

#define T_RUA_RUA_PDU_initiatingMessage 1
#define T_RUA_RUA_PDU_successfulOutcome 2
#define T_RUA_RUA_PDU_unsuccessfulOutcome 3
#define T_RUA_RUA_PDU_extElem1          4

typedef struct EXTERN RUA_RUA_PDU {
   int t;
   union {
      /* t = 1 */
      RUA_InitiatingMessage *initiatingMessage;
      /* t = 2 */
      RUA_SuccessfulOutcome *successfulOutcome;
      /* t = 3 */
      RUA_UnsuccessfulOutcome *unsuccessfulOutcome;
      /* t = 4 */
      ASN1OpenType *extElem1;
   } u;
} RUA_RUA_PDU;

EXTERN int asn1PE_RUA_RUA_PDU (OSCTXT* pctxt, RUA_RUA_PDU* pvalue);

EXTERN int asn1PD_RUA_RUA_PDU (OSCTXT* pctxt, RUA_RUA_PDU* pvalue);

EXTERN void asn1Print_RUA_RUA_PDU
   (const char* name, RUA_RUA_PDU* pvalue);

EXTERN void asn1Init_RUA_RUA_PDU (RUA_RUA_PDU* pvalue);

#ifdef __cplusplus
}
#endif

#endif
