/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 6.1.4, Date: 09-Jul-2012.
 */
#include "RUA-CommonDataTypes.h"
#include "rtxsrc/rtxCommon.h"

EXTERN int asn1PE_RUA_ProcedureCode (OSCTXT* pctxt, RUA_ProcedureCode value)
{
   int stat = 0;

   stat = pe_ConsUnsigned (pctxt, value, OSUINTCONST(0), OSUINTCONST(255));
   if (stat != 0) return LOG_RTERR (pctxt, stat);

   return (stat);
}

EXTERN int asn1PE_RUA_Criticality (OSCTXT* pctxt, RUA_Criticality value)
{
   int stat = 0;
   OSUINT32 ui;

   switch (value) {
      case RUA_reject: ui = 0; break;
      case RUA_ignore: ui = 1; break;
      case RUA_notify: ui = 2; break;
      default: rtxErrAddUIntParm (pctxt, value);
      return LOG_RTERR (pctxt, RTERR_INVENUM);
   }

   stat = pe_ConsUnsigned (pctxt, ui, 0, OSUINTCONST(2));
   if (stat != 0) return LOG_RTERR (pctxt, stat);

   return (stat);
}

EXTERN int asn1PE_RUA_ProtocolIE_ID (OSCTXT* pctxt, RUA_ProtocolIE_ID value)
{
   int stat = 0;

   stat = pe_ConsUnsigned (pctxt, value, OSUINTCONST(0), OSUINTCONST(65535));
   if (stat != 0) return LOG_RTERR (pctxt, stat);

   return (stat);
}

EXTERN int asn1PE_RUA_PrivateIE_ID (OSCTXT* pctxt, RUA_PrivateIE_ID* pvalue)
{
   int stat = 0;

   /* Encode choice index value */

   stat = pe_ConsUnsigned (pctxt, pvalue->t - 1, 0, 1);
   if (stat != 0) return LOG_RTERR (pctxt, stat);

   /* Encode root element data value */

   switch (pvalue->t)
   {
      /* local */
      case 1:
         stat = pe_ConsUnsigned (pctxt, pvalue->u.local, OSUINTCONST(0), OSUINTCONST(65535));
         if (stat != 0) return LOG_RTERR (pctxt, stat);

         break;

      /* global */
      case 2:
         stat = pe_ObjectIdentifier (pctxt, pvalue->u.global);
         if (stat != 0) return LOG_RTERR (pctxt, stat);
         break;

      default:
         return LOG_RTERR (pctxt, RTERR_INVOPT);
   }

   return (stat);
}

EXTERN int asn1PE_RUA_TriggeringMessage (OSCTXT* pctxt, RUA_TriggeringMessage value)
{
   int stat = 0;
   OSUINT32 ui;

   switch (value) {
      case RUA_initiating_message: ui = 0; break;
      case RUA_successful_outcome: ui = 1; break;
      case RUA_unsuccessful_outcome: ui = 2; break;
      default: rtxErrAddUIntParm (pctxt, value);
      return LOG_RTERR (pctxt, RTERR_INVENUM);
   }

   stat = pe_ConsUnsigned (pctxt, ui, 0, OSUINTCONST(2));
   if (stat != 0) return LOG_RTERR (pctxt, stat);

   return (stat);
}

EXTERN int asn1PE_RUA_Presence (OSCTXT* pctxt, RUA_Presence value)
{
   int stat = 0;
   OSUINT32 ui;

   switch (value) {
      case RUA_optional: ui = 0; break;
      case RUA_conditional: ui = 1; break;
      case RUA_mandatory: ui = 2; break;
      default: rtxErrAddUIntParm (pctxt, value);
      return LOG_RTERR (pctxt, RTERR_INVENUM);
   }

   stat = pe_ConsUnsigned (pctxt, ui, 0, OSUINTCONST(2));
   if (stat != 0) return LOG_RTERR (pctxt, stat);

   return (stat);
}

