/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 6.1.4, Date: 09-Jul-2012.
 */
#include "RUA-IEs.h"
#include "RUA-Constants.h"
#include "rtxsrc/rtxCommon.h"

static const OSEnumItem RUA_CN_DomainIndicator_ENUMTAB[] = {
   { OSUTF8("cs-domain"), 0, 9, 0 },
   { OSUTF8("ps-domain"), 1, 9, 1 }
} ;
#define RUA_CN_DomainIndicator_ENUMTABSIZE 2

const OSUTF8CHAR* RUA_CN_DomainIndicator_ToString (OSINT32 value)
{
   OSINT32 idx = value;

   if (idx >= 0 && idx < RUA_CN_DomainIndicator_ENUMTABSIZE) {
      return RUA_CN_DomainIndicator_ENUMTAB
         [RUA_CN_DomainIndicator_ENUMTAB[idx].transidx].name;
   }
   else
      return OSUTF8("_UNKNOWN_");
}

int RUA_CN_DomainIndicator_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, RUA_CN_DomainIndicator* pvalue)
{
   OSUINT32 valueLen = rtxUTF8LenBytes (value);
   OSINT32 idx = rtxLookupEnum (value, valueLen, 
      RUA_CN_DomainIndicator_ENUMTAB, RUA_CN_DomainIndicator_ENUMTABSIZE);

   if (idx >= 0) {
      *pvalue = (RUA_CN_DomainIndicator)
         RUA_CN_DomainIndicator_ENUMTAB[idx].value;
      return 0;
   }
   else {
      rtxErrAddStrParm (pctxt, (const char*)value);
      return LOG_RTERR (pctxt, RTERR_INVENUM);
   }
}

static const OSEnumItem RUA_Establishment_Cause_ENUMTAB[] = {
   { OSUTF8("emergency-call"), 0, 14, 0 },
   { OSUTF8("normal-call"), 1, 11, 1 }
} ;
#define RUA_Establishment_Cause_ENUMTABSIZE 2

const OSUTF8CHAR* RUA_Establishment_Cause_ToString (OSINT32 value)
{
   OSINT32 idx = value;

   if (idx >= 0 && idx < RUA_Establishment_Cause_ENUMTABSIZE) {
      return RUA_Establishment_Cause_ENUMTAB
         [RUA_Establishment_Cause_ENUMTAB[idx].transidx].name;
   }
   else
      return OSUTF8("_UNKNOWN_");
}

int RUA_Establishment_Cause_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, RUA_Establishment_Cause* pvalue)
{
   OSUINT32 valueLen = rtxUTF8LenBytes (value);
   OSINT32 idx = rtxLookupEnum (value, valueLen, 
      RUA_Establishment_Cause_ENUMTAB, RUA_Establishment_Cause_ENUMTABSIZE);

   if (idx >= 0) {
      *pvalue = (RUA_Establishment_Cause)
         RUA_Establishment_Cause_ENUMTAB[idx].value;
      return 0;
   }
   else {
      rtxErrAddStrParm (pctxt, (const char*)value);
      return LOG_RTERR (pctxt, RTERR_INVENUM);
   }
}

void asn1Init_RUA_Context_ID (RUA_Context_ID* pvalue)
{
   if (0 == pvalue) return;
   pvalue->numbits = 0;
}

void asn1Init_RUA_Ansi_41_IDNNS (RUA_Ansi_41_IDNNS* pvalue)
{
   if (0 == pvalue) return;
   pvalue->numbits = 0;
}

void asn1Init_RUA_RANAP_Message (RUA_RANAP_Message* pvalue)
{
   if (0 == pvalue) return;
   pvalue->numocts = 0;
   pvalue->data = 0;
}

void asn1Init_RUA_RoutingParameter (RUA_RoutingParameter* pvalue)
{
   if (0 == pvalue) return;
   pvalue->numbits = 0;
}

static const OSEnumItem RUA_CauseRadioNetwork_ENUMTAB[] = {
   { OSUTF8("connect-failed"), 1, 14, 2 },
   { OSUTF8("network-release"), 2, 15, 0 },
   { OSUTF8("normal"), 0, 6, 1 },
   { OSUTF8("unspecified"), 3, 11, 3 }
} ;
#define RUA_CauseRadioNetwork_ENUMTABSIZE 4

const OSUTF8CHAR* RUA_CauseRadioNetwork_ToString (OSINT32 value)
{
   OSINT32 idx = value;

   if (idx >= 0 && idx < RUA_CauseRadioNetwork_ENUMTABSIZE) {
      return RUA_CauseRadioNetwork_ENUMTAB
         [RUA_CauseRadioNetwork_ENUMTAB[idx].transidx].name;
   }
   else
      return OSUTF8("_UNKNOWN_");
}

int RUA_CauseRadioNetwork_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, RUA_CauseRadioNetwork* pvalue)
{
   OSUINT32 valueLen = rtxUTF8LenBytes (value);
   OSINT32 idx = rtxLookupEnum (value, valueLen, 
      RUA_CauseRadioNetwork_ENUMTAB, RUA_CauseRadioNetwork_ENUMTABSIZE);

   if (idx >= 0) {
      *pvalue = (RUA_CauseRadioNetwork)
         RUA_CauseRadioNetwork_ENUMTAB[idx].value;
      return 0;
   }
   else {
      rtxErrAddStrParm (pctxt, (const char*)value);
      return LOG_RTERR (pctxt, RTERR_INVENUM);
   }
}

static const OSEnumItem RUA_CauseTransport_ENUMTAB[] = {
   { OSUTF8("transport-resource-unavailable"), 0, 30, 0 },
   { OSUTF8("unspecified"), 1, 11, 1 }
} ;
#define RUA_CauseTransport_ENUMTABSIZE 2

const OSUTF8CHAR* RUA_CauseTransport_ToString (OSINT32 value)
{
   OSINT32 idx = value;

   if (idx >= 0 && idx < RUA_CauseTransport_ENUMTABSIZE) {
      return RUA_CauseTransport_ENUMTAB
         [RUA_CauseTransport_ENUMTAB[idx].transidx].name;
   }
   else
      return OSUTF8("_UNKNOWN_");
}

int RUA_CauseTransport_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, RUA_CauseTransport* pvalue)
{
   OSUINT32 valueLen = rtxUTF8LenBytes (value);
   OSINT32 idx = rtxLookupEnum (value, valueLen, RUA_CauseTransport_ENUMTAB, 
      RUA_CauseTransport_ENUMTABSIZE);

   if (idx >= 0) {
      *pvalue = (RUA_CauseTransport)RUA_CauseTransport_ENUMTAB[idx].value;
      return 0;
   }
   else {
      rtxErrAddStrParm (pctxt, (const char*)value);
      return LOG_RTERR (pctxt, RTERR_INVENUM);
   }
}

static const OSEnumItem RUA_CauseProtocol_ENUMTAB[] = {
   { OSUTF8("abstract-syntax-error-falsely-constructed-message"), 6, 49, 5 },
   { OSUTF8("abstract-syntax-error-ignore-and-notify"), 2, 39, 2 },
   { OSUTF8("abstract-syntax-error-reject"), 1, 28, 1 },
   { OSUTF8("message-not-compatible-with-receiver-state"), 3, 42, 3 },
   { OSUTF8("semantic-error"), 4, 14, 4 },
   { OSUTF8("transfer-syntax-error"), 0, 21, 6 },
   { OSUTF8("unspecified"), 5, 11, 0 }
} ;
#define RUA_CauseProtocol_ENUMTABSIZE 7

const OSUTF8CHAR* RUA_CauseProtocol_ToString (OSINT32 value)
{
   OSINT32 idx = value;

   if (idx >= 0 && idx < RUA_CauseProtocol_ENUMTABSIZE) {
      return RUA_CauseProtocol_ENUMTAB
         [RUA_CauseProtocol_ENUMTAB[idx].transidx].name;
   }
   else
      return OSUTF8("_UNKNOWN_");
}

int RUA_CauseProtocol_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, RUA_CauseProtocol* pvalue)
{
   OSUINT32 valueLen = rtxUTF8LenBytes (value);
   OSINT32 idx = rtxLookupEnum (value, valueLen, RUA_CauseProtocol_ENUMTAB, 
      RUA_CauseProtocol_ENUMTABSIZE);

   if (idx >= 0) {
      *pvalue = (RUA_CauseProtocol)RUA_CauseProtocol_ENUMTAB[idx].value;
      return 0;
   }
   else {
      rtxErrAddStrParm (pctxt, (const char*)value);
      return LOG_RTERR (pctxt, RTERR_INVENUM);
   }
}

static const OSEnumItem RUA_CauseMisc_ENUMTAB[] = {
   { OSUTF8("hardware-failure"), 1, 16, 2 },
   { OSUTF8("o-and-m-intervention"), 2, 20, 0 },
   { OSUTF8("processing-overload"), 0, 19, 1 },
   { OSUTF8("unspecified"), 3, 11, 3 }
} ;
#define RUA_CauseMisc_ENUMTABSIZE 4

const OSUTF8CHAR* RUA_CauseMisc_ToString (OSINT32 value)
{
   OSINT32 idx = value;

   if (idx >= 0 && idx < RUA_CauseMisc_ENUMTABSIZE) {
      return RUA_CauseMisc_ENUMTAB[RUA_CauseMisc_ENUMTAB[idx].transidx].name;
   }
   else
      return OSUTF8("_UNKNOWN_");
}

int RUA_CauseMisc_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, RUA_CauseMisc* pvalue)
{
   OSUINT32 valueLen = rtxUTF8LenBytes (value);
   OSINT32 idx = rtxLookupEnum (value, valueLen, RUA_CauseMisc_ENUMTAB, 
      RUA_CauseMisc_ENUMTABSIZE);

   if (idx >= 0) {
      *pvalue = (RUA_CauseMisc)RUA_CauseMisc_ENUMTAB[idx].value;
      return 0;
   }
   else {
      rtxErrAddStrParm (pctxt, (const char*)value);
      return LOG_RTERR (pctxt, RTERR_INVENUM);
   }
}

static const OSEnumItem RUA_TypeOfError_ENUMTAB[] = {
   { OSUTF8("missing"), 1, 7, 1 },
   { OSUTF8("not-understood"), 0, 14, 0 }
} ;
#define RUA_TypeOfError_ENUMTABSIZE 2

const OSUTF8CHAR* RUA_TypeOfError_ToString (OSINT32 value)
{
   OSINT32 idx = value;

   if (idx >= 0 && idx < RUA_TypeOfError_ENUMTABSIZE) {
      return RUA_TypeOfError_ENUMTAB
         [RUA_TypeOfError_ENUMTAB[idx].transidx].name;
   }
   else
      return OSUTF8("_UNKNOWN_");
}

int RUA_TypeOfError_ToEnum (OSCTXT* pctxt,
   const OSUTF8CHAR* value, RUA_TypeOfError* pvalue)
{
   OSUINT32 valueLen = rtxUTF8LenBytes (value);
   OSINT32 idx = rtxLookupEnum (value, valueLen, RUA_TypeOfError_ENUMTAB, 
      RUA_TypeOfError_ENUMTABSIZE);

   if (idx >= 0) {
      *pvalue = (RUA_TypeOfError)RUA_TypeOfError_ENUMTAB[idx].value;
      return 0;
   }
   else {
      rtxErrAddStrParm (pctxt, (const char*)value);
      return LOG_RTERR (pctxt, RTERR_INVENUM);
   }
}

void asn1Init_RUA_IntraDomainNasNodeSelector_version_later_futurecoding (
   RUA_IntraDomainNasNodeSelector_version_later_futurecoding* pvalue)
{
   if (0 == pvalue) return;
   pvalue->numbits = 0;
}

void asn1Init_RUA_Gsm_map_IDNNS_routingbasis_localPTMSI (
   RUA_Gsm_map_IDNNS_routingbasis_localPTMSI* pvalue)
{
   if (0 == pvalue) return;
   asn1Init_RUA_RoutingParameter (&pvalue->routingparameter);
}

void asn1Init_RUA_Gsm_map_IDNNS_routingbasis_tMSIofsamePLMN (
   RUA_Gsm_map_IDNNS_routingbasis_tMSIofsamePLMN* pvalue)
{
   if (0 == pvalue) return;
   asn1Init_RUA_RoutingParameter (&pvalue->routingparameter);
}

void asn1Init_RUA_Gsm_map_IDNNS_routingbasis_tMSIofdifferentPLMN (
   RUA_Gsm_map_IDNNS_routingbasis_tMSIofdifferentPLMN* pvalue)
{
   if (0 == pvalue) return;
   asn1Init_RUA_RoutingParameter (&pvalue->routingparameter);
}

void asn1Init_RUA_Gsm_map_IDNNS_routingbasis_iMSIresponsetopaging (
   RUA_Gsm_map_IDNNS_routingbasis_iMSIresponsetopaging* pvalue)
{
   if (0 == pvalue) return;
   asn1Init_RUA_RoutingParameter (&pvalue->routingparameter);
}

void asn1Init_RUA_Gsm_map_IDNNS_routingbasis_iMSIcauseUEinitiatedEvent (
   RUA_Gsm_map_IDNNS_routingbasis_iMSIcauseUEinitiatedEvent* pvalue)
{
   if (0 == pvalue) return;
   asn1Init_RUA_RoutingParameter (&pvalue->routingparameter);
}

void asn1Init_RUA_Gsm_map_IDNNS_routingbasis_iMEI (
   RUA_Gsm_map_IDNNS_routingbasis_iMEI* pvalue)
{
   if (0 == pvalue) return;
   asn1Init_RUA_RoutingParameter (&pvalue->routingparameter);
}

void asn1Init_RUA_Gsm_map_IDNNS_routingbasis_spare2 (
   RUA_Gsm_map_IDNNS_routingbasis_spare2* pvalue)
{
   if (0 == pvalue) return;
   asn1Init_RUA_RoutingParameter (&pvalue->routingparameter);
}

void asn1Init_RUA_Gsm_map_IDNNS_routingbasis_spare1 (
   RUA_Gsm_map_IDNNS_routingbasis_spare1* pvalue)
{
   if (0 == pvalue) return;
   asn1Init_RUA_RoutingParameter (&pvalue->routingparameter);
}

void asn1Init_RUA_Gsm_map_IDNNS_routingbasis (
   RUA_Gsm_map_IDNNS_routingbasis* pvalue)
{
   if (0 == pvalue) return;
   pvalue->t = 0;
   OSCRTLMEMSET (&pvalue->u, 0, sizeof(pvalue->u));
}

void asn1Init_RUA_Gsm_map_IDNNS (RUA_Gsm_map_IDNNS* pvalue)
{
   if (0 == pvalue) return;
   asn1Init_RUA_Gsm_map_IDNNS_routingbasis (&pvalue->routingbasis);
}

void asn1Init_RUA_IntraDomainNasNodeSelector_version_release99_cn_Type (
   RUA_IntraDomainNasNodeSelector_version_release99_cn_Type* pvalue)
{
   if (0 == pvalue) return;
   pvalue->t = 0;
   OSCRTLMEMSET (&pvalue->u, 0, sizeof(pvalue->u));
}

void asn1Init_RUA_IntraDomainNasNodeSelector_version_release99 (
   RUA_IntraDomainNasNodeSelector_version_release99* pvalue)
{
   if (0 == pvalue) return;
   asn1Init_RUA_IntraDomainNasNodeSelector_version_release99_cn_Type (&pvalue->cn_Type);
}

void asn1Init_RUA_IntraDomainNasNodeSelector_version_later (
   RUA_IntraDomainNasNodeSelector_version_later* pvalue)
{
   if (0 == pvalue) return;
   asn1Init_RUA_IntraDomainNasNodeSelector_version_later_futurecoding (&pvalue->futurecoding);
}

void asn1Init_RUA_IntraDomainNasNodeSelector_version (
   RUA_IntraDomainNasNodeSelector_version* pvalue)
{
   if (0 == pvalue) return;
   pvalue->t = 0;
   OSCRTLMEMSET (&pvalue->u, 0, sizeof(pvalue->u));
}

void asn1Init_RUA_IntraDomainNasNodeSelector (
   RUA_IntraDomainNasNodeSelector* pvalue)
{
   if (0 == pvalue) return;
   asn1Init_RUA_IntraDomainNasNodeSelector_version (&pvalue->version);
}

void asn1Init_RUA_Cause (RUA_Cause* pvalue)
{
   if (0 == pvalue) return;
   pvalue->t = 0;
   OSCRTLMEMSET (&pvalue->u, 0, sizeof(pvalue->u));
}

void asn1Init_RUA_CriticalityDiagnostics_IE_List_element (
   RUA_CriticalityDiagnostics_IE_List_element* pvalue)
{
   if (0 == pvalue) return;
   OSCRTLMEMSET (&pvalue->m, 0, sizeof (pvalue->m));
   asn1Init_RUA_ProtocolExtensionContainer (&pvalue->iE_Extensions);
   rtxDListFastInit (&pvalue->extElem1);
}

void asn1Init_RUA_CriticalityDiagnostics_IE_List (
   RUA_CriticalityDiagnostics_IE_List* pvalue)
{
   if (0 == pvalue) return;
   rtxDListFastInit (pvalue);
}

void asn1Init_RUA_CriticalityDiagnostics (RUA_CriticalityDiagnostics* pvalue)
{
   if (0 == pvalue) return;
   OSCRTLMEMSET (&pvalue->m, 0, sizeof (pvalue->m));
   asn1Init_RUA_CriticalityDiagnostics_IE_List (&pvalue->iEsCriticalityDiagnostics);
   asn1Init_RUA_ProtocolExtensionContainer (&pvalue->iE_Extensions);
   rtxDListFastInit (&pvalue->extElem1);
}

