SAX$(OBJ): \
    $(XMLINCL)/libxml/parser.h \
    $(XMLINCL)/libxml/tree.h \
    $(XMLINCL)/libxml/pattern.h \
    $(XMLINCL)/libxml/xinclude.h \
    $(XMLINCL)/libxml/encoding.h \
    $(XMLINCL)/libxml/list.h \
    $(XMLINCL)/libxml/xmlversion.h \
    $(XMLINCL)/libxml/xmlsave.h \
    $(XMLINCL)/libxml/hash.h \
    $(XMLINCL)/libxml/xmlreader.h \
    $(XMLINCL)/libxml/xmlexports.h \
    $(XMLINCL)/libxml/parserInternals.h \
    $(XMLINCL)/libxml/nanoftp.h \
    $(XMLINCL)/libxml/xmlschemas.h \
    $(XMLINCL)/libxml/SAX.h \
    $(XMLINCL)/libxml/catalog.h \
    $(XMLINCL)/libxml/xmlIO.h \
    $(LIBXML2SRCDIR)/SAX.c \
    $(XMLINCL)/libxml/entities.h \
    $(XMLINCL)/libxml/uri.h \
    $(XMLINCL)/libxml/nanohttp.h \
    $(LIBXML2SRCDIR)/elfgcchack.h \
    $(XMLINCL)/libxml/xmlmemory.h \
    $(XMLINCL)/libxml/relaxng.h \
    $(LIBXML2SRCDIR)/libxml.h \
    $(XMLINCL)/libxml/HTMLparser.h \
    $(XMLINCL)/libxml/xmlschemastypes.h \
    $(XMLINCL)/libxml/chvalid.h \
    $(XMLINCL)/libxml/schematron.h \
    $(XMLINCL)/libxml/xmlregexp.h \
    $(XMLINCL)/libxml/xpointer.h \
    $(LIBXML2SRCDIR)/config.h \
    $(XMLINCL)/libxml/xmlmodule.h \
    $(XMLINCL)/libxml/globals.h \
    $(XMLINCL)/libxml/xmlstring.h \
    $(XMLINCL)/libxml/xpathInternals.h \
    $(XMLINCL)/libxml/xmlerror.h \
    $(XMLINCL)/libxml/schemasInternals.h \
    $(XMLINCL)/libxml/valid.h \
    $(XMLINCL)/libxml/debugXML.h \
    $(XMLINCL)/libxml/dict.h \
    $(XMLINCL)/libxml/xmlwriter.h \
    $(XMLINCL)/libxml/xlink.h \
    $(XMLINCL)/libxml/xmlautomata.h \
    $(XMLINCL)/libxml/HTMLtree.h \
    $(XMLINCL)/libxml/xmlunicode.h \
    $(XMLINCL)/libxml/c14n.h \
    $(XMLINCL)/libxml/SAX2.h \
    $(XMLINCL)/wincecompat.h \
    $(XMLINCL)/libxml/xpath.h \
    $(XMLINCL)/libxml/DOCBparser.h \
    $(XMLINCL)/libxml/threads.h
	$(CC) $(CFLAGS) -c $(IPATHS) $(LIBXML2SRCDIR)/SAX.c

SAX2$(OBJ): \
    $(XMLINCL)/libxml/parser.h \
    $(XMLINCL)/libxml/tree.h \
    $(XMLINCL)/libxml/pattern.h \
    $(XMLINCL)/libxml/xinclude.h \
    $(XMLINCL)/libxml/encoding.h \
    $(XMLINCL)/libxml/list.h \
    $(XMLINCL)/libxml/xmlversion.h \
    $(XMLINCL)/libxml/xmlsave.h \
    $(XMLINCL)/libxml/hash.h \
    $(XMLINCL)/libxml/xmlreader.h \
    $(XMLINCL)/libxml/xmlexports.h \
    $(XMLINCL)/libxml/parserInternals.h \
    $(XMLINCL)/libxml/nanoftp.h \
    $(XMLINCL)/libxml/xmlschemas.h \
    $(XMLINCL)/libxml/SAX.h \
    $(XMLINCL)/libxml/catalog.h \
    $(XMLINCL)/libxml/xmlIO.h \
    $(XMLINCL)/libxml/entities.h \
    $(XMLINCL)/libxml/uri.h \
    $(XMLINCL)/libxml/nanohttp.h \
    $(LIBXML2SRCDIR)/elfgcchack.h \
    $(LIBXML2SRCDIR)/SAX2.c \
    $(XMLINCL)/libxml/xmlmemory.h \
    $(XMLINCL)/libxml/relaxng.h \
    $(LIBXML2SRCDIR)/libxml.h \
    $(XMLINCL)/libxml/HTMLparser.h \
    $(XMLINCL)/libxml/xmlschemastypes.h \
    $(XMLINCL)/libxml/chvalid.h \
    $(XMLINCL)/libxml/schematron.h \
    $(XMLINCL)/libxml/xmlregexp.h \
    $(XMLINCL)/libxml/xpointer.h \
    $(LIBXML2SRCDIR)/config.h \
    $(XMLINCL)/libxml/xmlmodule.h \
    $(XMLINCL)/libxml/globals.h \
    $(XMLINCL)/libxml/xmlstring.h \
    $(XMLINCL)/libxml/xpathInternals.h \
    $(XMLINCL)/libxml/xmlerror.h \
    $(XMLINCL)/libxml/valid.h \
    $(XMLINCL)/libxml/schemasInternals.h \
    $(XMLINCL)/libxml/debugXML.h \
    $(XMLINCL)/libxml/dict.h \
    $(XMLINCL)/libxml/xmlwriter.h \
    $(XMLINCL)/libxml/xlink.h \
    $(XMLINCL)/libxml/xmlautomata.h \
    $(XMLINCL)/libxml/HTMLtree.h \
    $(XMLINCL)/libxml/xmlunicode.h \
    $(XMLINCL)/libxml/SAX2.h \
    $(XMLINCL)/libxml/c14n.h \
    $(XMLINCL)/wincecompat.h \
    $(XMLINCL)/libxml/xpath.h \
    $(XMLINCL)/libxml/threads.h \
    $(XMLINCL)/libxml/DOCBparser.h
	$(CC) $(CFLAGS) -c $(IPATHS) $(LIBXML2SRCDIR)/SAX2.c

chvalid$(OBJ): \
    $(XMLINCL)/libxml/parser.h \
    $(XMLINCL)/libxml/tree.h \
    $(XMLINCL)/libxml/pattern.h \
    $(XMLINCL)/libxml/xinclude.h \
    $(XMLINCL)/libxml/encoding.h \
    $(XMLINCL)/libxml/list.h \
    $(XMLINCL)/libxml/xmlversion.h \
    $(XMLINCL)/libxml/xmlsave.h \
    $(XMLINCL)/libxml/hash.h \
    $(XMLINCL)/libxml/xmlreader.h \
    $(XMLINCL)/libxml/xmlexports.h \
    $(LIBXML2SRCDIR)/chvalid.c \
    $(XMLINCL)/libxml/parserInternals.h \
    $(XMLINCL)/libxml/nanoftp.h \
    $(XMLINCL)/libxml/xmlschemas.h \
    $(XMLINCL)/libxml/SAX.h \
    $(XMLINCL)/libxml/catalog.h \
    $(XMLINCL)/libxml/xmlIO.h \
    $(XMLINCL)/libxml/entities.h \
    $(XMLINCL)/libxml/uri.h \
    $(XMLINCL)/libxml/nanohttp.h \
    $(LIBXML2SRCDIR)/elfgcchack.h \
    $(XMLINCL)/libxml/xmlmemory.h \
    $(XMLINCL)/libxml/relaxng.h \
    $(LIBXML2SRCDIR)/libxml.h \
    $(XMLINCL)/libxml/HTMLparser.h \
    $(XMLINCL)/libxml/xmlschemastypes.h \
    $(XMLINCL)/libxml/chvalid.h \
    $(XMLINCL)/libxml/schematron.h \
    $(XMLINCL)/libxml/xmlregexp.h \
    $(XMLINCL)/libxml/xpointer.h \
    $(LIBXML2SRCDIR)/config.h \
    $(XMLINCL)/libxml/xmlmodule.h \
    $(XMLINCL)/libxml/globals.h \
    $(XMLINCL)/libxml/xmlstring.h \
    $(XMLINCL)/libxml/xpathInternals.h \
    $(XMLINCL)/libxml/xmlerror.h \
    $(XMLINCL)/libxml/valid.h \
    $(XMLINCL)/libxml/schemasInternals.h \
    $(XMLINCL)/libxml/debugXML.h \
    $(XMLINCL)/libxml/dict.h \
    $(XMLINCL)/libxml/xmlwriter.h \
    $(XMLINCL)/libxml/xlink.h \
    $(XMLINCL)/libxml/xmlautomata.h \
    $(XMLINCL)/libxml/HTMLtree.h \
    $(XMLINCL)/libxml/xmlunicode.h \
    $(XMLINCL)/libxml/SAX2.h \
    $(XMLINCL)/libxml/c14n.h \
    $(XMLINCL)/wincecompat.h \
    $(XMLINCL)/libxml/xpath.h \
    $(XMLINCL)/libxml/threads.h \
    $(XMLINCL)/libxml/DOCBparser.h
	$(CC) $(CFLAGS) -c $(IPATHS) $(LIBXML2SRCDIR)/chvalid.c

debugXML$(OBJ): \
    $(XMLINCL)/libxml/parser.h \
    $(XMLINCL)/libxml/tree.h \
    $(XMLINCL)/libxml/pattern.h \
    $(XMLINCL)/libxml/xinclude.h \
    $(XMLINCL)/libxml/encoding.h \
    $(XMLINCL)/libxml/list.h \
    $(LIBXML2SRCDIR)/debugXML.c \
    $(XMLINCL)/libxml/xmlversion.h \
    $(XMLINCL)/libxml/xmlsave.h \
    $(XMLINCL)/libxml/hash.h \
    $(XMLINCL)/libxml/xmlreader.h \
    $(XMLINCL)/libxml/xmlexports.h \
    $(XMLINCL)/libxml/parserInternals.h \
    $(XMLINCL)/libxml/nanoftp.h \
    $(XMLINCL)/libxml/xmlschemas.h \
    $(XMLINCL)/libxml/SAX.h \
    $(XMLINCL)/libxml/catalog.h \
    $(XMLINCL)/libxml/xmlIO.h \
    $(XMLINCL)/libxml/entities.h \
    $(XMLINCL)/libxml/uri.h \
    $(XMLINCL)/libxml/nanohttp.h \
    $(LIBXML2SRCDIR)/elfgcchack.h \
    $(XMLINCL)/libxml/xmlmemory.h \
    $(XMLINCL)/libxml/relaxng.h \
    $(LIBXML2SRCDIR)/libxml.h \
    $(XMLINCL)/libxml/HTMLparser.h \
    $(XMLINCL)/libxml/xmlschemastypes.h \
    $(XMLINCL)/libxml/chvalid.h \
    $(XMLINCL)/libxml/schematron.h \
    $(XMLINCL)/libxml/xmlregexp.h \
    $(XMLINCL)/libxml/xpointer.h \
    $(LIBXML2SRCDIR)/config.h \
    $(XMLINCL)/libxml/xmlmodule.h \
    $(XMLINCL)/libxml/globals.h \
    $(XMLINCL)/libxml/xmlstring.h \
    $(XMLINCL)/libxml/xpathInternals.h \
    $(XMLINCL)/libxml/xmlerror.h \
    $(XMLINCL)/libxml/valid.h \
    $(XMLINCL)/libxml/schemasInternals.h \
    $(XMLINCL)/libxml/debugXML.h \
    $(XMLINCL)/libxml/dict.h \
    $(XMLINCL)/libxml/xmlwriter.h \
    $(XMLINCL)/libxml/xlink.h \
    $(XMLINCL)/libxml/xmlautomata.h \
    $(XMLINCL)/libxml/HTMLtree.h \
    $(XMLINCL)/libxml/xmlunicode.h \
    $(XMLINCL)/libxml/SAX2.h \
    $(XMLINCL)/libxml/c14n.h \
    $(XMLINCL)/wincecompat.h \
    $(XMLINCL)/libxml/xpath.h \
    $(XMLINCL)/libxml/threads.h \
    $(XMLINCL)/libxml/DOCBparser.h
	$(CC) $(CFLAGS) -c $(IPATHS) $(LIBXML2SRCDIR)/debugXML.c

dict$(OBJ): \
    $(XMLINCL)/libxml/parser.h \
    $(XMLINCL)/libxml/tree.h \
    $(XMLINCL)/libxml/pattern.h \
    $(XMLINCL)/libxml/xinclude.h \
    $(XMLINCL)/libxml/encoding.h \
    $(XMLINCL)/libxml/list.h \
    $(XMLINCL)/libxml/xmlversion.h \
    $(XMLINCL)/libxml/xmlsave.h \
    $(XMLINCL)/libxml/hash.h \
    $(LIBXML2SRCDIR)/dict.c \
    $(XMLINCL)/libxml/xmlreader.h \
    $(XMLINCL)/libxml/xmlexports.h \
    $(XMLINCL)/libxml/parserInternals.h \
    $(XMLINCL)/libxml/nanoftp.h \
    $(XMLINCL)/libxml/xmlschemas.h \
    $(XMLINCL)/libxml/SAX.h \
    $(XMLINCL)/libxml/catalog.h \
    $(XMLINCL)/libxml/xmlIO.h \
    $(XMLINCL)/libxml/entities.h \
    $(XMLINCL)/libxml/uri.h \
    $(XMLINCL)/libxml/nanohttp.h \
    $(LIBXML2SRCDIR)/elfgcchack.h \
    $(XMLINCL)/libxml/xmlmemory.h \
    $(XMLINCL)/libxml/relaxng.h \
    $(LIBXML2SRCDIR)/libxml.h \
    $(XMLINCL)/libxml/HTMLparser.h \
    $(XMLINCL)/libxml/xmlschemastypes.h \
    $(XMLINCL)/libxml/chvalid.h \
    $(XMLINCL)/libxml/schematron.h \
    $(XMLINCL)/libxml/xmlregexp.h \
    $(XMLINCL)/libxml/xpointer.h \
    $(LIBXML2SRCDIR)/config.h \
    $(XMLINCL)/libxml/xmlmodule.h \
    $(XMLINCL)/libxml/globals.h \
    $(XMLINCL)/libxml/xmlstring.h \
    $(XMLINCL)/libxml/xpathInternals.h \
    $(XMLINCL)/libxml/xmlerror.h \
    $(XMLINCL)/libxml/valid.h \
    $(XMLINCL)/libxml/schemasInternals.h \
    $(XMLINCL)/libxml/debugXML.h \
    $(XMLINCL)/libxml/dict.h \
    $(XMLINCL)/libxml/xmlwriter.h \
    $(XMLINCL)/libxml/xlink.h \
    $(XMLINCL)/libxml/xmlautomata.h \
    $(XMLINCL)/libxml/HTMLtree.h \
    $(XMLINCL)/libxml/xmlunicode.h \
    $(XMLINCL)/libxml/SAX2.h \
    $(XMLINCL)/libxml/c14n.h \
    $(XMLINCL)/wincecompat.h \
    $(XMLINCL)/libxml/xpath.h \
    $(XMLINCL)/libxml/threads.h \
    $(XMLINCL)/libxml/DOCBparser.h
	$(CC) $(CFLAGS) -c $(IPATHS) $(LIBXML2SRCDIR)/dict.c

encoding$(OBJ): \
    $(XMLINCL)/libxml/parser.h \
    $(XMLINCL)/libxml/tree.h \
    $(XMLINCL)/libxml/pattern.h \
    $(XMLINCL)/libxml/xinclude.h \
    $(XMLINCL)/libxml/encoding.h \
    $(XMLINCL)/libxml/list.h \
    $(XMLINCL)/libxml/xmlversion.h \
    $(XMLINCL)/libxml/xmlsave.h \
    $(XMLINCL)/libxml/hash.h \
    $(XMLINCL)/libxml/xmlreader.h \
    $(XMLINCL)/libxml/xmlexports.h \
    $(XMLINCL)/libxml/parserInternals.h \
    $(XMLINCL)/libxml/nanoftp.h \
    $(XMLINCL)/libxml/xmlschemas.h \
    $(XMLINCL)/libxml/SAX.h \
    $(XMLINCL)/libxml/catalog.h \
    $(XMLINCL)/libxml/xmlIO.h \
    $(XMLINCL)/libxml/entities.h \
    $(XMLINCL)/libxml/uri.h \
    $(XMLINCL)/libxml/nanohttp.h \
    $(LIBXML2SRCDIR)/elfgcchack.h \
    $(XMLINCL)/libxml/xmlmemory.h \
    $(XMLINCL)/libxml/relaxng.h \
    $(LIBXML2SRCDIR)/libxml.h \
    $(XMLINCL)/libxml/HTMLparser.h \
    $(XMLINCL)/libxml/xmlschemastypes.h \
    $(XMLINCL)/libxml/chvalid.h \
    $(XMLINCL)/libxml/schematron.h \
    $(XMLINCL)/libxml/xmlregexp.h \
    $(XMLINCL)/libxml/xpointer.h \
    $(LIBXML2SRCDIR)/config.h \
    $(XMLINCL)/libxml/xmlmodule.h \
    $(XMLINCL)/libxml/globals.h \
    $(XMLINCL)/libxml/xmlstring.h \
    $(XMLINCL)/libxml/xpathInternals.h \
    $(XMLINCL)/libxml/xmlerror.h \
    $(XMLINCL)/libxml/valid.h \
    $(XMLINCL)/libxml/schemasInternals.h \
    $(XMLINCL)/libxml/debugXML.h \
    $(XMLINCL)/libxml/dict.h \
    $(XMLINCL)/libxml/xmlwriter.h \
    $(XMLINCL)/libxml/xlink.h \
    $(LIBXML2SRCDIR)/encoding.c \
    $(XMLINCL)/libxml/xmlautomata.h \
    $(XMLINCL)/libxml/HTMLtree.h \
    $(XMLINCL)/libxml/xmlunicode.h \
    $(XMLINCL)/libxml/SAX2.h \
    $(XMLINCL)/libxml/c14n.h \
    $(XMLINCL)/wincecompat.h \
    $(XMLINCL)/libxml/xpath.h \
    $(XMLINCL)/libxml/threads.h \
    $(XMLINCL)/libxml/DOCBparser.h
	$(CC) $(CFLAGS) -c $(IPATHS) $(LIBXML2SRCDIR)/encoding.c

entities$(OBJ): \
    $(XMLINCL)/libxml/parser.h \
    $(XMLINCL)/libxml/tree.h \
    $(XMLINCL)/libxml/pattern.h \
    $(XMLINCL)/libxml/xinclude.h \
    $(XMLINCL)/libxml/encoding.h \
    $(XMLINCL)/libxml/list.h \
    $(XMLINCL)/libxml/xmlversion.h \
    $(XMLINCL)/libxml/xmlsave.h \
    $(XMLINCL)/libxml/hash.h \
    $(XMLINCL)/libxml/xmlreader.h \
    $(XMLINCL)/libxml/xmlexports.h \
    $(LIBXML2SRCDIR)/entities.c \
    $(XMLINCL)/libxml/parserInternals.h \
    $(XMLINCL)/libxml/nanoftp.h \
    $(XMLINCL)/libxml/xmlschemas.h \
    $(XMLINCL)/libxml/SAX.h \
    $(XMLINCL)/libxml/catalog.h \
    $(XMLINCL)/libxml/xmlIO.h \
    $(XMLINCL)/libxml/entities.h \
    $(XMLINCL)/libxml/uri.h \
    $(XMLINCL)/libxml/nanohttp.h \
    $(LIBXML2SRCDIR)/elfgcchack.h \
    $(XMLINCL)/libxml/xmlmemory.h \
    $(XMLINCL)/libxml/relaxng.h \
    $(LIBXML2SRCDIR)/libxml.h \
    $(XMLINCL)/libxml/HTMLparser.h \
    $(XMLINCL)/libxml/xmlschemastypes.h \
    $(XMLINCL)/libxml/chvalid.h \
    $(XMLINCL)/libxml/schematron.h \
    $(XMLINCL)/libxml/xmlregexp.h \
    $(XMLINCL)/libxml/xpointer.h \
    $(LIBXML2SRCDIR)/config.h \
    $(XMLINCL)/libxml/xmlmodule.h \
    $(XMLINCL)/libxml/globals.h \
    $(XMLINCL)/libxml/xmlstring.h \
    $(XMLINCL)/libxml/xpathInternals.h \
    $(XMLINCL)/libxml/xmlerror.h \
    $(XMLINCL)/libxml/valid.h \
    $(XMLINCL)/libxml/schemasInternals.h \
    $(XMLINCL)/libxml/debugXML.h \
    $(XMLINCL)/libxml/dict.h \
    $(XMLINCL)/libxml/xmlwriter.h \
    $(XMLINCL)/libxml/xlink.h \
    $(XMLINCL)/libxml/xmlautomata.h \
    $(XMLINCL)/libxml/HTMLtree.h \
    $(XMLINCL)/libxml/xmlunicode.h \
    $(XMLINCL)/libxml/SAX2.h \
    $(XMLINCL)/libxml/c14n.h \
    $(XMLINCL)/wincecompat.h \
    $(XMLINCL)/libxml/xpath.h \
    $(XMLINCL)/libxml/threads.h \
    $(XMLINCL)/libxml/DOCBparser.h
	$(CC) $(CFLAGS) -c $(IPATHS) $(LIBXML2SRCDIR)/entities.c

error$(OBJ): \
    $(XMLINCL)/libxml/parser.h \
    $(XMLINCL)/libxml/tree.h \
    $(XMLINCL)/libxml/pattern.h \
    $(XMLINCL)/libxml/xinclude.h \
    $(XMLINCL)/libxml/encoding.h \
    $(XMLINCL)/libxml/list.h \
    $(XMLINCL)/libxml/xmlversion.h \
    $(XMLINCL)/libxml/xmlsave.h \
    $(XMLINCL)/libxml/hash.h \
    $(XMLINCL)/libxml/xmlreader.h \
    $(XMLINCL)/libxml/xmlexports.h \
    $(XMLINCL)/libxml/parserInternals.h \
    $(XMLINCL)/libxml/nanoftp.h \
    $(XMLINCL)/libxml/xmlschemas.h \
    $(XMLINCL)/libxml/SAX.h \
    $(XMLINCL)/libxml/catalog.h \
    $(XMLINCL)/libxml/xmlIO.h \
    $(XMLINCL)/libxml/entities.h \
    $(XMLINCL)/libxml/uri.h \
    $(XMLINCL)/libxml/nanohttp.h \
    $(LIBXML2SRCDIR)/elfgcchack.h \
    $(XMLINCL)/libxml/xmlmemory.h \
    $(XMLINCL)/libxml/relaxng.h \
    $(LIBXML2SRCDIR)/libxml.h \
    $(XMLINCL)/libxml/HTMLparser.h \
    $(XMLINCL)/libxml/xmlschemastypes.h \
    $(XMLINCL)/libxml/chvalid.h \
    $(XMLINCL)/libxml/schematron.h \
    $(XMLINCL)/libxml/xmlregexp.h \
    $(LIBXML2SRCDIR)/error.c \
    $(XMLINCL)/libxml/xpointer.h \
    $(LIBXML2SRCDIR)/config.h \
    $(XMLINCL)/libxml/xmlmodule.h \
    $(XMLINCL)/libxml/globals.h \
    $(XMLINCL)/libxml/xmlstring.h \
    $(XMLINCL)/libxml/xpathInternals.h \
    $(XMLINCL)/libxml/xmlerror.h \
    $(XMLINCL)/libxml/valid.h \
    $(XMLINCL)/libxml/schemasInternals.h \
    $(XMLINCL)/libxml/debugXML.h \
    $(XMLINCL)/libxml/dict.h \
    $(XMLINCL)/libxml/xmlwriter.h \
    $(XMLINCL)/libxml/xlink.h \
    $(XMLINCL)/libxml/xmlautomata.h \
    $(XMLINCL)/libxml/HTMLtree.h \
    $(XMLINCL)/libxml/xmlunicode.h \
    $(XMLINCL)/libxml/SAX2.h \
    $(XMLINCL)/libxml/c14n.h \
    $(XMLINCL)/wincecompat.h \
    $(XMLINCL)/libxml/xpath.h \
    $(XMLINCL)/libxml/threads.h \
    $(XMLINCL)/libxml/DOCBparser.h
	$(CC) $(CFLAGS) -c $(IPATHS) $(LIBXML2SRCDIR)/error.c

globals$(OBJ): \
    $(XMLINCL)/libxml/parser.h \
    $(XMLINCL)/libxml/tree.h \
    $(XMLINCL)/libxml/pattern.h \
    $(XMLINCL)/libxml/xinclude.h \
    $(XMLINCL)/libxml/encoding.h \
    $(XMLINCL)/libxml/list.h \
    $(XMLINCL)/libxml/xmlversion.h \
    $(XMLINCL)/libxml/xmlsave.h \
    $(XMLINCL)/libxml/hash.h \
    $(XMLINCL)/libxml/xmlreader.h \
    $(XMLINCL)/libxml/xmlexports.h \
    $(XMLINCL)/libxml/parserInternals.h \
    $(XMLINCL)/libxml/nanoftp.h \
    $(XMLINCL)/libxml/xmlschemas.h \
    $(XMLINCL)/libxml/SAX.h \
    $(XMLINCL)/libxml/catalog.h \
    $(XMLINCL)/libxml/xmlIO.h \
    $(XMLINCL)/libxml/entities.h \
    $(XMLINCL)/libxml/uri.h \
    $(XMLINCL)/libxml/nanohttp.h \
    $(LIBXML2SRCDIR)/elfgcchack.h \
    $(XMLINCL)/libxml/xmlmemory.h \
    $(XMLINCL)/libxml/relaxng.h \
    $(LIBXML2SRCDIR)/libxml.h \
    $(XMLINCL)/libxml/HTMLparser.h \
    $(XMLINCL)/libxml/xmlschemastypes.h \
    $(XMLINCL)/libxml/chvalid.h \
    $(XMLINCL)/libxml/schematron.h \
    $(XMLINCL)/libxml/xmlregexp.h \
    $(XMLINCL)/libxml/xpointer.h \
    $(LIBXML2SRCDIR)/config.h \
    $(XMLINCL)/libxml/xmlmodule.h \
    $(XMLINCL)/libxml/globals.h \
    $(XMLINCL)/libxml/xmlstring.h \
    $(XMLINCL)/libxml/xpathInternals.h \
    $(XMLINCL)/libxml/xmlerror.h \
    $(XMLINCL)/libxml/valid.h \
    $(XMLINCL)/libxml/schemasInternals.h \
    $(XMLINCL)/libxml/debugXML.h \
    $(LIBXML2SRCDIR)/globals.c \
    $(XMLINCL)/libxml/dict.h \
    $(XMLINCL)/libxml/xmlwriter.h \
    $(XMLINCL)/libxml/xlink.h \
    $(XMLINCL)/libxml/xmlautomata.h \
    $(XMLINCL)/libxml/HTMLtree.h \
    $(XMLINCL)/libxml/xmlunicode.h \
    $(XMLINCL)/libxml/SAX2.h \
    $(XMLINCL)/libxml/c14n.h \
    $(XMLINCL)/wincecompat.h \
    $(XMLINCL)/libxml/xpath.h \
    $(XMLINCL)/libxml/threads.h \
    $(XMLINCL)/libxml/DOCBparser.h
	$(CC) $(CFLAGS) -c $(IPATHS) $(LIBXML2SRCDIR)/globals.c

hash$(OBJ): \
    $(XMLINCL)/libxml/parser.h \
    $(XMLINCL)/libxml/tree.h \
    $(XMLINCL)/libxml/pattern.h \
    $(XMLINCL)/libxml/xinclude.h \
    $(XMLINCL)/libxml/encoding.h \
    $(XMLINCL)/libxml/list.h \
    $(XMLINCL)/libxml/xmlversion.h \
    $(XMLINCL)/libxml/xmlsave.h \
    $(XMLINCL)/libxml/hash.h \
    $(XMLINCL)/libxml/xmlreader.h \
    $(XMLINCL)/libxml/xmlexports.h \
    $(XMLINCL)/libxml/parserInternals.h \
    $(XMLINCL)/libxml/nanoftp.h \
    $(XMLINCL)/libxml/xmlschemas.h \
    $(XMLINCL)/libxml/SAX.h \
    $(XMLINCL)/libxml/catalog.h \
    $(XMLINCL)/libxml/xmlIO.h \
    $(XMLINCL)/libxml/entities.h \
    $(XMLINCL)/libxml/uri.h \
    $(XMLINCL)/libxml/nanohttp.h \
    $(LIBXML2SRCDIR)/elfgcchack.h \
    $(XMLINCL)/libxml/xmlmemory.h \
    $(XMLINCL)/libxml/relaxng.h \
    $(LIBXML2SRCDIR)/libxml.h \
    $(XMLINCL)/libxml/HTMLparser.h \
    $(XMLINCL)/libxml/xmlschemastypes.h \
    $(XMLINCL)/libxml/chvalid.h \
    $(XMLINCL)/libxml/schematron.h \
    $(XMLINCL)/libxml/xmlregexp.h \
    $(XMLINCL)/libxml/xpointer.h \
    $(LIBXML2SRCDIR)/config.h \
    $(XMLINCL)/libxml/xmlmodule.h \
    $(XMLINCL)/libxml/globals.h \
    $(XMLINCL)/libxml/xmlstring.h \
    $(XMLINCL)/libxml/xpathInternals.h \
    $(XMLINCL)/libxml/xmlerror.h \
    $(XMLINCL)/libxml/valid.h \
    $(XMLINCL)/libxml/schemasInternals.h \
    $(XMLINCL)/libxml/debugXML.h \
    $(XMLINCL)/libxml/dict.h \
    $(XMLINCL)/libxml/xmlwriter.h \
    $(XMLINCL)/libxml/xlink.h \
    $(XMLINCL)/libxml/xmlautomata.h \
    $(XMLINCL)/libxml/HTMLtree.h \
    $(XMLINCL)/libxml/xmlunicode.h \
    $(XMLINCL)/libxml/SAX2.h \
    $(XMLINCL)/libxml/c14n.h \
    $(XMLINCL)/wincecompat.h \
    $(XMLINCL)/libxml/xpath.h \
    $(XMLINCL)/libxml/threads.h \
    $(XMLINCL)/libxml/DOCBparser.h \
    $(LIBXML2SRCDIR)/hash.c
	$(CC) $(CFLAGS) -c $(IPATHS) $(LIBXML2SRCDIR)/hash.c

legacy$(OBJ): \
    $(XMLINCL)/libxml/parser.h \
    $(XMLINCL)/libxml/tree.h \
    $(XMLINCL)/libxml/pattern.h \
    $(XMLINCL)/libxml/xinclude.h \
    $(XMLINCL)/libxml/encoding.h \
    $(XMLINCL)/libxml/list.h \
    $(XMLINCL)/libxml/xmlversion.h \
    $(XMLINCL)/libxml/xmlsave.h \
    $(XMLINCL)/libxml/hash.h \
    $(XMLINCL)/libxml/xmlreader.h \
    $(XMLINCL)/libxml/xmlexports.h \
    $(XMLINCL)/libxml/parserInternals.h \
    $(XMLINCL)/libxml/nanoftp.h \
    $(XMLINCL)/libxml/xmlschemas.h \
    $(XMLINCL)/libxml/SAX.h \
    $(XMLINCL)/libxml/catalog.h \
    $(XMLINCL)/libxml/xmlIO.h \
    $(XMLINCL)/libxml/entities.h \
    $(XMLINCL)/libxml/uri.h \
    $(XMLINCL)/libxml/nanohttp.h \
    $(LIBXML2SRCDIR)/elfgcchack.h \
    $(XMLINCL)/libxml/xmlmemory.h \
    $(XMLINCL)/libxml/relaxng.h \
    $(LIBXML2SRCDIR)/libxml.h \
    $(XMLINCL)/libxml/HTMLparser.h \
    $(XMLINCL)/libxml/xmlschemastypes.h \
    $(XMLINCL)/libxml/chvalid.h \
    $(XMLINCL)/libxml/schematron.h \
    $(XMLINCL)/libxml/xmlregexp.h \
    $(XMLINCL)/libxml/xpointer.h \
    $(LIBXML2SRCDIR)/config.h \
    $(XMLINCL)/libxml/xmlmodule.h \
    $(XMLINCL)/libxml/globals.h \
    $(XMLINCL)/libxml/xmlstring.h \
    $(XMLINCL)/libxml/xpathInternals.h \
    $(LIBXML2SRCDIR)/legacy.c \
    $(XMLINCL)/libxml/xmlerror.h \
    $(XMLINCL)/libxml/valid.h \
    $(XMLINCL)/libxml/schemasInternals.h \
    $(XMLINCL)/libxml/debugXML.h \
    $(XMLINCL)/libxml/dict.h \
    $(XMLINCL)/libxml/xmlwriter.h \
    $(XMLINCL)/libxml/xlink.h \
    $(XMLINCL)/libxml/xmlautomata.h \
    $(XMLINCL)/libxml/HTMLtree.h \
    $(XMLINCL)/libxml/xmlunicode.h \
    $(XMLINCL)/libxml/SAX2.h \
    $(XMLINCL)/libxml/c14n.h \
    $(XMLINCL)/wincecompat.h \
    $(XMLINCL)/libxml/xpath.h \
    $(XMLINCL)/libxml/threads.h \
    $(XMLINCL)/libxml/DOCBparser.h
	$(CC) $(CFLAGS) -c $(IPATHS) $(LIBXML2SRCDIR)/legacy.c

list$(OBJ): \
    $(XMLINCL)/libxml/parser.h \
    $(XMLINCL)/libxml/tree.h \
    $(XMLINCL)/libxml/pattern.h \
    $(XMLINCL)/libxml/xinclude.h \
    $(XMLINCL)/libxml/encoding.h \
    $(XMLINCL)/libxml/list.h \
    $(XMLINCL)/libxml/xmlversion.h \
    $(XMLINCL)/libxml/xmlsave.h \
    $(XMLINCL)/libxml/hash.h \
    $(XMLINCL)/libxml/xmlreader.h \
    $(XMLINCL)/libxml/xmlexports.h \
    $(XMLINCL)/libxml/parserInternals.h \
    $(XMLINCL)/libxml/nanoftp.h \
    $(XMLINCL)/libxml/xmlschemas.h \
    $(XMLINCL)/libxml/SAX.h \
    $(XMLINCL)/libxml/catalog.h \
    $(XMLINCL)/libxml/xmlIO.h \
    $(XMLINCL)/libxml/entities.h \
    $(XMLINCL)/libxml/uri.h \
    $(XMLINCL)/libxml/nanohttp.h \
    $(LIBXML2SRCDIR)/elfgcchack.h \
    $(XMLINCL)/libxml/xmlmemory.h \
    $(XMLINCL)/libxml/relaxng.h \
    $(LIBXML2SRCDIR)/libxml.h \
    $(XMLINCL)/libxml/HTMLparser.h \
    $(XMLINCL)/libxml/xmlschemastypes.h \
    $(XMLINCL)/libxml/chvalid.h \
    $(XMLINCL)/libxml/schematron.h \
    $(XMLINCL)/libxml/xmlregexp.h \
    $(XMLINCL)/libxml/xpointer.h \
    $(LIBXML2SRCDIR)/config.h \
    $(XMLINCL)/libxml/xmlmodule.h \
    $(XMLINCL)/libxml/globals.h \
    $(XMLINCL)/libxml/xmlstring.h \
    $(XMLINCL)/libxml/xpathInternals.h \
    $(XMLINCL)/libxml/xmlerror.h \
    $(XMLINCL)/libxml/valid.h \
    $(XMLINCL)/libxml/schemasInternals.h \
    $(XMLINCL)/libxml/debugXML.h \
    $(XMLINCL)/libxml/dict.h \
    $(XMLINCL)/libxml/xmlwriter.h \
    $(XMLINCL)/libxml/xlink.h \
    $(XMLINCL)/libxml/xmlautomata.h \
    $(XMLINCL)/libxml/HTMLtree.h \
    $(XMLINCL)/libxml/xmlunicode.h \
    $(XMLINCL)/libxml/SAX2.h \
    $(XMLINCL)/libxml/c14n.h \
    $(XMLINCL)/wincecompat.h \
    $(XMLINCL)/libxml/xpath.h \
    $(LIBXML2SRCDIR)/list.c \
    $(XMLINCL)/libxml/threads.h \
    $(XMLINCL)/libxml/DOCBparser.h
	$(CC) $(CFLAGS) -c $(IPATHS) $(LIBXML2SRCDIR)/list.c

parser$(OBJ): \
    $(XMLINCL)/libxml/parser.h \
    $(XMLINCL)/libxml/tree.h \
    $(XMLINCL)/libxml/pattern.h \
    $(XMLINCL)/libxml/xinclude.h \
    $(XMLINCL)/libxml/encoding.h \
    $(XMLINCL)/libxml/list.h \
    $(XMLINCL)/libxml/xmlversion.h \
    $(XMLINCL)/libxml/xmlsave.h \
    $(XMLINCL)/libxml/hash.h \
    $(XMLINCL)/libxml/xmlreader.h \
    $(XMLINCL)/libxml/xmlexports.h \
    $(XMLINCL)/libxml/parserInternals.h \
    $(XMLINCL)/libxml/nanoftp.h \
    $(XMLINCL)/libxml/xmlschemas.h \
    $(XMLINCL)/libxml/SAX.h \
    $(XMLINCL)/libxml/catalog.h \
    $(LIBXML2SRCDIR)/parser.c \
    $(XMLINCL)/libxml/xmlIO.h \
    $(XMLINCL)/libxml/entities.h \
    $(XMLINCL)/libxml/uri.h \
    $(XMLINCL)/libxml/nanohttp.h \
    $(LIBXML2SRCDIR)/elfgcchack.h \
    $(XMLINCL)/libxml/xmlmemory.h \
    $(XMLINCL)/libxml/relaxng.h \
    $(LIBXML2SRCDIR)/libxml.h \
    $(XMLINCL)/libxml/HTMLparser.h \
    $(XMLINCL)/libxml/xmlschemastypes.h \
    $(XMLINCL)/libxml/chvalid.h \
    $(XMLINCL)/libxml/schematron.h \
    $(XMLINCL)/libxml/xmlregexp.h \
    $(XMLINCL)/libxml/xpointer.h \
    $(LIBXML2SRCDIR)/config.h \
    $(XMLINCL)/libxml/xmlmodule.h \
    $(XMLINCL)/libxml/globals.h \
    $(XMLINCL)/libxml/xmlstring.h \
    $(XMLINCL)/libxml/xpathInternals.h \
    $(XMLINCL)/libxml/xmlerror.h \
    $(XMLINCL)/libxml/valid.h \
    $(XMLINCL)/libxml/schemasInternals.h \
    $(XMLINCL)/libxml/debugXML.h \
    $(XMLINCL)/libxml/dict.h \
    $(XMLINCL)/libxml/xmlwriter.h \
    $(XMLINCL)/libxml/xlink.h \
    $(XMLINCL)/libxml/xmlautomata.h \
    $(XMLINCL)/libxml/HTMLtree.h \
    $(XMLINCL)/libxml/xmlunicode.h \
    $(XMLINCL)/libxml/SAX2.h \
    $(XMLINCL)/libxml/c14n.h \
    $(XMLINCL)/wincecompat.h \
    $(XMLINCL)/libxml/xpath.h \
    $(XMLINCL)/libxml/threads.h \
    $(XMLINCL)/libxml/DOCBparser.h
	$(CC) $(CFLAGS) -c $(IPATHS) $(LIBXML2SRCDIR)/parser.c

parserInternals$(OBJ): \
    $(XMLINCL)/libxml/parser.h \
    $(XMLINCL)/libxml/tree.h \
    $(XMLINCL)/libxml/pattern.h \
    $(LIBXML2SRCDIR)/parserInternals.c \
    $(XMLINCL)/libxml/xinclude.h \
    $(XMLINCL)/libxml/encoding.h \
    $(XMLINCL)/libxml/list.h \
    $(XMLINCL)/libxml/xmlversion.h \
    $(XMLINCL)/libxml/xmlsave.h \
    $(XMLINCL)/libxml/hash.h \
    $(XMLINCL)/libxml/xmlreader.h \
    $(XMLINCL)/libxml/xmlexports.h \
    $(XMLINCL)/libxml/parserInternals.h \
    $(XMLINCL)/libxml/nanoftp.h \
    $(XMLINCL)/libxml/xmlschemas.h \
    $(XMLINCL)/libxml/SAX.h \
    $(XMLINCL)/libxml/catalog.h \
    $(XMLINCL)/libxml/xmlIO.h \
    $(XMLINCL)/libxml/entities.h \
    $(XMLINCL)/libxml/uri.h \
    $(XMLINCL)/libxml/nanohttp.h \
    $(LIBXML2SRCDIR)/elfgcchack.h \
    $(XMLINCL)/libxml/xmlmemory.h \
    $(XMLINCL)/libxml/relaxng.h \
    $(LIBXML2SRCDIR)/libxml.h \
    $(XMLINCL)/libxml/HTMLparser.h \
    $(XMLINCL)/libxml/xmlschemastypes.h \
    $(XMLINCL)/libxml/chvalid.h \
    $(XMLINCL)/libxml/schematron.h \
    $(XMLINCL)/libxml/xmlregexp.h \
    $(XMLINCL)/libxml/xpointer.h \
    $(LIBXML2SRCDIR)/config.h \
    $(XMLINCL)/libxml/xmlmodule.h \
    $(XMLINCL)/libxml/globals.h \
    $(XMLINCL)/libxml/xmlstring.h \
    $(XMLINCL)/libxml/xpathInternals.h \
    $(XMLINCL)/libxml/xmlerror.h \
    $(XMLINCL)/libxml/valid.h \
    $(XMLINCL)/libxml/schemasInternals.h \
    $(XMLINCL)/libxml/debugXML.h \
    $(XMLINCL)/libxml/dict.h \
    $(XMLINCL)/libxml/xmlwriter.h \
    $(XMLINCL)/libxml/xlink.h \
    $(XMLINCL)/libxml/xmlautomata.h \
    $(XMLINCL)/libxml/HTMLtree.h \
    $(XMLINCL)/libxml/xmlunicode.h \
    $(XMLINCL)/libxml/SAX2.h \
    $(XMLINCL)/libxml/c14n.h \
    $(XMLINCL)/wincecompat.h \
    $(XMLINCL)/libxml/xpath.h \
    $(XMLINCL)/libxml/threads.h \
    $(XMLINCL)/libxml/DOCBparser.h
	$(CC) $(CFLAGS) -c $(IPATHS) $(LIBXML2SRCDIR)/parserInternals.c

pattern$(OBJ): \
    $(XMLINCL)/libxml/parser.h \
    $(XMLINCL)/libxml/tree.h \
    $(XMLINCL)/libxml/pattern.h \
    $(XMLINCL)/libxml/xinclude.h \
    $(XMLINCL)/libxml/encoding.h \
    $(XMLINCL)/libxml/list.h \
    $(XMLINCL)/libxml/xmlversion.h \
    $(XMLINCL)/libxml/xmlsave.h \
    $(XMLINCL)/libxml/hash.h \
    $(XMLINCL)/libxml/xmlreader.h \
    $(XMLINCL)/libxml/xmlexports.h \
    $(XMLINCL)/libxml/parserInternals.h \
    $(XMLINCL)/libxml/nanoftp.h \
    $(XMLINCL)/libxml/xmlschemas.h \
    $(XMLINCL)/libxml/SAX.h \
    $(XMLINCL)/libxml/catalog.h \
    $(XMLINCL)/libxml/xmlIO.h \
    $(XMLINCL)/libxml/entities.h \
    $(XMLINCL)/libxml/uri.h \
    $(XMLINCL)/libxml/nanohttp.h \
    $(LIBXML2SRCDIR)/elfgcchack.h \
    $(XMLINCL)/libxml/xmlmemory.h \
    $(XMLINCL)/libxml/relaxng.h \
    $(LIBXML2SRCDIR)/libxml.h \
    $(XMLINCL)/libxml/HTMLparser.h \
    $(XMLINCL)/libxml/xmlschemastypes.h \
    $(XMLINCL)/libxml/chvalid.h \
    $(XMLINCL)/libxml/schematron.h \
    $(XMLINCL)/libxml/xmlregexp.h \
    $(XMLINCL)/libxml/xpointer.h \
    $(LIBXML2SRCDIR)/config.h \
    $(LIBXML2SRCDIR)/pattern.c \
    $(XMLINCL)/libxml/xmlmodule.h \
    $(XMLINCL)/libxml/globals.h \
    $(XMLINCL)/libxml/xmlstring.h \
    $(XMLINCL)/libxml/xpathInternals.h \
    $(XMLINCL)/libxml/xmlerror.h \
    $(XMLINCL)/libxml/valid.h \
    $(XMLINCL)/libxml/schemasInternals.h \
    $(XMLINCL)/libxml/debugXML.h \
    $(XMLINCL)/libxml/dict.h \
    $(XMLINCL)/libxml/xmlwriter.h \
    $(XMLINCL)/libxml/xlink.h \
    $(XMLINCL)/libxml/xmlautomata.h \
    $(XMLINCL)/libxml/HTMLtree.h \
    $(XMLINCL)/libxml/xmlunicode.h \
    $(XMLINCL)/libxml/SAX2.h \
    $(XMLINCL)/libxml/c14n.h \
    $(XMLINCL)/wincecompat.h \
    $(XMLINCL)/libxml/xpath.h \
    $(XMLINCL)/libxml/threads.h \
    $(XMLINCL)/libxml/DOCBparser.h
	$(CC) $(CFLAGS) -c $(IPATHS) $(LIBXML2SRCDIR)/pattern.c

relaxng$(OBJ): \
    $(XMLINCL)/libxml/parser.h \
    $(XMLINCL)/libxml/tree.h \
    $(XMLINCL)/libxml/pattern.h \
    $(XMLINCL)/libxml/xinclude.h \
    $(XMLINCL)/libxml/encoding.h \
    $(XMLINCL)/libxml/list.h \
    $(XMLINCL)/libxml/xmlversion.h \
    $(XMLINCL)/libxml/xmlsave.h \
    $(XMLINCL)/libxml/hash.h \
    $(XMLINCL)/libxml/xmlreader.h \
    $(XMLINCL)/libxml/xmlexports.h \
    $(XMLINCL)/libxml/parserInternals.h \
    $(XMLINCL)/libxml/nanoftp.h \
    $(XMLINCL)/libxml/xmlschemas.h \
    $(XMLINCL)/libxml/SAX.h \
    $(XMLINCL)/libxml/catalog.h \
    $(XMLINCL)/libxml/xmlIO.h \
    $(XMLINCL)/libxml/entities.h \
    $(XMLINCL)/libxml/uri.h \
    $(XMLINCL)/libxml/nanohttp.h \
    $(LIBXML2SRCDIR)/elfgcchack.h \
    $(XMLINCL)/libxml/xmlmemory.h \
    $(XMLINCL)/libxml/relaxng.h \
    $(LIBXML2SRCDIR)/libxml.h \
    $(LIBXML2SRCDIR)/relaxng.c \
    $(XMLINCL)/libxml/HTMLparser.h \
    $(XMLINCL)/libxml/xmlschemastypes.h \
    $(XMLINCL)/libxml/chvalid.h \
    $(XMLINCL)/libxml/schematron.h \
    $(XMLINCL)/libxml/xmlregexp.h \
    $(XMLINCL)/libxml/xpointer.h \
    $(LIBXML2SRCDIR)/config.h \
    $(XMLINCL)/libxml/xmlmodule.h \
    $(XMLINCL)/libxml/globals.h \
    $(XMLINCL)/libxml/xmlstring.h \
    $(XMLINCL)/libxml/xpathInternals.h \
    $(XMLINCL)/libxml/xmlerror.h \
    $(XMLINCL)/libxml/valid.h \
    $(XMLINCL)/libxml/schemasInternals.h \
    $(XMLINCL)/libxml/debugXML.h \
    $(XMLINCL)/libxml/dict.h \
    $(XMLINCL)/libxml/xmlwriter.h \
    $(XMLINCL)/libxml/xlink.h \
    $(XMLINCL)/libxml/xmlautomata.h \
    $(XMLINCL)/libxml/HTMLtree.h \
    $(XMLINCL)/libxml/xmlunicode.h \
    $(XMLINCL)/libxml/SAX2.h \
    $(XMLINCL)/libxml/c14n.h \
    $(XMLINCL)/wincecompat.h \
    $(XMLINCL)/libxml/xpath.h \
    $(XMLINCL)/libxml/threads.h \
    $(XMLINCL)/libxml/DOCBparser.h
	$(CC) $(CFLAGS) -c $(IPATHS) $(LIBXML2SRCDIR)/relaxng.c

threads$(OBJ): \
    $(XMLINCL)/libxml/parser.h \
    $(XMLINCL)/libxml/tree.h \
    $(XMLINCL)/libxml/pattern.h \
    $(XMLINCL)/libxml/xinclude.h \
    $(XMLINCL)/libxml/encoding.h \
    $(XMLINCL)/libxml/list.h \
    $(LIBXML2SRCDIR)/threads.c \
    $(XMLINCL)/libxml/xmlversion.h \
    $(XMLINCL)/libxml/xmlsave.h \
    $(XMLINCL)/libxml/hash.h \
    $(XMLINCL)/libxml/xmlreader.h \
    $(XMLINCL)/libxml/xmlexports.h \
    $(XMLINCL)/libxml/parserInternals.h \
    $(XMLINCL)/libxml/nanoftp.h \
    $(XMLINCL)/libxml/xmlschemas.h \
    $(XMLINCL)/libxml/SAX.h \
    $(XMLINCL)/libxml/catalog.h \
    $(XMLINCL)/libxml/xmlIO.h \
    $(XMLINCL)/libxml/entities.h \
    $(XMLINCL)/libxml/uri.h \
    $(XMLINCL)/libxml/nanohttp.h \
    $(LIBXML2SRCDIR)/elfgcchack.h \
    $(XMLINCL)/libxml/xmlmemory.h \
    $(XMLINCL)/libxml/relaxng.h \
    $(LIBXML2SRCDIR)/libxml.h \
    $(XMLINCL)/libxml/HTMLparser.h \
    $(XMLINCL)/libxml/xmlschemastypes.h \
    $(XMLINCL)/libxml/chvalid.h \
    $(XMLINCL)/libxml/schematron.h \
    $(XMLINCL)/libxml/xmlregexp.h \
    $(XMLINCL)/libxml/xpointer.h \
    $(LIBXML2SRCDIR)/config.h \
    $(XMLINCL)/libxml/xmlmodule.h \
    $(XMLINCL)/libxml/globals.h \
    $(XMLINCL)/libxml/xmlstring.h \
    $(XMLINCL)/libxml/xpathInternals.h \
    $(XMLINCL)/libxml/xmlerror.h \
    $(XMLINCL)/libxml/valid.h \
    $(XMLINCL)/libxml/schemasInternals.h \
    $(XMLINCL)/libxml/debugXML.h \
    $(XMLINCL)/libxml/dict.h \
    $(XMLINCL)/libxml/xmlwriter.h \
    $(XMLINCL)/libxml/xlink.h \
    $(XMLINCL)/libxml/xmlautomata.h \
    $(XMLINCL)/libxml/HTMLtree.h \
    $(XMLINCL)/libxml/xmlunicode.h \
    $(XMLINCL)/libxml/SAX2.h \
    $(XMLINCL)/libxml/c14n.h \
    $(XMLINCL)/wincecompat.h \
    $(XMLINCL)/libxml/xpath.h \
    $(XMLINCL)/libxml/threads.h \
    $(XMLINCL)/libxml/DOCBparser.h
	$(CC) $(CFLAGS) -c $(IPATHS) $(LIBXML2SRCDIR)/threads.c

tree$(OBJ): \
    $(XMLINCL)/libxml/parser.h \
    $(XMLINCL)/libxml/tree.h \
    $(XMLINCL)/libxml/pattern.h \
    $(XMLINCL)/libxml/xinclude.h \
    $(XMLINCL)/libxml/encoding.h \
    $(XMLINCL)/libxml/list.h \
    $(XMLINCL)/libxml/xmlversion.h \
    $(XMLINCL)/libxml/xmlsave.h \
    $(XMLINCL)/libxml/hash.h \
    $(XMLINCL)/libxml/xmlreader.h \
    $(XMLINCL)/libxml/xmlexports.h \
    $(XMLINCL)/libxml/parserInternals.h \
    $(XMLINCL)/libxml/nanoftp.h \
    $(XMLINCL)/libxml/xmlschemas.h \
    $(XMLINCL)/libxml/SAX.h \
    $(XMLINCL)/libxml/catalog.h \
    $(XMLINCL)/libxml/xmlIO.h \
    $(XMLINCL)/libxml/entities.h \
    $(XMLINCL)/libxml/uri.h \
    $(XMLINCL)/libxml/nanohttp.h \
    $(LIBXML2SRCDIR)/elfgcchack.h \
    $(XMLINCL)/libxml/xmlmemory.h \
    $(XMLINCL)/libxml/relaxng.h \
    $(LIBXML2SRCDIR)/libxml.h \
    $(XMLINCL)/libxml/HTMLparser.h \
    $(XMLINCL)/libxml/xmlschemastypes.h \
    $(XMLINCL)/libxml/chvalid.h \
    $(XMLINCL)/libxml/schematron.h \
    $(XMLINCL)/libxml/xmlregexp.h \
    $(XMLINCL)/libxml/xpointer.h \
    $(LIBXML2SRCDIR)/config.h \
    $(XMLINCL)/libxml/xmlmodule.h \
    $(XMLINCL)/libxml/globals.h \
    $(XMLINCL)/libxml/xmlstring.h \
    $(XMLINCL)/libxml/xpathInternals.h \
    $(XMLINCL)/libxml/xmlerror.h \
    $(XMLINCL)/libxml/valid.h \
    $(XMLINCL)/libxml/schemasInternals.h \
    $(XMLINCL)/libxml/debugXML.h \
    $(XMLINCL)/libxml/dict.h \
    $(XMLINCL)/libxml/xmlwriter.h \
    $(XMLINCL)/libxml/xlink.h \
    $(XMLINCL)/libxml/xmlautomata.h \
    $(XMLINCL)/libxml/HTMLtree.h \
    $(XMLINCL)/libxml/xmlunicode.h \
    $(XMLINCL)/libxml/SAX2.h \
    $(XMLINCL)/libxml/c14n.h \
    $(XMLINCL)/wincecompat.h \
    $(XMLINCL)/libxml/xpath.h \
    $(XMLINCL)/libxml/threads.h \
    $(XMLINCL)/libxml/DOCBparser.h \
    $(LIBXML2SRCDIR)/tree.c
	$(CC) $(CFLAGS) -c $(IPATHS) $(LIBXML2SRCDIR)/tree.c

trionan$(OBJ): \
    $(LIBXML2SRCDIR)/trionan.c \
    $(LIBXML2SRCDIR)/trionan.h \
    $(LIBXML2SRCDIR)/triodef.h
	$(CC) $(CFLAGS) -c $(IPATHS) $(LIBXML2SRCDIR)/trionan.c

uri$(OBJ): \
    $(XMLINCL)/libxml/parser.h \
    $(XMLINCL)/libxml/tree.h \
    $(XMLINCL)/libxml/pattern.h \
    $(XMLINCL)/libxml/xinclude.h \
    $(XMLINCL)/libxml/encoding.h \
    $(XMLINCL)/libxml/list.h \
    $(XMLINCL)/libxml/xmlversion.h \
    $(XMLINCL)/libxml/xmlsave.h \
    $(XMLINCL)/libxml/hash.h \
    $(XMLINCL)/libxml/xmlreader.h \
    $(XMLINCL)/libxml/xmlexports.h \
    $(XMLINCL)/libxml/parserInternals.h \
    $(XMLINCL)/libxml/nanoftp.h \
    $(XMLINCL)/libxml/xmlschemas.h \
    $(XMLINCL)/libxml/SAX.h \
    $(XMLINCL)/libxml/catalog.h \
    $(XMLINCL)/libxml/xmlIO.h \
    $(XMLINCL)/libxml/entities.h \
    $(XMLINCL)/libxml/uri.h \
    $(XMLINCL)/libxml/nanohttp.h \
    $(LIBXML2SRCDIR)/elfgcchack.h \
    $(XMLINCL)/libxml/xmlmemory.h \
    $(XMLINCL)/libxml/relaxng.h \
    $(LIBXML2SRCDIR)/libxml.h \
    $(LIBXML2SRCDIR)/uri.c \
    $(XMLINCL)/libxml/HTMLparser.h \
    $(XMLINCL)/libxml/xmlschemastypes.h \
    $(XMLINCL)/libxml/chvalid.h \
    $(XMLINCL)/libxml/schematron.h \
    $(XMLINCL)/libxml/xmlregexp.h \
    $(XMLINCL)/libxml/xpointer.h \
    $(LIBXML2SRCDIR)/config.h \
    $(XMLINCL)/libxml/xmlmodule.h \
    $(XMLINCL)/libxml/globals.h \
    $(XMLINCL)/libxml/xmlstring.h \
    $(XMLINCL)/libxml/xpathInternals.h \
    $(XMLINCL)/libxml/xmlerror.h \
    $(XMLINCL)/libxml/valid.h \
    $(XMLINCL)/libxml/schemasInternals.h \
    $(XMLINCL)/libxml/debugXML.h \
    $(XMLINCL)/libxml/dict.h \
    $(XMLINCL)/libxml/xmlwriter.h \
    $(XMLINCL)/libxml/xlink.h \
    $(XMLINCL)/libxml/xmlautomata.h \
    $(XMLINCL)/libxml/HTMLtree.h \
    $(XMLINCL)/libxml/xmlunicode.h \
    $(XMLINCL)/libxml/SAX2.h \
    $(XMLINCL)/libxml/c14n.h \
    $(XMLINCL)/wincecompat.h \
    $(XMLINCL)/libxml/xpath.h \
    $(XMLINCL)/libxml/threads.h \
    $(XMLINCL)/libxml/DOCBparser.h
	$(CC) $(CFLAGS) -c $(IPATHS) $(LIBXML2SRCDIR)/uri.c

valid$(OBJ): \
    $(XMLINCL)/libxml/parser.h \
    $(XMLINCL)/libxml/tree.h \
    $(XMLINCL)/libxml/pattern.h \
    $(XMLINCL)/libxml/xinclude.h \
    $(XMLINCL)/libxml/encoding.h \
    $(XMLINCL)/libxml/list.h \
    $(XMLINCL)/libxml/xmlversion.h \
    $(XMLINCL)/libxml/xmlsave.h \
    $(XMLINCL)/libxml/hash.h \
    $(XMLINCL)/libxml/xmlreader.h \
    $(XMLINCL)/libxml/xmlexports.h \
    $(XMLINCL)/libxml/parserInternals.h \
    $(XMLINCL)/libxml/nanoftp.h \
    $(XMLINCL)/libxml/xmlschemas.h \
    $(XMLINCL)/libxml/SAX.h \
    $(XMLINCL)/libxml/catalog.h \
    $(XMLINCL)/libxml/xmlIO.h \
    $(XMLINCL)/libxml/entities.h \
    $(XMLINCL)/libxml/uri.h \
    $(XMLINCL)/libxml/nanohttp.h \
    $(LIBXML2SRCDIR)/elfgcchack.h \
    $(XMLINCL)/libxml/xmlmemory.h \
    $(XMLINCL)/libxml/relaxng.h \
    $(LIBXML2SRCDIR)/libxml.h \
    $(XMLINCL)/libxml/HTMLparser.h \
    $(XMLINCL)/libxml/xmlschemastypes.h \
    $(XMLINCL)/libxml/chvalid.h \
    $(XMLINCL)/libxml/schematron.h \
    $(XMLINCL)/libxml/xmlregexp.h \
    $(XMLINCL)/libxml/xpointer.h \
    $(LIBXML2SRCDIR)/config.h \
    $(XMLINCL)/libxml/xmlmodule.h \
    $(XMLINCL)/libxml/globals.h \
    $(XMLINCL)/libxml/xmlstring.h \
    $(XMLINCL)/libxml/xpathInternals.h \
    $(XMLINCL)/libxml/xmlerror.h \
    $(XMLINCL)/libxml/valid.h \
    $(XMLINCL)/libxml/schemasInternals.h \
    $(LIBXML2SRCDIR)/valid.c \
    $(XMLINCL)/libxml/debugXML.h \
    $(XMLINCL)/libxml/dict.h \
    $(XMLINCL)/libxml/xmlwriter.h \
    $(XMLINCL)/libxml/xlink.h \
    $(XMLINCL)/libxml/xmlautomata.h \
    $(XMLINCL)/libxml/HTMLtree.h \
    $(XMLINCL)/libxml/xmlunicode.h \
    $(XMLINCL)/libxml/SAX2.h \
    $(XMLINCL)/libxml/c14n.h \
    $(XMLINCL)/wincecompat.h \
    $(XMLINCL)/libxml/xpath.h \
    $(XMLINCL)/libxml/threads.h \
    $(XMLINCL)/libxml/DOCBparser.h
	$(CC) $(CFLAGS) -c $(IPATHS) $(LIBXML2SRCDIR)/valid.c

xinclude$(OBJ): \
    $(XMLINCL)/libxml/parser.h \
    $(XMLINCL)/libxml/tree.h \
    $(XMLINCL)/libxml/pattern.h \
    $(XMLINCL)/libxml/xinclude.h \
    $(XMLINCL)/libxml/encoding.h \
    $(XMLINCL)/libxml/list.h \
    $(XMLINCL)/libxml/xmlversion.h \
    $(XMLINCL)/libxml/xmlsave.h \
    $(XMLINCL)/libxml/hash.h \
    $(XMLINCL)/libxml/xmlreader.h \
    $(XMLINCL)/libxml/xmlexports.h \
    $(XMLINCL)/libxml/parserInternals.h \
    $(XMLINCL)/libxml/nanoftp.h \
    $(XMLINCL)/libxml/xmlschemas.h \
    $(XMLINCL)/libxml/SAX.h \
    $(XMLINCL)/libxml/catalog.h \
    $(XMLINCL)/libxml/xmlIO.h \
    $(XMLINCL)/libxml/entities.h \
    $(XMLINCL)/libxml/uri.h \
    $(XMLINCL)/libxml/nanohttp.h \
    $(LIBXML2SRCDIR)/elfgcchack.h \
    $(XMLINCL)/libxml/xmlmemory.h \
    $(XMLINCL)/libxml/relaxng.h \
    $(LIBXML2SRCDIR)/libxml.h \
    $(XMLINCL)/libxml/HTMLparser.h \
    $(XMLINCL)/libxml/xmlschemastypes.h \
    $(XMLINCL)/libxml/chvalid.h \
    $(XMLINCL)/libxml/schematron.h \
    $(XMLINCL)/libxml/xmlregexp.h \
    $(LIBXML2SRCDIR)/xinclude.c \
    $(XMLINCL)/libxml/xpointer.h \
    $(LIBXML2SRCDIR)/config.h \
    $(XMLINCL)/libxml/xmlmodule.h \
    $(XMLINCL)/libxml/globals.h \
    $(XMLINCL)/libxml/xmlstring.h \
    $(XMLINCL)/libxml/xpathInternals.h \
    $(XMLINCL)/libxml/xmlerror.h \
    $(XMLINCL)/libxml/valid.h \
    $(XMLINCL)/libxml/schemasInternals.h \
    $(XMLINCL)/libxml/debugXML.h \
    $(XMLINCL)/libxml/dict.h \
    $(XMLINCL)/libxml/xmlwriter.h \
    $(XMLINCL)/libxml/xlink.h \
    $(XMLINCL)/libxml/xmlautomata.h \
    $(XMLINCL)/libxml/HTMLtree.h \
    $(XMLINCL)/libxml/xmlunicode.h \
    $(XMLINCL)/libxml/SAX2.h \
    $(XMLINCL)/libxml/c14n.h \
    $(XMLINCL)/wincecompat.h \
    $(XMLINCL)/libxml/xpath.h \
    $(XMLINCL)/libxml/threads.h \
    $(XMLINCL)/libxml/DOCBparser.h
	$(CC) $(CFLAGS) -c $(IPATHS) $(LIBXML2SRCDIR)/xinclude.c

xlink$(OBJ): \
    $(XMLINCL)/libxml/parser.h \
    $(XMLINCL)/libxml/tree.h \
    $(XMLINCL)/libxml/pattern.h \
    $(XMLINCL)/libxml/xinclude.h \
    $(XMLINCL)/libxml/encoding.h \
    $(XMLINCL)/libxml/list.h \
    $(XMLINCL)/libxml/xmlversion.h \
    $(XMLINCL)/libxml/xmlsave.h \
    $(XMLINCL)/libxml/hash.h \
    $(XMLINCL)/libxml/xmlreader.h \
    $(XMLINCL)/libxml/xmlexports.h \
    $(XMLINCL)/libxml/parserInternals.h \
    $(XMLINCL)/libxml/nanoftp.h \
    $(XMLINCL)/libxml/xmlschemas.h \
    $(XMLINCL)/libxml/SAX.h \
    $(XMLINCL)/libxml/catalog.h \
    $(LIBXML2SRCDIR)/xlink.c \
    $(XMLINCL)/libxml/xmlIO.h \
    $(XMLINCL)/libxml/entities.h \
    $(XMLINCL)/libxml/uri.h \
    $(XMLINCL)/libxml/nanohttp.h \
    $(LIBXML2SRCDIR)/elfgcchack.h \
    $(XMLINCL)/libxml/xmlmemory.h \
    $(XMLINCL)/libxml/relaxng.h \
    $(LIBXML2SRCDIR)/libxml.h \
    $(XMLINCL)/libxml/HTMLparser.h \
    $(XMLINCL)/libxml/xmlschemastypes.h \
    $(XMLINCL)/libxml/chvalid.h \
    $(XMLINCL)/libxml/schematron.h \
    $(XMLINCL)/libxml/xmlregexp.h \
    $(XMLINCL)/libxml/xpointer.h \
    $(LIBXML2SRCDIR)/config.h \
    $(XMLINCL)/libxml/xmlmodule.h \
    $(XMLINCL)/libxml/globals.h \
    $(XMLINCL)/libxml/xmlstring.h \
    $(XMLINCL)/libxml/xpathInternals.h \
    $(XMLINCL)/libxml/xmlerror.h \
    $(XMLINCL)/libxml/valid.h \
    $(XMLINCL)/libxml/schemasInternals.h \
    $(XMLINCL)/libxml/debugXML.h \
    $(XMLINCL)/libxml/dict.h \
    $(XMLINCL)/libxml/xmlwriter.h \
    $(XMLINCL)/libxml/xlink.h \
    $(XMLINCL)/libxml/xmlautomata.h \
    $(XMLINCL)/libxml/HTMLtree.h \
    $(XMLINCL)/libxml/xmlunicode.h \
    $(XMLINCL)/libxml/SAX2.h \
    $(XMLINCL)/libxml/c14n.h \
    $(XMLINCL)/wincecompat.h \
    $(XMLINCL)/libxml/xpath.h \
    $(XMLINCL)/libxml/threads.h \
    $(XMLINCL)/libxml/DOCBparser.h
	$(CC) $(CFLAGS) -c $(IPATHS) $(LIBXML2SRCDIR)/xlink.c

xmlIO$(OBJ): \
    $(XMLINCL)/libxml/parser.h \
    $(XMLINCL)/libxml/tree.h \
    $(XMLINCL)/libxml/pattern.h \
    $(XMLINCL)/libxml/xinclude.h \
    $(XMLINCL)/libxml/encoding.h \
    $(XMLINCL)/libxml/list.h \
    $(XMLINCL)/libxml/xmlversion.h \
    $(XMLINCL)/libxml/xmlsave.h \
    $(XMLINCL)/libxml/hash.h \
    $(XMLINCL)/libxml/xmlreader.h \
    $(XMLINCL)/libxml/xmlexports.h \
    $(XMLINCL)/libxml/parserInternals.h \
    $(XMLINCL)/libxml/nanoftp.h \
    $(XMLINCL)/libxml/xmlschemas.h \
    $(XMLINCL)/libxml/SAX.h \
    $(XMLINCL)/libxml/catalog.h \
    $(XMLINCL)/libxml/xmlIO.h \
    $(XMLINCL)/libxml/entities.h \
    $(XMLINCL)/libxml/uri.h \
    $(XMLINCL)/libxml/nanohttp.h \
    $(LIBXML2SRCDIR)/elfgcchack.h \
    $(XMLINCL)/libxml/xmlmemory.h \
    $(XMLINCL)/libxml/relaxng.h \
    $(LIBXML2SRCDIR)/libxml.h \
    $(XMLINCL)/libxml/HTMLparser.h \
    $(XMLINCL)/libxml/xmlschemastypes.h \
    $(XMLINCL)/libxml/chvalid.h \
    $(XMLINCL)/libxml/schematron.h \
    $(XMLINCL)/libxml/xmlregexp.h \
    $(XMLINCL)/libxml/xpointer.h \
    $(LIBXML2SRCDIR)/config.h \
    $(XMLINCL)/libxml/xmlmodule.h \
    $(XMLINCL)/libxml/globals.h \
    $(XMLINCL)/libxml/xmlstring.h \
    $(XMLINCL)/libxml/xpathInternals.h \
    $(XMLINCL)/libxml/xmlerror.h \
    $(XMLINCL)/libxml/valid.h \
    $(XMLINCL)/libxml/schemasInternals.h \
    $(XMLINCL)/libxml/debugXML.h \
    $(XMLINCL)/libxml/dict.h \
    $(LIBXML2SRCDIR)/xmlIO.c \
    $(XMLINCL)/libxml/xmlwriter.h \
    $(XMLINCL)/libxml/xlink.h \
    $(XMLINCL)/libxml/xmlautomata.h \
    $(XMLINCL)/libxml/HTMLtree.h \
    $(XMLINCL)/libxml/xmlunicode.h \
    $(XMLINCL)/libxml/SAX2.h \
    $(XMLINCL)/libxml/c14n.h \
    $(XMLINCL)/wincecompat.h \
    $(XMLINCL)/libxml/xpath.h \
    $(XMLINCL)/libxml/threads.h \
    $(XMLINCL)/libxml/DOCBparser.h
	$(CC) $(CFLAGS) -c $(IPATHS) $(LIBXML2SRCDIR)/xmlIO.c

xmlmemory$(OBJ): \
    $(XMLINCL)/libxml/parser.h \
    $(XMLINCL)/libxml/tree.h \
    $(XMLINCL)/libxml/pattern.h \
    $(XMLINCL)/libxml/xinclude.h \
    $(XMLINCL)/libxml/encoding.h \
    $(XMLINCL)/libxml/list.h \
    $(XMLINCL)/libxml/xmlversion.h \
    $(XMLINCL)/libxml/xmlsave.h \
    $(XMLINCL)/libxml/hash.h \
    $(XMLINCL)/libxml/xmlreader.h \
    $(XMLINCL)/libxml/xmlexports.h \
    $(LIBXML2SRCDIR)/xmlmemory.c \
    $(XMLINCL)/libxml/parserInternals.h \
    $(XMLINCL)/libxml/nanoftp.h \
    $(XMLINCL)/libxml/xmlschemas.h \
    $(XMLINCL)/libxml/SAX.h \
    $(XMLINCL)/libxml/catalog.h \
    $(XMLINCL)/libxml/xmlIO.h \
    $(XMLINCL)/libxml/entities.h \
    $(XMLINCL)/libxml/uri.h \
    $(XMLINCL)/libxml/nanohttp.h \
    $(LIBXML2SRCDIR)/elfgcchack.h \
    $(XMLINCL)/libxml/xmlmemory.h \
    $(XMLINCL)/libxml/relaxng.h \
    $(LIBXML2SRCDIR)/libxml.h \
    $(XMLINCL)/libxml/HTMLparser.h \
    $(XMLINCL)/libxml/xmlschemastypes.h \
    $(XMLINCL)/libxml/chvalid.h \
    $(XMLINCL)/libxml/schematron.h \
    $(XMLINCL)/libxml/xmlregexp.h \
    $(XMLINCL)/libxml/xpointer.h \
    $(LIBXML2SRCDIR)/config.h \
    $(XMLINCL)/libxml/xmlmodule.h \
    $(XMLINCL)/libxml/globals.h \
    $(XMLINCL)/libxml/xmlstring.h \
    $(XMLINCL)/libxml/xpathInternals.h \
    $(XMLINCL)/libxml/xmlerror.h \
    $(XMLINCL)/libxml/valid.h \
    $(XMLINCL)/libxml/schemasInternals.h \
    $(XMLINCL)/libxml/debugXML.h \
    $(XMLINCL)/libxml/dict.h \
    $(XMLINCL)/libxml/xmlwriter.h \
    $(XMLINCL)/libxml/xlink.h \
    $(XMLINCL)/libxml/xmlautomata.h \
    $(XMLINCL)/libxml/HTMLtree.h \
    $(XMLINCL)/libxml/xmlunicode.h \
    $(XMLINCL)/libxml/SAX2.h \
    $(XMLINCL)/libxml/c14n.h \
    $(XMLINCL)/wincecompat.h \
    $(XMLINCL)/libxml/xpath.h \
    $(XMLINCL)/libxml/threads.h \
    $(XMLINCL)/libxml/DOCBparser.h
	$(CC) $(CFLAGS) -c $(IPATHS) $(LIBXML2SRCDIR)/xmlmemory.c

xmlmodule$(OBJ): \
    $(XMLINCL)/libxml/parser.h \
    $(XMLINCL)/libxml/tree.h \
    $(XMLINCL)/libxml/pattern.h \
    $(XMLINCL)/libxml/xinclude.h \
    $(XMLINCL)/libxml/encoding.h \
    $(XMLINCL)/libxml/list.h \
    $(XMLINCL)/libxml/xmlversion.h \
    $(XMLINCL)/libxml/xmlsave.h \
    $(XMLINCL)/libxml/hash.h \
    $(XMLINCL)/libxml/xmlreader.h \
    $(XMLINCL)/libxml/xmlexports.h \
    $(LIBXML2SRCDIR)/xmlmodule.c \
    $(XMLINCL)/libxml/parserInternals.h \
    $(XMLINCL)/libxml/nanoftp.h \
    $(XMLINCL)/libxml/xmlschemas.h \
    $(XMLINCL)/libxml/SAX.h \
    $(XMLINCL)/libxml/catalog.h \
    $(XMLINCL)/libxml/xmlIO.h \
    $(XMLINCL)/libxml/entities.h \
    $(XMLINCL)/libxml/uri.h \
    $(XMLINCL)/libxml/nanohttp.h \
    $(LIBXML2SRCDIR)/elfgcchack.h \
    $(XMLINCL)/libxml/xmlmemory.h \
    $(XMLINCL)/libxml/relaxng.h \
    $(LIBXML2SRCDIR)/libxml.h \
    $(XMLINCL)/libxml/HTMLparser.h \
    $(XMLINCL)/libxml/xmlschemastypes.h \
    $(XMLINCL)/libxml/chvalid.h \
    $(XMLINCL)/libxml/schematron.h \
    $(XMLINCL)/libxml/xmlregexp.h \
    $(XMLINCL)/libxml/xpointer.h \
    $(LIBXML2SRCDIR)/config.h \
    $(XMLINCL)/libxml/xmlmodule.h \
    $(XMLINCL)/libxml/globals.h \
    $(XMLINCL)/libxml/xmlstring.h \
    $(XMLINCL)/libxml/xpathInternals.h \
    $(XMLINCL)/libxml/xmlerror.h \
    $(XMLINCL)/libxml/valid.h \
    $(XMLINCL)/libxml/schemasInternals.h \
    $(XMLINCL)/libxml/debugXML.h \
    $(XMLINCL)/libxml/dict.h \
    $(XMLINCL)/libxml/xmlwriter.h \
    $(XMLINCL)/libxml/xlink.h \
    $(XMLINCL)/libxml/xmlautomata.h \
    $(XMLINCL)/libxml/HTMLtree.h \
    $(XMLINCL)/libxml/xmlunicode.h \
    $(XMLINCL)/libxml/SAX2.h \
    $(XMLINCL)/libxml/c14n.h \
    $(XMLINCL)/wincecompat.h \
    $(XMLINCL)/libxml/xpath.h \
    $(XMLINCL)/libxml/threads.h \
    $(XMLINCL)/libxml/DOCBparser.h
	$(CC) $(CFLAGS) -c $(IPATHS) $(LIBXML2SRCDIR)/xmlmodule.c

xmlreader$(OBJ): \
    $(XMLINCL)/libxml/parser.h \
    $(XMLINCL)/libxml/tree.h \
    $(XMLINCL)/libxml/pattern.h \
    $(XMLINCL)/libxml/xinclude.h \
    $(XMLINCL)/libxml/encoding.h \
    $(XMLINCL)/libxml/list.h \
    $(XMLINCL)/libxml/xmlversion.h \
    $(XMLINCL)/libxml/xmlsave.h \
    $(XMLINCL)/libxml/hash.h \
    $(XMLINCL)/libxml/xmlreader.h \
    $(XMLINCL)/libxml/xmlexports.h \
    $(XMLINCL)/libxml/parserInternals.h \
    $(XMLINCL)/libxml/nanoftp.h \
    $(XMLINCL)/libxml/xmlschemas.h \
    $(XMLINCL)/libxml/SAX.h \
    $(XMLINCL)/libxml/catalog.h \
    $(LIBXML2SRCDIR)/xmlreader.c \
    $(XMLINCL)/libxml/xmlIO.h \
    $(XMLINCL)/libxml/entities.h \
    $(XMLINCL)/libxml/uri.h \
    $(XMLINCL)/libxml/nanohttp.h \
    $(LIBXML2SRCDIR)/elfgcchack.h \
    $(XMLINCL)/libxml/xmlmemory.h \
    $(XMLINCL)/libxml/relaxng.h \
    $(LIBXML2SRCDIR)/libxml.h \
    $(XMLINCL)/libxml/HTMLparser.h \
    $(XMLINCL)/libxml/xmlschemastypes.h \
    $(XMLINCL)/libxml/chvalid.h \
    $(XMLINCL)/libxml/schematron.h \
    $(XMLINCL)/libxml/xmlregexp.h \
    $(XMLINCL)/libxml/xpointer.h \
    $(LIBXML2SRCDIR)/config.h \
    $(XMLINCL)/libxml/xmlmodule.h \
    $(XMLINCL)/libxml/globals.h \
    $(XMLINCL)/libxml/xmlstring.h \
    $(XMLINCL)/libxml/xpathInternals.h \
    $(XMLINCL)/libxml/xmlerror.h \
    $(XMLINCL)/libxml/valid.h \
    $(XMLINCL)/libxml/schemasInternals.h \
    $(XMLINCL)/libxml/debugXML.h \
    $(XMLINCL)/libxml/dict.h \
    $(XMLINCL)/libxml/xmlwriter.h \
    $(XMLINCL)/libxml/xlink.h \
    $(XMLINCL)/libxml/xmlautomata.h \
    $(XMLINCL)/libxml/HTMLtree.h \
    $(XMLINCL)/libxml/xmlunicode.h \
    $(XMLINCL)/libxml/SAX2.h \
    $(XMLINCL)/libxml/c14n.h \
    $(XMLINCL)/wincecompat.h \
    $(XMLINCL)/libxml/xpath.h \
    $(XMLINCL)/libxml/threads.h \
    $(XMLINCL)/libxml/DOCBparser.h
	$(CC) $(CFLAGS) -c $(IPATHS) $(LIBXML2SRCDIR)/xmlreader.c

xmlregexp$(OBJ): \
    $(XMLINCL)/libxml/parser.h \
    $(XMLINCL)/libxml/tree.h \
    $(XMLINCL)/libxml/pattern.h \
    $(XMLINCL)/libxml/xinclude.h \
    $(XMLINCL)/libxml/encoding.h \
    $(XMLINCL)/libxml/list.h \
    $(XMLINCL)/libxml/xmlversion.h \
    $(XMLINCL)/libxml/xmlsave.h \
    $(XMLINCL)/libxml/hash.h \
    $(XMLINCL)/libxml/xmlreader.h \
    $(XMLINCL)/libxml/xmlexports.h \
    $(XMLINCL)/libxml/parserInternals.h \
    $(XMLINCL)/libxml/nanoftp.h \
    $(XMLINCL)/libxml/xmlschemas.h \
    $(XMLINCL)/libxml/SAX.h \
    $(XMLINCL)/libxml/catalog.h \
    $(XMLINCL)/libxml/xmlIO.h \
    $(XMLINCL)/libxml/entities.h \
    $(XMLINCL)/libxml/uri.h \
    $(XMLINCL)/libxml/nanohttp.h \
    $(LIBXML2SRCDIR)/elfgcchack.h \
    $(XMLINCL)/libxml/xmlmemory.h \
    $(XMLINCL)/libxml/relaxng.h \
    $(LIBXML2SRCDIR)/libxml.h \
    $(XMLINCL)/libxml/HTMLparser.h \
    $(XMLINCL)/libxml/xmlschemastypes.h \
    $(XMLINCL)/libxml/chvalid.h \
    $(XMLINCL)/libxml/schematron.h \
    $(XMLINCL)/libxml/xmlregexp.h \
    $(XMLINCL)/libxml/xpointer.h \
    $(LIBXML2SRCDIR)/config.h \
    $(XMLINCL)/libxml/xmlmodule.h \
    $(XMLINCL)/libxml/globals.h \
    $(LIBXML2SRCDIR)/xmlregexp.c \
    $(XMLINCL)/libxml/xmlstring.h \
    $(XMLINCL)/libxml/xpathInternals.h \
    $(XMLINCL)/libxml/xmlerror.h \
    $(XMLINCL)/libxml/valid.h \
    $(XMLINCL)/libxml/schemasInternals.h \
    $(XMLINCL)/libxml/debugXML.h \
    $(XMLINCL)/libxml/dict.h \
    $(XMLINCL)/libxml/xmlwriter.h \
    $(XMLINCL)/libxml/xlink.h \
    $(XMLINCL)/libxml/xmlautomata.h \
    $(XMLINCL)/libxml/HTMLtree.h \
    $(XMLINCL)/libxml/xmlunicode.h \
    $(XMLINCL)/libxml/SAX2.h \
    $(XMLINCL)/libxml/c14n.h \
    $(XMLINCL)/wincecompat.h \
    $(XMLINCL)/libxml/xpath.h \
    $(XMLINCL)/libxml/threads.h \
    $(XMLINCL)/libxml/DOCBparser.h
	$(CC) $(CFLAGS) -c $(IPATHS) $(LIBXML2SRCDIR)/xmlregexp.c

xmlsave$(OBJ): \
    $(XMLINCL)/libxml/parser.h \
    $(XMLINCL)/libxml/tree.h \
    $(XMLINCL)/libxml/pattern.h \
    $(XMLINCL)/libxml/xinclude.h \
    $(XMLINCL)/libxml/encoding.h \
    $(XMLINCL)/libxml/list.h \
    $(XMLINCL)/libxml/xmlversion.h \
    $(XMLINCL)/libxml/xmlsave.h \
    $(XMLINCL)/libxml/hash.h \
    $(XMLINCL)/libxml/xmlreader.h \
    $(XMLINCL)/libxml/xmlexports.h \
    $(XMLINCL)/libxml/parserInternals.h \
    $(XMLINCL)/libxml/nanoftp.h \
    $(XMLINCL)/libxml/xmlschemas.h \
    $(LIBXML2SRCDIR)/xmlsave.c \
    $(XMLINCL)/libxml/SAX.h \
    $(XMLINCL)/libxml/catalog.h \
    $(XMLINCL)/libxml/xmlIO.h \
    $(XMLINCL)/libxml/entities.h \
    $(XMLINCL)/libxml/uri.h \
    $(XMLINCL)/libxml/nanohttp.h \
    $(LIBXML2SRCDIR)/elfgcchack.h \
    $(XMLINCL)/libxml/xmlmemory.h \
    $(XMLINCL)/libxml/relaxng.h \
    $(LIBXML2SRCDIR)/libxml.h \
    $(XMLINCL)/libxml/HTMLparser.h \
    $(XMLINCL)/libxml/xmlschemastypes.h \
    $(XMLINCL)/libxml/chvalid.h \
    $(XMLINCL)/libxml/schematron.h \
    $(XMLINCL)/libxml/xmlregexp.h \
    $(XMLINCL)/libxml/xpointer.h \
    $(LIBXML2SRCDIR)/config.h \
    $(XMLINCL)/libxml/xmlmodule.h \
    $(XMLINCL)/libxml/globals.h \
    $(XMLINCL)/libxml/xmlstring.h \
    $(XMLINCL)/libxml/xpathInternals.h \
    $(XMLINCL)/libxml/xmlerror.h \
    $(XMLINCL)/libxml/valid.h \
    $(XMLINCL)/libxml/schemasInternals.h \
    $(XMLINCL)/libxml/debugXML.h \
    $(XMLINCL)/libxml/dict.h \
    $(XMLINCL)/libxml/xmlwriter.h \
    $(XMLINCL)/libxml/xlink.h \
    $(XMLINCL)/libxml/xmlautomata.h \
    $(XMLINCL)/libxml/HTMLtree.h \
    $(XMLINCL)/libxml/xmlunicode.h \
    $(XMLINCL)/libxml/SAX2.h \
    $(XMLINCL)/libxml/c14n.h \
    $(XMLINCL)/wincecompat.h \
    $(XMLINCL)/libxml/xpath.h \
    $(XMLINCL)/libxml/threads.h \
    $(XMLINCL)/libxml/DOCBparser.h
	$(CC) $(CFLAGS) -c $(IPATHS) $(LIBXML2SRCDIR)/xmlsave.c

xmlschemas$(OBJ): \
    $(XMLINCL)/libxml/parser.h \
    $(XMLINCL)/libxml/tree.h \
    $(XMLINCL)/libxml/pattern.h \
    $(XMLINCL)/libxml/xinclude.h \
    $(XMLINCL)/libxml/encoding.h \
    $(XMLINCL)/libxml/list.h \
    $(XMLINCL)/libxml/xmlversion.h \
    $(XMLINCL)/libxml/xmlsave.h \
    $(XMLINCL)/libxml/hash.h \
    $(XMLINCL)/libxml/xmlreader.h \
    $(XMLINCL)/libxml/xmlexports.h \
    $(XMLINCL)/libxml/parserInternals.h \
    $(XMLINCL)/libxml/nanoftp.h \
    $(XMLINCL)/libxml/xmlschemas.h \
    $(XMLINCL)/libxml/SAX.h \
    $(XMLINCL)/libxml/catalog.h \
    $(XMLINCL)/libxml/xmlIO.h \
    $(XMLINCL)/libxml/entities.h \
    $(XMLINCL)/libxml/uri.h \
    $(XMLINCL)/libxml/nanohttp.h \
    $(LIBXML2SRCDIR)/elfgcchack.h \
    $(XMLINCL)/libxml/xmlmemory.h \
    $(XMLINCL)/libxml/relaxng.h \
    $(LIBXML2SRCDIR)/libxml.h \
    $(XMLINCL)/libxml/HTMLparser.h \
    $(XMLINCL)/libxml/xmlschemastypes.h \
    $(XMLINCL)/libxml/chvalid.h \
    $(XMLINCL)/libxml/schematron.h \
    $(XMLINCL)/libxml/xmlregexp.h \
    $(XMLINCL)/libxml/xpointer.h \
    $(LIBXML2SRCDIR)/config.h \
    $(XMLINCL)/libxml/xmlmodule.h \
    $(XMLINCL)/libxml/globals.h \
    $(XMLINCL)/libxml/xmlstring.h \
    $(XMLINCL)/libxml/xpathInternals.h \
    $(LIBXML2SRCDIR)/xmlschemas.c \
    $(XMLINCL)/libxml/xmlerror.h \
    $(XMLINCL)/libxml/valid.h \
    $(XMLINCL)/libxml/schemasInternals.h \
    $(XMLINCL)/libxml/debugXML.h \
    $(XMLINCL)/libxml/dict.h \
    $(XMLINCL)/libxml/xmlwriter.h \
    $(XMLINCL)/libxml/xlink.h \
    $(XMLINCL)/libxml/xmlautomata.h \
    $(XMLINCL)/libxml/HTMLtree.h \
    $(XMLINCL)/libxml/xmlunicode.h \
    $(XMLINCL)/libxml/SAX2.h \
    $(XMLINCL)/libxml/c14n.h \
    $(XMLINCL)/wincecompat.h \
    $(XMLINCL)/libxml/xpath.h \
    $(XMLINCL)/libxml/threads.h \
    $(XMLINCL)/libxml/DOCBparser.h
	$(CC) $(CFLAGS) -c $(IPATHS) $(LIBXML2SRCDIR)/xmlschemas.c

xmlschemastypes$(OBJ): \
    $(XMLINCL)/libxml/parser.h \
    $(XMLINCL)/libxml/tree.h \
    $(XMLINCL)/libxml/pattern.h \
    $(XMLINCL)/libxml/xinclude.h \
    $(XMLINCL)/libxml/encoding.h \
    $(XMLINCL)/libxml/list.h \
    $(XMLINCL)/libxml/xmlversion.h \
    $(XMLINCL)/libxml/xmlsave.h \
    $(XMLINCL)/libxml/hash.h \
    $(XMLINCL)/libxml/xmlreader.h \
    $(XMLINCL)/libxml/xmlexports.h \
    $(XMLINCL)/libxml/parserInternals.h \
    $(XMLINCL)/libxml/nanoftp.h \
    $(XMLINCL)/libxml/xmlschemas.h \
    $(XMLINCL)/libxml/SAX.h \
    $(XMLINCL)/libxml/catalog.h \
    $(XMLINCL)/libxml/xmlIO.h \
    $(XMLINCL)/libxml/entities.h \
    $(XMLINCL)/libxml/uri.h \
    $(XMLINCL)/libxml/nanohttp.h \
    $(LIBXML2SRCDIR)/elfgcchack.h \
    $(XMLINCL)/libxml/xmlmemory.h \
    $(XMLINCL)/libxml/relaxng.h \
    $(LIBXML2SRCDIR)/libxml.h \
    $(XMLINCL)/libxml/HTMLparser.h \
    $(XMLINCL)/libxml/xmlschemastypes.h \
    $(XMLINCL)/libxml/chvalid.h \
    $(XMLINCL)/libxml/schematron.h \
    $(XMLINCL)/libxml/xmlregexp.h \
    $(LIBXML2SRCDIR)/xmlschemastypes.c \
    $(XMLINCL)/libxml/xpointer.h \
    $(LIBXML2SRCDIR)/config.h \
    $(XMLINCL)/libxml/xmlmodule.h \
    $(XMLINCL)/libxml/globals.h \
    $(XMLINCL)/libxml/xmlstring.h \
    $(XMLINCL)/libxml/xpathInternals.h \
    $(XMLINCL)/libxml/xmlerror.h \
    $(XMLINCL)/libxml/valid.h \
    $(XMLINCL)/libxml/schemasInternals.h \
    $(XMLINCL)/libxml/debugXML.h \
    $(XMLINCL)/libxml/dict.h \
    $(XMLINCL)/libxml/xmlwriter.h \
    $(XMLINCL)/libxml/xlink.h \
    $(XMLINCL)/libxml/xmlautomata.h \
    $(XMLINCL)/libxml/HTMLtree.h \
    $(XMLINCL)/libxml/xmlunicode.h \
    $(XMLINCL)/libxml/SAX2.h \
    $(XMLINCL)/libxml/c14n.h \
    $(XMLINCL)/wincecompat.h \
    $(XMLINCL)/libxml/xpath.h \
    $(XMLINCL)/libxml/threads.h \
    $(XMLINCL)/libxml/DOCBparser.h
	$(CC) $(CFLAGS) -c $(IPATHS) $(LIBXML2SRCDIR)/xmlschemastypes.c

xmlstring$(OBJ): \
    $(XMLINCL)/libxml/parser.h \
    $(XMLINCL)/libxml/tree.h \
    $(XMLINCL)/libxml/pattern.h \
    $(XMLINCL)/libxml/xinclude.h \
    $(XMLINCL)/libxml/encoding.h \
    $(XMLINCL)/libxml/list.h \
    $(XMLINCL)/libxml/xmlversion.h \
    $(XMLINCL)/libxml/xmlsave.h \
    $(XMLINCL)/libxml/hash.h \
    $(XMLINCL)/libxml/xmlreader.h \
    $(XMLINCL)/libxml/xmlexports.h \
    $(XMLINCL)/libxml/parserInternals.h \
    $(XMLINCL)/libxml/nanoftp.h \
    $(XMLINCL)/libxml/xmlschemas.h \
    $(XMLINCL)/libxml/SAX.h \
    $(XMLINCL)/libxml/catalog.h \
    $(XMLINCL)/libxml/xmlIO.h \
    $(XMLINCL)/libxml/entities.h \
    $(XMLINCL)/libxml/uri.h \
    $(XMLINCL)/libxml/nanohttp.h \
    $(LIBXML2SRCDIR)/elfgcchack.h \
    $(XMLINCL)/libxml/xmlmemory.h \
    $(XMLINCL)/libxml/relaxng.h \
    $(LIBXML2SRCDIR)/libxml.h \
    $(XMLINCL)/libxml/HTMLparser.h \
    $(XMLINCL)/libxml/xmlschemastypes.h \
    $(XMLINCL)/libxml/chvalid.h \
    $(XMLINCL)/libxml/schematron.h \
    $(XMLINCL)/libxml/xmlregexp.h \
    $(XMLINCL)/libxml/xpointer.h \
    $(LIBXML2SRCDIR)/config.h \
    $(XMLINCL)/libxml/xmlmodule.h \
    $(XMLINCL)/libxml/globals.h \
    $(XMLINCL)/libxml/xmlstring.h \
    $(XMLINCL)/libxml/xpathInternals.h \
    $(XMLINCL)/libxml/xmlerror.h \
    $(XMLINCL)/libxml/valid.h \
    $(XMLINCL)/libxml/schemasInternals.h \
    $(XMLINCL)/libxml/debugXML.h \
    $(XMLINCL)/libxml/dict.h \
    $(XMLINCL)/libxml/xmlwriter.h \
    $(XMLINCL)/libxml/xlink.h \
    $(XMLINCL)/libxml/xmlautomata.h \
    $(XMLINCL)/libxml/HTMLtree.h \
    $(XMLINCL)/libxml/xmlunicode.h \
    $(XMLINCL)/libxml/SAX2.h \
    $(XMLINCL)/libxml/c14n.h \
    $(XMLINCL)/wincecompat.h \
    $(XMLINCL)/libxml/xpath.h \
    $(XMLINCL)/libxml/threads.h \
    $(XMLINCL)/libxml/DOCBparser.h \
    $(LIBXML2SRCDIR)/xmlstring.c
	$(CC) $(CFLAGS) -c $(IPATHS) $(LIBXML2SRCDIR)/xmlstring.c

xmlunicode$(OBJ): \
    $(XMLINCL)/libxml/parser.h \
    $(XMLINCL)/libxml/tree.h \
    $(XMLINCL)/libxml/pattern.h \
    $(XMLINCL)/libxml/xinclude.h \
    $(XMLINCL)/libxml/encoding.h \
    $(XMLINCL)/libxml/list.h \
    $(XMLINCL)/libxml/xmlversion.h \
    $(XMLINCL)/libxml/xmlsave.h \
    $(XMLINCL)/libxml/hash.h \
    $(XMLINCL)/libxml/xmlreader.h \
    $(XMLINCL)/libxml/xmlexports.h \
    $(XMLINCL)/libxml/parserInternals.h \
    $(XMLINCL)/libxml/nanoftp.h \
    $(XMLINCL)/libxml/xmlschemas.h \
    $(XMLINCL)/libxml/SAX.h \
    $(XMLINCL)/libxml/catalog.h \
    $(LIBXML2SRCDIR)/xmlunicode.c \
    $(XMLINCL)/libxml/xmlIO.h \
    $(XMLINCL)/libxml/entities.h \
    $(XMLINCL)/libxml/uri.h \
    $(XMLINCL)/libxml/nanohttp.h \
    $(LIBXML2SRCDIR)/elfgcchack.h \
    $(XMLINCL)/libxml/xmlmemory.h \
    $(XMLINCL)/libxml/relaxng.h \
    $(LIBXML2SRCDIR)/libxml.h \
    $(XMLINCL)/libxml/HTMLparser.h \
    $(XMLINCL)/libxml/xmlschemastypes.h \
    $(XMLINCL)/libxml/chvalid.h \
    $(XMLINCL)/libxml/schematron.h \
    $(XMLINCL)/libxml/xmlregexp.h \
    $(XMLINCL)/libxml/xpointer.h \
    $(LIBXML2SRCDIR)/config.h \
    $(XMLINCL)/libxml/xmlmodule.h \
    $(XMLINCL)/libxml/globals.h \
    $(XMLINCL)/libxml/xmlstring.h \
    $(XMLINCL)/libxml/xpathInternals.h \
    $(XMLINCL)/libxml/xmlerror.h \
    $(XMLINCL)/libxml/valid.h \
    $(XMLINCL)/libxml/schemasInternals.h \
    $(XMLINCL)/libxml/debugXML.h \
    $(XMLINCL)/libxml/dict.h \
    $(XMLINCL)/libxml/xmlwriter.h \
    $(XMLINCL)/libxml/xlink.h \
    $(XMLINCL)/libxml/xmlautomata.h \
    $(XMLINCL)/libxml/HTMLtree.h \
    $(XMLINCL)/libxml/xmlunicode.h \
    $(XMLINCL)/libxml/SAX2.h \
    $(XMLINCL)/libxml/c14n.h \
    $(XMLINCL)/wincecompat.h \
    $(XMLINCL)/libxml/xpath.h \
    $(XMLINCL)/libxml/threads.h \
    $(XMLINCL)/libxml/DOCBparser.h
	$(CC) $(CFLAGS) -c $(IPATHS) $(LIBXML2SRCDIR)/xmlunicode.c

xpath$(OBJ): \
    $(XMLINCL)/libxml/parser.h \
    $(XMLINCL)/libxml/tree.h \
    $(XMLINCL)/libxml/pattern.h \
    $(XMLINCL)/libxml/xinclude.h \
    $(XMLINCL)/libxml/encoding.h \
    $(XMLINCL)/libxml/list.h \
    $(LIBXML2SRCDIR)/trionan.c \
    $(XMLINCL)/libxml/xmlversion.h \
    $(XMLINCL)/libxml/xmlsave.h \
    $(XMLINCL)/libxml/hash.h \
    $(XMLINCL)/libxml/xmlreader.h \
    $(XMLINCL)/libxml/xmlexports.h \
    $(XMLINCL)/libxml/parserInternals.h \
    $(XMLINCL)/libxml/nanoftp.h \
    $(XMLINCL)/libxml/xmlschemas.h \
    $(XMLINCL)/libxml/SAX.h \
    $(XMLINCL)/libxml/catalog.h \
    $(XMLINCL)/libxml/xmlIO.h \
    $(XMLINCL)/libxml/entities.h \
    $(XMLINCL)/libxml/uri.h \
    $(XMLINCL)/libxml/nanohttp.h \
    $(LIBXML2SRCDIR)/elfgcchack.h \
    $(XMLINCL)/libxml/xmlmemory.h \
    $(XMLINCL)/libxml/relaxng.h \
    $(LIBXML2SRCDIR)/libxml.h \
    $(XMLINCL)/libxml/HTMLparser.h \
    $(XMLINCL)/libxml/xmlschemastypes.h \
    $(XMLINCL)/libxml/chvalid.h \
    $(XMLINCL)/libxml/schematron.h \
    $(LIBXML2SRCDIR)/trionan.h \
    $(XMLINCL)/libxml/xmlregexp.h \
    $(XMLINCL)/libxml/xpointer.h \
    $(LIBXML2SRCDIR)/config.h \
    $(LIBXML2SRCDIR)/xpath.c \
    $(XMLINCL)/libxml/xmlmodule.h \
    $(XMLINCL)/libxml/globals.h \
    $(XMLINCL)/libxml/xmlstring.h \
    $(XMLINCL)/libxml/xpathInternals.h \
    $(XMLINCL)/libxml/xmlerror.h \
    $(XMLINCL)/libxml/valid.h \
    $(XMLINCL)/libxml/schemasInternals.h \
    $(XMLINCL)/libxml/debugXML.h \
    $(XMLINCL)/libxml/dict.h \
    $(XMLINCL)/libxml/xmlwriter.h \
    $(XMLINCL)/libxml/xlink.h \
    $(XMLINCL)/libxml/xmlautomata.h \
    $(XMLINCL)/libxml/HTMLtree.h \
    $(XMLINCL)/libxml/xmlunicode.h \
    $(XMLINCL)/libxml/SAX2.h \
    $(XMLINCL)/libxml/c14n.h \
    $(XMLINCL)/wincecompat.h \
    $(XMLINCL)/libxml/xpath.h \
    $(XMLINCL)/libxml/threads.h \
    $(XMLINCL)/libxml/DOCBparser.h \
    $(LIBXML2SRCDIR)/triodef.h
	$(CC) $(CFLAGS) -c $(IPATHS) $(LIBXML2SRCDIR)/xpath.c

xpointer$(OBJ): \
    $(XMLINCL)/libxml/parser.h \
    $(XMLINCL)/libxml/tree.h \
    $(XMLINCL)/libxml/pattern.h \
    $(XMLINCL)/libxml/xinclude.h \
    $(XMLINCL)/libxml/encoding.h \
    $(XMLINCL)/libxml/list.h \
    $(XMLINCL)/libxml/xmlversion.h \
    $(XMLINCL)/libxml/xmlsave.h \
    $(XMLINCL)/libxml/hash.h \
    $(XMLINCL)/libxml/xmlreader.h \
    $(XMLINCL)/libxml/xmlexports.h \
    $(XMLINCL)/libxml/parserInternals.h \
    $(XMLINCL)/libxml/nanoftp.h \
    $(XMLINCL)/libxml/xmlschemas.h \
    $(XMLINCL)/libxml/SAX.h \
    $(XMLINCL)/libxml/catalog.h \
    $(XMLINCL)/libxml/xmlIO.h \
    $(XMLINCL)/libxml/entities.h \
    $(XMLINCL)/libxml/uri.h \
    $(XMLINCL)/libxml/nanohttp.h \
    $(LIBXML2SRCDIR)/elfgcchack.h \
    $(XMLINCL)/libxml/xmlmemory.h \
    $(XMLINCL)/libxml/relaxng.h \
    $(LIBXML2SRCDIR)/libxml.h \
    $(XMLINCL)/libxml/HTMLparser.h \
    $(LIBXML2SRCDIR)/xpointer.c \
    $(XMLINCL)/libxml/xmlschemastypes.h \
    $(XMLINCL)/libxml/chvalid.h \
    $(XMLINCL)/libxml/schematron.h \
    $(XMLINCL)/libxml/xmlregexp.h \
    $(XMLINCL)/libxml/xpointer.h \
    $(LIBXML2SRCDIR)/config.h \
    $(XMLINCL)/libxml/xmlmodule.h \
    $(XMLINCL)/libxml/globals.h \
    $(XMLINCL)/libxml/xmlstring.h \
    $(XMLINCL)/libxml/xpathInternals.h \
    $(XMLINCL)/libxml/xmlerror.h \
    $(XMLINCL)/libxml/valid.h \
    $(XMLINCL)/libxml/schemasInternals.h \
    $(XMLINCL)/libxml/debugXML.h \
    $(XMLINCL)/libxml/dict.h \
    $(XMLINCL)/libxml/xmlwriter.h \
    $(XMLINCL)/libxml/xlink.h \
    $(XMLINCL)/libxml/xmlautomata.h \
    $(XMLINCL)/libxml/HTMLtree.h \
    $(XMLINCL)/libxml/xmlunicode.h \
    $(XMLINCL)/libxml/SAX2.h \
    $(XMLINCL)/libxml/c14n.h \
    $(XMLINCL)/wincecompat.h \
    $(XMLINCL)/libxml/xpath.h \
    $(XMLINCL)/libxml/threads.h \
    $(XMLINCL)/libxml/DOCBparser.h
	$(CC) $(CFLAGS) -c $(IPATHS) $(LIBXML2SRCDIR)/xpointer.c

