OSRT_COMMON_RTOBJECTS = \
rtxArrayList$(OBJ) \
rtxBase64$(OBJ) \
rtxBigInt$(OBJ) \
rtxBigIntArithmetic$(OBJ) \
rtxBigIntCommon$(OBJ) \
rtxBitDecode$(OBJ) \
rtxBitEncode$(OBJ) \
rtxBitString$(OBJ) \
rtxCharStr$(OBJ) \
rtxCheckBuffer$(OBJ) \
rtxContext$(OBJ) \
rtxCopyAsciiText$(OBJ) \
rtxCopyUTF8Text$(OBJ) \
rtxDatesParse$(OBJ) \
rtxDatesPrint$(OBJ) \
rtxDatesToString$(OBJ) \
rtxDateTime$(OBJ) \
rtxDateTimeCompare$(OBJ) \
rtxDateTimeCompare2$(OBJ) \
rtxDateTimeParse$(OBJ) \
rtxDateTimeParseCommon$(OBJ) \
rtxDateTimeToString$(OBJ) \
rtxDateTimeToStringCommon$(OBJ) \
rtxDateTimePrint$(OBJ) \
rtxDecimalHelper$(OBJ) \
rtxDiag$(OBJ) \
rtxDiagBitTrace$(OBJ) \
rtxDiagBitTraceHTML$(OBJ) \
rtxDiagBitTracePrint$(OBJ) \
rtxDList$(OBJ) \
rtxDuration$(OBJ) \
rtxDynBitSet$(OBJ) \
rtxDynPtrArray$(OBJ) \
rtxError$(OBJ) \
rtxFile$(OBJ) \
rtxFloat$(OBJ) \
rtxHashMap$(OBJ) \
rtxHashMapStr2Int$(OBJ) \
rtxHashMapStr2UInt$(OBJ) \
rtxHexCharsToBin$(OBJ) \
rtxHexDump$(OBJ) \
rtxIntToCharStr$(OBJ) \
rtxInt64ToCharStr$(OBJ) \
rtxLookupEnum$(OBJ) \
rtxMemBuf$(OBJ) \
rtxMemDefs$(OBJ) \
rtxMemFreeOpenSeqExt$(OBJ) \
rtxMemFuncs$(OBJ) \
rtxMemHeap$(OBJ) \
rtxMemHeapCreate$(OBJ) \
rtxPattern$(OBJ) \
rtxPrint$(OBJ) \
rtxPrintStream$(OBJ) \
rtxPrintToStream$(OBJ) \
rtxRegExp$(OBJ) \
rtxRegExp2$(OBJ) \
rtxRegExpPrint$(OBJ) \
rtxRealHelper$(OBJ) \
rtxScalarDList$(OBJ) \
rtxSList$(OBJ) \
rtxSocket$(OBJ) \
rtxStack$(OBJ) \
rtxStream$(OBJ) \
rtxStreamBuffered$(OBJ) \
rtxStreamCtxtBuf$(OBJ) \
rtxStreamDirectBuf$(OBJ) \
rtxStreamFile$(OBJ) \
rtxStreamMemory$(OBJ) \
rtxStreamRelease$(OBJ) \
rtxStreamSocket$(OBJ) \
rtxToken$(OBJ) \
rtxTestNumericEnum$(OBJ) \
rtxTestNumericEnum64$(OBJ) \
rtxTestNumericEnumU64$(OBJ) \
rtxTestNumericEnumU32$(OBJ) \
rtxTokenConst$(OBJ) \
rtxUIntToCharStr$(OBJ) \
rtxUInt64ToCharStr$(OBJ) \
rtxUTF8$(OBJ) \
rtxUTF8StrToBool$(OBJ) \
rtxUTF8StrToDouble$(OBJ) \
rtxUTF8StrToDynHexStr$(OBJ) \
rtxUTF8StrToInt$(OBJ) \
rtxUTF8StrToInt64$(OBJ) \
rtxUTF8StrToUInt$(OBJ) \
rtxUTF8StrToUInt64$(OBJ) \
rtxUTF8StrToNamedBits$(OBJ) \
rtxUTF8ToDynUniStr$(OBJ) \
rtxUnicode$(OBJ) \
rtxUtil$(OBJ) \
rtxUtil64$(OBJ) \
rtxWriteBytes$(OBJ) \
rtxXmlQName$(OBJ) \
rtxXmlStr$(OBJ)

OSRT_C_RTOBJECTS = \
$(OSRT_COMMON_RTOBJECTS) \
$(OSRT_C_OSRTOBJECTS) \
rtxMemory$(OBJ)

OSRT_CPP_OBJECTS = \
OSRTContext$(OBJ) \
OSRTCtxtHolder$(OBJ) \
OSRTFileInputStream$(OBJ) \
OSRTFileOutputStream$(OBJ) \
OSRTInputStream$(OBJ) \
OSRTMemBuf$(OBJ) \
OSRTMemoryInputStream$(OBJ) \
OSRTMemoryOutputStream$(OBJ) \
OSRTMsgBuf$(OBJ) \
OSRTOutputStream$(OBJ) \
OSRTSocket$(OBJ) \
OSRTSocketInputStream$(OBJ) \
OSRTSocketOutputStream$(OBJ) \
OSRTStream$(OBJ) \
OSRTString$(OBJ)
